import type { ToolSpec } from "../types";

/**
 * The AI tools.
 *
 * Every tool in this file has `engine: "ai"`, which is the one engine that is
 * not an engine at all: there is no worker and no WASM, because the work is
 * done by a language model on a server. That makes this the only category on
 * the site where the text you type is sent somewhere, and it is why the engine
 * has its own name rather than being folded into `pure`. A reader scanning the
 * registry should be able to tell which tools leave the device by looking.
 *
 * Two consequences run through every spec below:
 *
 *  - **No `accepts`.** These tools take typed or pasted text and nothing else.
 *    Keeping files out of the category is what lets the site go on saying, of
 *    all 148 tools without an asterisk, that your files never leave your device.
 *  - **Options are the whole prompt surface.** The browser never sends a
 *    prompt; it sends a slug and these option values. Anything the visitor can
 *    steer has to be declared here, which means the server can validate it
 *    against this file before a single token is spent.
 *
 * The exception is `readability-checker`, which sits in this category because
 * that is where people look for it, and runs on `pure` because reading scores
 * are arithmetic. It needs no server and says so.
 */

/** Offered wherever a tool can answer in a language other than the input's. */
const LANGUAGES = [
  { value: "english", label: "English" },
  { value: "hindi", label: "Hindi" },
  { value: "bengali", label: "Bengali" },
  { value: "assamese", label: "Assamese" },
  { value: "tamil", label: "Tamil" },
  { value: "telugu", label: "Telugu" },
  { value: "marathi", label: "Marathi" },
  { value: "gujarati", label: "Gujarati" },
  { value: "kannada", label: "Kannada" },
  { value: "malayalam", label: "Malayalam" },
  { value: "punjabi", label: "Punjabi" },
  { value: "urdu", label: "Urdu" },
  { value: "arabic", label: "Arabic" },
  { value: "chinese", label: "Chinese (Simplified)" },
  { value: "dutch", label: "Dutch" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "indonesian", label: "Indonesian" },
  { value: "italian", label: "Italian" },
  { value: "japanese", label: "Japanese" },
  { value: "korean", label: "Korean" },
  { value: "polish", label: "Polish" },
  { value: "portuguese", label: "Portuguese" },
  { value: "russian", label: "Russian" },
  { value: "spanish", label: "Spanish" },
  { value: "swedish", label: "Swedish" },
  { value: "turkish", label: "Turkish" },
  { value: "vietnamese", label: "Vietnamese" },
];

export const AI_TOOLS: ToolSpec[] = [
  {
    slug: "ai-prompt-generator",
    category: "ai",
    title: "AI Prompt Generator",
    short: "Turn a rough idea into a prompt that actually specifies the job",
    keywords: [
      "ai prompt generator",
      "prompt generator",
      "chatgpt prompt generator",
      "write a prompt for ai",
      "free prompt generator",
    ],
    io: "text",
    engine: "ai",
    op: "promptGenerate",
    options: [
      {
        kind: "select",
        id: "target",
        label: "Prompt is for",
        choices: [
          { value: "chat", label: "A chat assistant" },
          { value: "image", label: "An image model" },
          { value: "video", label: "A video model" },
          { value: "code", label: "A coding assistant" },
          { value: "agent", label: "An agent with tools" },
        ],
        default: "chat",
        help: "Image and video prompts are written as description; the rest are written as instruction.",
      },
      {
        kind: "select",
        id: "detail",
        label: "How detailed",
        choices: [
          { value: "compact", label: "Compact — a short paragraph" },
          { value: "standard", label: "Standard — role, task, constraints" },
          { value: "full", label: "Full — with format, examples and checks" },
        ],
        default: "standard",
      },
      {
        kind: "toggle",
        id: "variants",
        label: "Give me three versions",
        default: false,
        help: "Three distinct takes rather than one, so you can pick the framing that fits.",
      },
    ],
    related: ["improve-prompt", "explain-code", "blog-outline-generator", "summarize-text"],
    icon: "Wand2",
  },
  {
    slug: "improve-prompt",
    category: "ai",
    title: "Prompt Improver",
    short: "Paste a prompt that keeps missing and get back one that does not",
    keywords: [
      "improve prompt",
      "prompt optimizer",
      "rewrite my prompt",
      "prompt engineering tool",
      "better chatgpt prompt",
    ],
    io: "text",
    engine: "ai",
    op: "promptImprove",
    options: [
      {
        kind: "textarea",
        id: "problem",
        label: "What goes wrong with it",
        default: "",
        rows: 3,
        placeholder: "It answers in bullet points when I want prose, and it invents statistics.",
      },
      {
        kind: "toggle",
        id: "explain",
        label: "Explain each change",
        default: true,
        help: "Adds a short list of what was altered and why, after the rewritten prompt.",
      },
    ],
    related: ["ai-prompt-generator", "change-tone", "simplify-text"],
    icon: "Sparkles",
  },
  {
    slug: "grammar-checker",
    category: "ai",
    title: "Grammar Checker",
    short: "Fix grammar, spelling and punctuation without rewriting your voice",
    keywords: [
      "grammar checker",
      "free grammar check",
      "spelling and grammar checker",
      "punctuation checker",
      "proofread text online",
    ],
    io: "text",
    engine: "ai",
    op: "grammarCheck",
    options: [
      {
        kind: "select",
        id: "variety",
        label: "Spelling",
        choices: [
          { value: "british", label: "British" },
          { value: "american", label: "American" },
          { value: "indian", label: "Indian" },
          { value: "leave", label: "Leave it alone" },
        ],
        default: "british",
      },
      {
        kind: "select",
        id: "reach",
        label: "How far to go",
        choices: [
          { value: "errors", label: "Errors only" },
          { value: "clarity", label: "Errors and awkward phrasing" },
        ],
        default: "errors",
        help: "“Errors only” will not touch a sentence that is merely clumsy.",
      },
      {
        kind: "toggle",
        id: "listChanges",
        label: "List what changed",
        default: false,
      },
    ],
    related: ["paraphrase-text", "change-tone", "simplify-text", "readability-checker"],
    icon: "SpellCheck",
  },
  {
    slug: "paraphrase-text",
    category: "ai",
    title: "Paraphrasing Tool",
    short: "Say the same thing in different words, at a register you choose",
    keywords: [
      "paraphrasing tool",
      "paraphrase text",
      "reword sentences",
      "rewrite text online",
      "free paraphraser",
    ],
    io: "text",
    engine: "ai",
    op: "paraphrase",
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Style",
        choices: [
          { value: "standard", label: "Standard" },
          { value: "fluent", label: "Fluent — smoother reading" },
          { value: "formal", label: "Formal" },
          { value: "simple", label: "Simple words" },
          { value: "creative", label: "Creative — furthest from the original" },
          { value: "shorten", label: "Shorter" },
          { value: "expand", label: "Longer" },
        ],
        default: "standard",
      },
      {
        kind: "slider",
        id: "strength",
        label: "How much to change",
        min: 1,
        max: 5,
        step: 1,
        default: 3,
        help: "1 swaps a few words. 5 rebuilds the sentences.",
      },
      {
        kind: "toggle",
        id: "keepTerms",
        label: "Keep technical terms as they are",
        default: true,
      },
    ],
    related: ["grammar-checker", "change-tone", "simplify-text", "summarize-text"],
    icon: "Repeat",
  },
  {
    slug: "summarize-text",
    category: "ai",
    title: "Text Summariser",
    short: "Cut a long document down to the part you actually needed",
    keywords: [
      "text summarizer",
      "summarize text",
      "article summariser",
      "tl;dr generator",
      "free summary tool",
    ],
    io: "text",
    engine: "ai",
    op: "summarize",
    options: [
      {
        kind: "select",
        id: "shape",
        label: "Shape",
        choices: [
          { value: "paragraph", label: "A paragraph" },
          { value: "bullets", label: "Bullet points" },
          { value: "oneline", label: "One sentence" },
          { value: "keypoints", label: "Key points with detail" },
        ],
        default: "paragraph",
      },
      {
        kind: "slider",
        id: "length",
        label: "Length",
        min: 1,
        max: 5,
        step: 1,
        default: 3,
        help: "1 is the barest summary. 5 keeps most of the supporting detail.",
      },
      {
        kind: "toggle",
        id: "quotes",
        label: "Include a quoted line or two",
        default: false,
        help: "Pulls exact sentences from the source rather than paraphrasing everything.",
      },
    ],
    related: ["bullet-points", "keyword-extractor", "paraphrase-text", "blog-outline-generator"],
    icon: "AlignLeft",
  },
  {
    slug: "change-tone",
    category: "ai",
    title: "Tone Changer",
    short: "Same message, different register — polite, direct, warm or plain",
    keywords: [
      "tone changer",
      "change tone of text",
      "make text more formal",
      "make text friendly",
      "rewrite tone online",
    ],
    io: "text",
    engine: "ai",
    op: "toneChange",
    options: [
      {
        kind: "select",
        id: "tone",
        label: "Target tone",
        choices: [
          { value: "professional", label: "Professional" },
          { value: "friendly", label: "Friendly" },
          { value: "direct", label: "Direct" },
          { value: "diplomatic", label: "Diplomatic" },
          { value: "confident", label: "Confident" },
          { value: "apologetic", label: "Apologetic" },
          { value: "enthusiastic", label: "Enthusiastic" },
          { value: "neutral", label: "Neutral" },
        ],
        default: "professional",
      },
      {
        kind: "select",
        id: "audience",
        label: "Written for",
        choices: [
          { value: "colleague", label: "A colleague" },
          { value: "manager", label: "A manager" },
          { value: "client", label: "A client" },
          { value: "customer", label: "A customer" },
          { value: "public", label: "The public" },
        ],
        default: "colleague",
      },
      {
        kind: "toggle",
        id: "keepLength",
        label: "Keep it roughly the same length",
        default: true,
      },
    ],
    related: ["write-email", "paraphrase-text", "grammar-checker", "simplify-text"],
    icon: "Waves",
  },
  {
    slug: "simplify-text",
    category: "ai",
    title: "Text Simplifier",
    short: "Rewrite dense writing in plain words at a reading level you set",
    keywords: [
      "simplify text",
      "plain english converter",
      "make text easier to read",
      "explain like im five",
      "reading level rewriter",
    ],
    io: "text",
    engine: "ai",
    op: "simplify",
    options: [
      {
        kind: "select",
        id: "level",
        label: "Reading level",
        choices: [
          { value: "child", label: "A ten-year-old" },
          { value: "teen", label: "A fifteen-year-old" },
          { value: "general", label: "A general adult reader" },
          { value: "nonnative", label: "Someone reading in a second language" },
        ],
        default: "general",
      },
      {
        kind: "toggle",
        id: "keepFacts",
        label: "Keep every number and name",
        default: true,
        help: "Stops the rewrite rounding figures off or dropping a caveat to read more smoothly.",
      },
      {
        kind: "toggle",
        id: "glossary",
        label: "Explain the jargon it removed",
        default: false,
      },
    ],
    related: ["readability-checker", "paraphrase-text", "summarize-text", "grammar-checker"],
    icon: "Feather",
  },
  {
    slug: "expand-text",
    category: "ai",
    title: "Notes to Prose",
    short: "Turn rough bullets into paragraphs that read like someone wrote them",
    keywords: [
      "expand text",
      "bullet points to paragraph",
      "notes to prose",
      "text expander ai",
      "turn notes into writing",
    ],
    io: "text",
    engine: "ai",
    op: "expand",
    options: [
      {
        kind: "select",
        id: "form",
        label: "Write it as",
        choices: [
          { value: "prose", label: "Plain paragraphs" },
          { value: "report", label: "A short report" },
          { value: "email", label: "An email body" },
          { value: "update", label: "A status update" },
        ],
        default: "prose",
      },
      {
        kind: "slider",
        id: "depth",
        label: "How much to add",
        min: 1,
        max: 5,
        step: 1,
        default: 3,
        help: "Higher means more connective writing around your points — never new facts.",
      },
      {
        kind: "toggle",
        id: "noInvention",
        label: "Add nothing I did not say",
        default: true,
      },
    ],
    related: ["bullet-points", "write-email", "change-tone", "summarize-text"],
    icon: "Expand",
  },
  {
    slug: "bullet-points",
    category: "ai",
    title: "Bullet Point Generator",
    short: "Pull a wall of text apart into the points it was actually making",
    keywords: [
      "bullet point generator",
      "text to bullet points",
      "summarize into bullets",
      "make bullet points from text",
      "convert paragraph to list",
    ],
    io: "text",
    engine: "ai",
    op: "bulletPoints",
    options: [
      {
        kind: "select",
        id: "style",
        label: "Bullet style",
        choices: [
          { value: "short", label: "Short — a few words each" },
          { value: "sentence", label: "One full sentence each" },
          { value: "grouped", label: "Grouped under headings" },
          { value: "action", label: "Action items" },
        ],
        default: "short",
      },
      {
        kind: "number",
        id: "count",
        label: "Roughly how many",
        min: 3,
        max: 25,
        step: 1,
        default: 7,
      },
    ],
    related: ["summarize-text", "expand-text", "keyword-extractor", "blog-outline-generator"],
    icon: "List",
  },
  {
    slug: "translate-text",
    category: "ai",
    title: "Translator",
    short: "Translate between twenty-eight languages, formal or informal",
    keywords: [
      "translate text",
      "free translator",
      "english to hindi translation",
      "document translator online",
      "ai translation tool",
    ],
    io: "text",
    engine: "ai",
    op: "translate",
    options: [
      {
        kind: "select",
        id: "into",
        label: "Translate into",
        choices: LANGUAGES,
        default: "hindi",
      },
      {
        kind: "select",
        id: "register",
        label: "Register",
        choices: [
          { value: "match", label: "Match the original" },
          { value: "formal", label: "Formal" },
          { value: "informal", label: "Informal" },
        ],
        default: "match",
        help: "Matters in languages that mark it grammatically — Hindi, French, Japanese and others.",
      },
      {
        kind: "toggle",
        id: "romanise",
        label: "Also write it in the Latin alphabet",
        default: false,
        help: "A transliteration under the translation, for reading aloud without the script.",
      },
    ],
    related: ["simplify-text", "change-tone", "paraphrase-text", "grammar-checker"],
    icon: "Languages",
  },
  {
    slug: "write-email",
    category: "ai",
    title: "Email Writer",
    short: "Say what the email is for and get a draft you can send",
    keywords: [
      "email writer ai",
      "write an email for me",
      "professional email generator",
      "email draft tool",
      "free ai email writer",
    ],
    io: "text",
    engine: "ai",
    op: "emailWrite",
    options: [
      {
        kind: "select",
        id: "kind",
        label: "Kind of email",
        choices: [
          { value: "request", label: "Asking for something" },
          { value: "reply", label: "Replying to one below" },
          { value: "followup", label: "Following up" },
          { value: "apology", label: "Apologising" },
          { value: "decline", label: "Saying no" },
          { value: "intro", label: "Introducing yourself" },
          { value: "update", label: "Giving an update" },
        ],
        default: "request",
      },
      {
        kind: "select",
        id: "length",
        label: "Length",
        choices: [
          { value: "brief", label: "Three lines" },
          { value: "normal", label: "Normal" },
          { value: "detailed", label: "Detailed" },
        ],
        default: "normal",
      },
      {
        kind: "text",
        id: "signoff",
        label: "Sign off as",
        default: "",
        maxLength: 60,
        placeholder: "Your name",
      },
    ],
    related: ["change-tone", "expand-text", "grammar-checker", "paraphrase-text"],
    icon: "Mail",
  },
  {
    slug: "title-generator",
    category: "ai",
    title: "Headline Generator",
    short: "Ten titles for one article, without the clickbait unless you ask",
    keywords: [
      "title generator",
      "headline generator",
      "blog title ideas",
      "youtube title generator",
      "catchy headline maker",
    ],
    io: "text",
    engine: "ai",
    op: "titles",
    options: [
      {
        kind: "select",
        id: "platform",
        label: "For",
        choices: [
          { value: "blog", label: "A blog post" },
          { value: "news", label: "A news story" },
          { value: "youtube", label: "A video" },
          { value: "email", label: "An email subject line" },
          { value: "paper", label: "A report or paper" },
        ],
        default: "blog",
      },
      {
        kind: "select",
        id: "flavour",
        label: "Flavour",
        choices: [
          { value: "plain", label: "Plain and descriptive" },
          { value: "curious", label: "Curiosity, honestly earned" },
          { value: "howto", label: "How-to" },
          { value: "listicle", label: "Numbered list" },
          { value: "mixed", label: "A mix" },
        ],
        default: "mixed",
      },
      {
        kind: "number",
        id: "count",
        label: "How many",
        min: 3,
        max: 20,
        step: 1,
        default: 10,
      },
    ],
    related: ["meta-description-generator", "blog-outline-generator", "social-post-generator", "keyword-extractor"],
    icon: "Heading",
  },
  {
    slug: "meta-description-generator",
    category: "ai",
    title: "Meta Description Generator",
    short: "Search snippets that fit the pixel budget and read like a sentence",
    keywords: [
      "meta description generator",
      "seo description writer",
      "meta tag description",
      "search snippet generator",
      "write meta description",
    ],
    io: "text",
    engine: "ai",
    op: "metaDescription",
    options: [
      {
        kind: "text",
        id: "keyword",
        label: "Term it should rank for",
        default: "",
        maxLength: 80,
        placeholder: "compress pdf online",
      },
      {
        kind: "number",
        id: "count",
        label: "How many options",
        min: 1,
        max: 10,
        step: 1,
        default: 5,
      },
      {
        kind: "toggle",
        id: "cta",
        label: "End with a call to action",
        default: true,
      },
    ],
    related: ["title-generator", "keyword-extractor", "social-post-generator", "summarize-text"],
    icon: "Tags",
  },
  {
    slug: "blog-outline-generator",
    category: "ai",
    title: "Article Outline Generator",
    short: "A working structure for a piece before you write a word of it",
    keywords: [
      "blog outline generator",
      "article outline ai",
      "content outline tool",
      "essay outline generator",
      "blog structure planner",
    ],
    io: "text",
    engine: "ai",
    op: "outline",
    options: [
      {
        kind: "select",
        id: "kind",
        label: "Piece",
        choices: [
          { value: "howto", label: "How-to guide" },
          { value: "listicle", label: "List article" },
          { value: "explainer", label: "Explainer" },
          { value: "comparison", label: "Comparison" },
          { value: "essay", label: "Essay" },
          { value: "casestudy", label: "Case study" },
        ],
        default: "howto",
      },
      {
        kind: "slider",
        id: "depth",
        label: "Depth",
        min: 1,
        max: 4,
        step: 1,
        default: 2,
        help: "1 is headings only. 4 adds sub-points and a note on what each section must prove.",
      },
      {
        kind: "toggle",
        id: "faq",
        label: "Suggest FAQ questions too",
        default: true,
      },
    ],
    related: ["title-generator", "bullet-points", "summarize-text", "meta-description-generator"],
    icon: "ListTree",
  },
  {
    slug: "social-post-generator",
    category: "ai",
    title: "Social Post Writer",
    short: "One idea, written the way each platform actually reads",
    keywords: [
      "social media post generator",
      "linkedin post writer",
      "twitter post generator",
      "instagram caption generator",
      "ai social media writer",
    ],
    io: "text",
    engine: "ai",
    op: "socialPost",
    options: [
      {
        kind: "select",
        id: "platform",
        label: "Platform",
        choices: [
          { value: "linkedin", label: "LinkedIn" },
          { value: "x", label: "X" },
          { value: "instagram", label: "Instagram" },
          { value: "facebook", label: "Facebook" },
          { value: "threads", label: "Threads" },
          { value: "reddit", label: "Reddit" },
        ],
        default: "linkedin",
      },
      {
        kind: "select",
        id: "voice",
        label: "Voice",
        choices: [
          { value: "plain", label: "Plain — no hype" },
          { value: "story", label: "A short story" },
          { value: "teaching", label: "Teaching something" },
          { value: "announcement", label: "Announcement" },
        ],
        default: "plain",
      },
      {
        kind: "toggle",
        id: "hashtags",
        label: "Add hashtags",
        default: false,
      },
    ],
    related: ["title-generator", "change-tone", "meta-description-generator", "summarize-text"],
    icon: "Megaphone",
  },
  {
    slug: "keyword-extractor",
    category: "ai",
    title: "Keyword Extractor",
    short: "The terms a page is really about, ranked and grouped",
    keywords: [
      "keyword extractor",
      "extract keywords from text",
      "seo keyword finder",
      "topic extraction tool",
      "find keywords in article",
    ],
    io: "text",
    engine: "ai",
    op: "keywords",
    options: [
      {
        kind: "select",
        id: "shape",
        label: "Return",
        choices: [
          { value: "ranked", label: "A ranked list" },
          { value: "grouped", label: "Grouped by theme" },
          { value: "csv", label: "Comma-separated" },
        ],
        default: "ranked",
      },
      {
        kind: "number",
        id: "count",
        label: "How many",
        min: 5,
        max: 50,
        step: 1,
        default: 20,
      },
      {
        kind: "toggle",
        id: "phrases",
        label: "Include multi-word phrases",
        default: true,
      },
    ],
    related: ["summarize-text", "meta-description-generator", "title-generator", "sentiment-analysis"],
    icon: "Hash",
  },
  {
    slug: "sentiment-analysis",
    category: "ai",
    title: "Sentiment Analyser",
    short: "Read a pile of feedback and find out what it is telling you",
    keywords: [
      "sentiment analysis tool",
      "analyse feedback sentiment",
      "review sentiment checker",
      "text emotion analysis",
      "free sentiment analyser",
    ],
    io: "text",
    engine: "ai",
    op: "sentiment",
    options: [
      {
        kind: "select",
        id: "granularity",
        label: "Analyse",
        choices: [
          { value: "whole", label: "The text as a whole" },
          { value: "perline", label: "Line by line" },
        ],
        default: "whole",
        help: "Line by line suits a pasted column of reviews or survey answers.",
      },
      {
        kind: "toggle",
        id: "themes",
        label: "Name the recurring themes",
        default: true,
      },
      {
        kind: "toggle",
        id: "quotes",
        label: "Quote an example for each finding",
        default: true,
      },
    ],
    related: ["keyword-extractor", "summarize-text", "text-to-table", "bullet-points"],
    icon: "Gauge",
  },
  {
    slug: "text-to-table",
    category: "ai",
    title: "Text to Table",
    short: "Pull structured rows out of unstructured text, as CSV or JSON",
    keywords: [
      "text to table",
      "extract data from text",
      "unstructured text to csv",
      "text to json converter ai",
      "parse text into columns",
    ],
    io: "text",
    engine: "ai",
    op: "textToTable",
    options: [
      {
        kind: "select",
        id: "format",
        label: "Give me",
        choices: [
          { value: "csv", label: "CSV" },
          { value: "json", label: "JSON" },
          { value: "markdown", label: "A Markdown table" },
        ],
        default: "csv",
      },
      {
        kind: "text",
        id: "columns",
        label: "Columns I want",
        default: "",
        maxLength: 200,
        placeholder: "name, email, city, joined",
        help: "Leave blank and it works out the columns from the text.",
      },
      {
        kind: "toggle",
        id: "blanks",
        label: "Leave a cell empty rather than guessing",
        default: true,
      },
    ],
    related: ["sentiment-analysis", "keyword-extractor", "csv-to-json", "json-formatter"],
    icon: "Table",
  },
  {
    slug: "regex-generator",
    category: "ai",
    title: "Regex Generator",
    short: "Describe the match in English and get the expression, explained",
    keywords: [
      "regex generator",
      "regex from english",
      "build a regular expression",
      "regex maker ai",
      "natural language to regex",
    ],
    io: "text",
    engine: "ai",
    op: "regexGenerate",
    options: [
      {
        kind: "select",
        id: "flavour",
        label: "Flavour",
        choices: [
          { value: "javascript", label: "JavaScript" },
          { value: "python", label: "Python" },
          { value: "pcre", label: "PCRE / PHP" },
          { value: "java", label: "Java" },
          { value: "go", label: "Go (RE2)" },
          { value: "posix", label: "POSIX / grep" },
        ],
        default: "javascript",
        help: "Go's RE2 has no backreferences or lookaround, so the answer changes with this.",
      },
      {
        kind: "toggle",
        id: "explain",
        label: "Explain it piece by piece",
        default: true,
      },
      {
        kind: "toggle",
        id: "examples",
        label: "Show strings it does and does not match",
        default: true,
      },
    ],
    related: ["regex-tester", "sql-generator", "explain-code", "cron-expression-parser"],
    icon: "Regex",
  },
  {
    slug: "sql-generator",
    category: "ai",
    title: "SQL Generator",
    short: "Ask the question in English, paste your schema, get the query",
    keywords: [
      "sql generator",
      "english to sql",
      "text to sql converter",
      "write sql query ai",
      "natural language sql tool",
    ],
    io: "text",
    engine: "ai",
    op: "sqlGenerate",
    options: [
      {
        kind: "select",
        id: "dialect",
        label: "Dialect",
        choices: [
          { value: "postgres", label: "PostgreSQL" },
          { value: "mysql", label: "MySQL" },
          { value: "sqlite", label: "SQLite" },
          { value: "sqlserver", label: "SQL Server" },
          { value: "bigquery", label: "BigQuery" },
          { value: "snowflake", label: "Snowflake" },
        ],
        default: "postgres",
      },
      {
        kind: "textarea",
        id: "schema",
        label: "Your tables",
        default: "",
        rows: 4,
        placeholder: "orders(id, customer_id, total, created_at)\ncustomers(id, name, city)",
        help: "Without this it has to guess your column names, and it will guess wrong.",
      },
      {
        kind: "toggle",
        id: "explain",
        label: "Explain what the query does",
        default: true,
      },
    ],
    related: ["regex-generator", "explain-code", "text-to-table", "json-formatter"],
    icon: "Database",
  },
  {
    slug: "explain-code",
    category: "ai",
    title: "Code Explainer",
    short: "Paste code you did not write and find out what it does",
    keywords: [
      "explain code",
      "code explainer ai",
      "what does this code do",
      "understand code snippet",
      "free code explanation tool",
    ],
    io: "text",
    engine: "ai",
    op: "explainCode",
    options: [
      {
        kind: "select",
        id: "audience",
        label: "Explain it to",
        choices: [
          { value: "beginner", label: "Someone new to the language" },
          { value: "developer", label: "A working developer" },
          { value: "reviewer", label: "A reviewer looking for problems" },
        ],
        default: "developer",
      },
      {
        kind: "toggle",
        id: "lineByLine",
        label: "Go through it line by line",
        default: false,
      },
      {
        kind: "toggle",
        id: "risks",
        label: "Flag bugs and risky patterns",
        default: true,
      },
    ],
    related: ["commit-message-generator", "regex-generator", "sql-generator", "ai-prompt-generator"],
    icon: "Code2",
  },
  {
    slug: "commit-message-generator",
    category: "ai",
    title: "Commit Message Writer",
    short: "Paste a diff, get a message that says what changed and why",
    keywords: [
      "commit message generator",
      "git commit message ai",
      "conventional commit generator",
      "write commit message from diff",
      "commit message helper",
    ],
    io: "text",
    engine: "ai",
    op: "commitMessage",
    options: [
      {
        kind: "select",
        id: "convention",
        label: "Convention",
        choices: [
          { value: "conventional", label: "Conventional Commits" },
          { value: "plain", label: "Plain summary line" },
          { value: "descriptive", label: "Summary plus a body" },
        ],
        default: "conventional",
      },
      {
        kind: "number",
        id: "limit",
        label: "Subject line limit",
        min: 40,
        max: 100,
        step: 1,
        default: 72,
        unit: " characters",
      },
      {
        kind: "toggle",
        id: "why",
        label: "Ask for the reason, not only the change",
        default: true,
      },
    ],
    related: ["explain-code", "regex-generator", "bullet-points", "sql-generator"],
    icon: "GitCommitHorizontal",
  },
  {
    slug: "citation-generator",
    category: "ai",
    title: "Citation Generator",
    short: "Format a reference in APA, MLA, Chicago, Harvard or IEEE",
    keywords: [
      "citation generator",
      "apa citation maker",
      "mla citation generator",
      "harvard referencing tool",
      "free bibliography generator",
    ],
    io: "text",
    engine: "ai",
    op: "citation",
    options: [
      {
        kind: "select",
        id: "style",
        label: "Style",
        choices: [
          { value: "apa", label: "APA 7th" },
          { value: "mla", label: "MLA 9th" },
          { value: "chicago", label: "Chicago 17th" },
          { value: "harvard", label: "Harvard" },
          { value: "ieee", label: "IEEE" },
          { value: "vancouver", label: "Vancouver" },
        ],
        default: "apa",
      },
      {
        kind: "toggle",
        id: "inText",
        label: "Include the in-text citation",
        default: true,
      },
      {
        kind: "toggle",
        id: "flagGaps",
        label: "Tell me what details are missing",
        default: true,
        help: "It will not invent a publisher or a year — it names the gap instead.",
      },
    ],
    related: ["summarize-text", "readability-checker", "grammar-checker", "bullet-points"],
    icon: "Quote",
  },
  {
    slug: "readability-checker",
    category: "ai",
    title: "Readability Checker",
    short: "Six reading scores and the sentences dragging them down — no server",
    keywords: [
      "readability checker",
      "flesch kincaid calculator",
      "reading level test",
      "gunning fog index calculator",
      "readability score tool",
    ],
    io: "text",
    engine: "pure",
    op: "readability",
    options: [
      {
        kind: "select",
        id: "detail",
        label: "Show",
        choices: [
          { value: "scores", label: "Scores and counts" },
          { value: "hard", label: "Scores and the hardest sentences" },
        ],
        default: "hard",
      },
      {
        kind: "number",
        id: "flag",
        label: "Flag sentences longer than",
        min: 15,
        max: 60,
        step: 1,
        default: 25,
        unit: " words",
        showIf: { id: "detail", equals: "hard" },
      },
    ],
    related: ["simplify-text", "grammar-checker", "word-counter", "summarize-text"],
    icon: "BookOpen",
  },
];
