import type { AcceptSpec, OptionSpec, ToolSpec } from "../types";

/**
 * Audio tools.
 *
 * Everything here runs on the browser's own decoder plus arithmetic in
 * `lib/engines/audio` — no FFmpeg build, so the page is usable the moment it
 * loads rather than after a thirty-megabyte download, and the site needs none
 * of the cross-origin isolation that build would demand.
 */

const AUDIO_IN: AcceptSpec = {
  mime: ["audio/*"],
  ext: ["mp3", "wav", "m4a", "aac", "ogg", "oga", "opus", "flac", "webm", "weba"],
  multiple: false,
  maxMB: 200,
};

const AUDIOS_IN: AcceptSpec = { ...AUDIO_IN, multiple: true };

const AUDIO_OUT = { ext: "mp3", mime: "audio/mpeg", cardinality: "per-file" as const };

/**
 * The output format, on every tool.
 *
 * MP3 is the default because it is what people can send to other people. WAV is
 * there because it throws nothing away, which matters when the file is going
 * back into an editor rather than out to a listener.
 */
const formatOptions: OptionSpec[] = [
  {
    kind: "select",
    id: "format",
    label: "Save as",
    choices: [
      { value: "mp3", label: "MP3 — small, plays anywhere" },
      { value: "wav", label: "WAV — uncompressed, about ten times larger" },
    ],
    default: "mp3",
  },
  {
    kind: "select",
    id: "bitrate",
    label: "MP3 quality",
    choices: [
      { value: "320", label: "320 kbps — highest" },
      { value: "192", label: "192 kbps — good for music" },
      { value: "128", label: "128 kbps — smaller" },
      { value: "64", label: "64 kbps — speech only" },
    ],
    default: "192",
    showIf: { id: "format", equals: "mp3" },
  },
];

export const AUDIO_TOOLS: ToolSpec[] = [
  {
    slug: "trim-audio",
    category: "audio",
    title: "Trim Audio",
    short: "Cut a clip out of a recording, by start and end time",
    keywords: ["trim audio", "cut mp3", "audio trimmer online", "crop audio file"],
    io: "file",
    engine: "audio",
    op: "trimAudio",
    accepts: AUDIO_IN,
    output: AUDIO_OUT,
    options: [
      {
        kind: "text",
        id: "start",
        label: "Start at",
        default: "",
        placeholder: "0:00",
        help: "Seconds, or minutes:seconds. Leave empty to start at the beginning.",
      },
      {
        kind: "text",
        id: "end",
        label: "End at",
        default: "",
        placeholder: "end of file",
        help: "Leave empty to run to the end.",
      },
      {
        kind: "toggle",
        id: "fade",
        label: "Soften the cut edges",
        default: true,
        help: "A twenty-millisecond fade at each end. Without it a cut through the middle of a waveform is heard as a click.",
      },
      ...formatOptions,
    ],
    related: ["join-audio", "change-audio-volume", "reverse-audio", "voice-recorder"],
    icon: "Scissors",
  },
  {
    slug: "change-audio-volume",
    category: "audio",
    title: "Change Volume",
    short: "Make a recording louder or quieter, or level it to a target",
    keywords: ["change audio volume", "increase mp3 volume", "normalize audio online", "make audio louder"],
    io: "file",
    engine: "audio",
    op: "changeAudioVolume",
    accepts: AUDIOS_IN,
    output: AUDIO_OUT,
    options: [
      {
        kind: "select",
        id: "mode",
        label: "How",
        choices: [
          { value: "gain", label: "By an amount — you choose" },
          { value: "normalise", label: "Match a target level — worked out for you" },
        ],
        default: "gain",
      },
      {
        kind: "slider",
        id: "gain",
        label: "Change by",
        min: -30,
        max: 30,
        step: 1,
        default: 6,
        unit: " dB",
        help: "+6 dB is roughly twice as loud, −6 dB roughly half.",
        showIf: { id: "mode", equals: "gain" },
      },
      {
        kind: "slider",
        id: "targetPeak",
        label: "Loudest point should reach",
        min: -12,
        max: 0,
        step: 1,
        default: -1,
        unit: " dB",
        help: "Below full scale. −1 dB is the usual choice: as loud as possible with a little room left.",
        showIf: { id: "mode", equals: "normalise" },
      },
      ...formatOptions,
    ],
    related: ["audio-equalizer", "trim-audio", "voice-recorder", "join-audio"],
    icon: "Volume2",
  },
  {
    slug: "change-audio-speed",
    category: "audio",
    title: "Change Speed",
    short: "Play a recording faster or slower, with the voice left alone",
    keywords: ["change audio speed", "speed up mp3", "slow down audio online", "audio speed changer"],
    io: "file",
    engine: "audio",
    op: "changeAudioSpeed",
    accepts: AUDIO_IN,
    output: AUDIO_OUT,
    options: [
      {
        kind: "slider",
        id: "speed",
        label: "Speed",
        min: 0.25,
        max: 4,
        step: 0.05,
        default: 1.5,
        unit: "×",
      },
      {
        kind: "toggle",
        id: "keepPitch",
        label: "Keep the original pitch",
        default: true,
        help: "On, a sped-up voice still sounds like the same person. Off, it rises like a tape played fast.",
      },
      ...formatOptions,
    ],
    related: ["change-audio-pitch", "trim-audio", "audio-equalizer", "reverse-audio"],
    icon: "Gauge",
  },
  {
    slug: "change-audio-pitch",
    category: "audio",
    title: "Change Pitch",
    short: "Move a recording up or down in semitones, same length",
    keywords: ["change audio pitch", "pitch shifter online", "transpose song", "change key of mp3"],
    io: "file",
    engine: "audio",
    op: "changeAudioPitch",
    accepts: AUDIO_IN,
    output: AUDIO_OUT,
    options: [
      {
        kind: "slider",
        id: "semitones",
        label: "Shift by",
        min: -12,
        max: 12,
        step: 1,
        default: 2,
        unit: " semitones",
        help: "Twelve semitones is an octave. Two or three is a comfortable change of key.",
      },
      ...formatOptions,
    ],
    related: ["change-audio-speed", "audio-equalizer", "trim-audio", "reverse-audio"],
    icon: "Music",
  },
  {
    slug: "audio-equalizer",
    category: "audio",
    title: "Equalizer",
    short: "Adjust bass, middle and treble, or pick a ready-made curve",
    keywords: ["audio equalizer online", "bass booster", "eq mp3", "change audio tone"],
    io: "file",
    engine: "audio",
    op: "equalizeAudio",
    accepts: AUDIO_IN,
    output: AUDIO_OUT,
    options: [
      {
        kind: "select",
        id: "preset",
        label: "Curve",
        choices: [
          { value: "custom", label: "Set the three bands myself" },
          { value: "voice", label: "Speech — lift the words out" },
          { value: "bass", label: "Bass boost" },
          { value: "bright", label: "Brighten" },
          { value: "warm", label: "Warm" },
          { value: "phone", label: "Telephone" },
          { value: "flat", label: "Flat — leave it alone" },
        ],
        default: "voice",
      },
      {
        kind: "slider",
        id: "bass",
        label: "Bass",
        min: -15,
        max: 15,
        step: 1,
        default: 0,
        unit: " dB",
        help: "A shelf below 200 Hz.",
        showIf: { id: "preset", equals: "custom" },
      },
      {
        kind: "slider",
        id: "mid",
        label: "Middle",
        min: -15,
        max: 15,
        step: 1,
        default: 0,
        unit: " dB",
        help: "Around 1 kHz, where speech lives.",
        showIf: { id: "preset", equals: "custom" },
      },
      {
        kind: "slider",
        id: "treble",
        label: "Treble",
        min: -15,
        max: 15,
        step: 1,
        default: 0,
        unit: " dB",
        help: "A shelf above 4 kHz.",
        showIf: { id: "preset", equals: "custom" },
      },
      ...formatOptions,
    ],
    related: ["change-audio-volume", "voice-recorder", "change-audio-pitch", "trim-audio"],
    icon: "SlidersHorizontal",
  },
  {
    slug: "reverse-audio",
    category: "audio",
    title: "Reverse Audio",
    short: "Play a recording backwards",
    keywords: ["reverse audio", "play mp3 backwards", "reverse sound online", "backwards audio maker"],
    io: "file",
    engine: "audio",
    op: "reverseAudio",
    accepts: AUDIO_IN,
    output: AUDIO_OUT,
    options: formatOptions,
    related: ["change-audio-speed", "trim-audio", "change-audio-pitch", "join-audio"],
    icon: "Repeat",
  },
  {
    slug: "join-audio",
    category: "audio",
    title: "Audio Joiner",
    short: "Put several recordings together into one, in the order you choose",
    keywords: ["join audio", "merge mp3", "combine audio files", "audio joiner online free"],
    io: "file",
    engine: "audio",
    op: "joinAudio",
    accepts: AUDIOS_IN,
    output: { ...AUDIO_OUT, cardinality: "single" as const },
    options: [
      {
        kind: "slider",
        id: "crossfade",
        label: "Overlap between tracks",
        min: 0,
        max: 5,
        step: 0.5,
        default: 0,
        unit: " s",
        help: "Zero puts them end to end. Anything above fades one into the next.",
      },
      { kind: "text", id: "filename", label: "Output name", default: "joined", placeholder: "joined" },
      ...formatOptions,
    ],
    related: ["trim-audio", "change-audio-volume", "voice-recorder", "reverse-audio"],
    icon: "ListMusic",
  },
  {
    slug: "voice-recorder",
    category: "audio",
    title: "Voice Recorder",
    short: "Record from your microphone and save it as MP3 or WAV",
    keywords: ["voice recorder online", "record audio in browser", "online mic recorder", "record mp3 online"],
    io: "file",
    engine: "audio",
    op: "exportRecording",
    accepts: AUDIO_IN,
    output: AUDIO_OUT,
    record: "mic",
    options: [
      {
        kind: "toggle",
        id: "normalise",
        label: "Even out the level",
        default: true,
        help: "Brings a quiet recording up to a normal listening level. A laptop microphone at arm's length usually needs it.",
      },
      ...formatOptions,
    ],
    related: ["trim-audio", "audio-equalizer", "change-audio-volume", "join-audio"],
    icon: "Mic",
  },
];
