import { QUANTITIES, unitChoices } from "@/lib/units";

import type { OptionSpec, ToolSpec } from "../types";

/**
 * Calculators & generators. Pure arithmetic — no engine warm-up, no network.
 */
export const CALC_TOOLS: ToolSpec[] = [
  {
    slug: "unit-converter",
    category: "calc",
    title: "Unit Converter",
    short: "Length, mass, area, volume, speed, temperature and data",
    keywords: ["unit converter", "measurement converter", "metric to imperial", "convert units online"],
    io: "form",
    engine: "pure",
    op: "unitConvert",
    options: [
      {
        kind: "select",
        id: "quantity",
        label: "Measuring",
        choices: QUANTITIES.map((q) => ({ value: q.id, label: q.label })),
        default: "length",
      },
      { kind: "number", id: "value", label: "Value", default: 1, step: 0.0001 },
      /*
        One pair of unit pickers per quantity, shown only for the quantity it
        belongs to. These were free text defaulting to "m" and "ft", so picking
        Mass — or anything but Length — produced an error until you also guessed
        a valid unit for it. The choices come from the same table the converter
        uses, so the picker can never offer a unit the converter would reject.
      */
      ...QUANTITIES.flatMap((q): OptionSpec[] => [
        {
          kind: "select",
          id: `from_${q.id}`,
          label: "From",
          choices: unitChoices(q.id),
          default: q.from,
          showIf: { id: "quantity", equals: q.id },
        },
        {
          kind: "select",
          id: `to_${q.id}`,
          label: "To",
          choices: unitChoices(q.id),
          default: q.to,
          showIf: { id: "quantity", equals: q.id },
        },
      ]),
      { kind: "number", id: "precision", label: "Decimal places", default: 6, min: 0, max: 12, step: 1 },
    ],
    related: ["base-converter", "aspect-ratio-calculator", "percentage-calculator"],
    icon: "Ruler",
  },
  {
    slug: "percentage-calculator",
    category: "calc",
    title: "Percentage Calculator",
    short: "Percent of, percent change, and what percent one number is",
    keywords: ["percentage calculator", "percent change calculator", "percent of a number", "increase decrease percent"],
    io: "form",
    engine: "pure",
    op: "percentage",
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Work out",
        choices: [
          { value: "of", label: "X percent of Y" },
          { value: "isWhat", label: "X is what percent of Y" },
          { value: "change", label: "Percent change from X to Y" },
          { value: "addSub", label: "X increased or decreased by Y percent" },
        ],
        default: "of",
      },
      { kind: "number", id: "a", label: "X", default: 15, step: 0.01 },
      { kind: "number", id: "b", label: "Y", default: 200, step: 0.01 },
      { kind: "number", id: "precision", label: "Decimal places", default: 2, min: 0, max: 10, step: 1 },
    ],
    related: ["discount-calculator", "gst-calculator", "tip-calculator"],
    icon: "Percent",
  },
  {
    slug: "loan-emi-calculator",
    category: "calc",
    title: "Loan EMI Calculator",
    short: "Monthly instalment, total interest and a full amortisation table",
    keywords: ["emi calculator", "loan calculator", "home loan emi", "car loan emi calculator"],
    io: "form",
    engine: "pure",
    op: "loanEmi",
    options: [
      { kind: "number", id: "principal", label: "Loan amount", default: 2500000, min: 1, step: 1000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 8.5, min: 0, max: 60, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Tenure", default: 20, min: 0.25, max: 40, step: 0.25, unit: " years" },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year schedule", default: true },
    ],
    related: ["compound-interest-calculator", "sip-calculator", "percentage-calculator"],
    icon: "Landmark",
  },
  {
    slug: "sip-calculator",
    category: "calc",
    title: "SIP Calculator",
    short: "What a monthly investment grows to at a given return",
    keywords: ["sip calculator", "mutual fund sip calculator", "monthly investment calculator", "sip returns"],
    io: "form",
    engine: "pure",
    op: "sip",
    options: [
      { kind: "number", id: "monthly", label: "Monthly investment", default: 10000, min: 1, step: 500 },
      { kind: "number", id: "rate", label: "Expected return", default: 12, min: 0, max: 40, step: 0.5, unit: "% a year" },
      { kind: "number", id: "years", label: "Duration", default: 10, min: 1, max: 50, step: 1, unit: " years" },
      { kind: "number", id: "stepUp", label: "Yearly step-up", default: 0, min: 0, max: 50, step: 1, unit: "%" },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year table", default: true },
    ],
    related: ["compound-interest-calculator", "loan-emi-calculator"],
    icon: "TrendingUp",
  },
  {
    slug: "compound-interest-calculator",
    category: "calc",
    title: "Compound Interest Calculator",
    short: "Growth on a lump sum, compounded as often as you like",
    keywords: ["compound interest calculator", "interest calculator", "future value calculator"],
    io: "form",
    engine: "pure",
    op: "compoundInterest",
    options: [
      { kind: "number", id: "principal", label: "Starting amount", default: 100000, min: 0, step: 1000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 8, min: 0, max: 60, step: 0.1, unit: "% a year" },
      { kind: "number", id: "years", label: "Duration", default: 10, min: 0.25, max: 60, step: 0.25, unit: " years" },
      {
        kind: "select",
        id: "frequency",
        label: "Compounded",
        choices: [
          { value: "1", label: "Yearly" },
          { value: "2", label: "Half-yearly" },
          { value: "4", label: "Quarterly" },
          { value: "12", label: "Monthly" },
          { value: "365", label: "Daily" },
        ],
        default: "4",
      },
      { kind: "number", id: "contribution", label: "Added each month", default: 0, min: 0, step: 500 },
    ],
    related: ["sip-calculator", "loan-emi-calculator", "percentage-calculator"],
    icon: "ChartLine",
  },
  {
    slug: "gst-calculator",
    category: "calc",
    title: "GST Calculator",
    short: "Add or strip GST and split it into CGST and SGST",
    keywords: ["gst calculator", "gst inclusive calculator", "reverse gst", "cgst sgst calculator"],
    io: "form",
    engine: "pure",
    op: "gst",
    options: [
      { kind: "number", id: "amount", label: "Amount", default: 1000, min: 0, step: 1 },
      {
        kind: "select",
        id: "rate",
        label: "GST rate",
        choices: [
          { value: "0", label: "0%" },
          { value: "0.25", label: "0.25%" },
          { value: "3", label: "3%" },
          { value: "5", label: "5%" },
          { value: "12", label: "12%" },
          { value: "18", label: "18%" },
          { value: "28", label: "28%" },
        ],
        default: "18",
      },
      {
        kind: "select",
        id: "mode",
        label: "The amount above is",
        choices: [
          { value: "exclusive", label: "Before GST — add it on" },
          { value: "inclusive", label: "After GST — work backwards" },
        ],
        default: "exclusive",
      },
      { kind: "toggle", id: "interstate", label: "Inter-state supply — IGST instead of CGST + SGST", default: false },
    ],
    related: ["percentage-calculator", "discount-calculator"],
    icon: "ReceiptIndianRupee",
  },
  {
    slug: "discount-calculator",
    category: "calc",
    title: "Discount Calculator",
    short: "Final price, money saved, and stacked discounts done right",
    keywords: ["discount calculator", "percent off calculator", "sale price calculator", "how much do i save"],
    io: "form",
    engine: "pure",
    op: "discount",
    options: [
      { kind: "number", id: "price", label: "Original price", default: 2499, min: 0, step: 1 },
      { kind: "number", id: "discount", label: "Discount", default: 30, min: 0, max: 100, step: 0.5, unit: "%" },
      { kind: "number", id: "second", label: "Extra discount on the reduced price", default: 0, min: 0, max: 100, step: 0.5, unit: "%" },
      { kind: "number", id: "tax", label: "Tax added afterwards", default: 0, min: 0, max: 100, step: 0.5, unit: "%" },
    ],
    related: ["percentage-calculator", "gst-calculator", "tip-calculator"],
    icon: "Tag",
  },
  {
    slug: "tip-calculator",
    category: "calc",
    title: "Tip Calculator",
    short: "Tip, total and the per-person split",
    keywords: ["tip calculator", "bill split calculator", "gratuity calculator", "split the bill"],
    io: "form",
    engine: "pure",
    op: "tip",
    options: [
      { kind: "number", id: "bill", label: "Bill amount", default: 1200, min: 0, step: 1 },
      { kind: "slider", id: "percent", label: "Tip", min: 0, max: 40, step: 1, default: 10, unit: "%" },
      { kind: "number", id: "people", label: "Split between", default: 2, min: 1, max: 100, step: 1, unit: " people" },
      { kind: "toggle", id: "roundUp", label: "Round each share up to a whole unit", default: false },
    ],
    related: ["percentage-calculator", "discount-calculator"],
    icon: "HandCoins",
  },
  {
    slug: "bmi-calculator",
    category: "calc",
    title: "BMI Calculator",
    short: "Body mass index in metric or imperial, with the healthy range",
    keywords: ["bmi calculator", "body mass index", "bmi chart", "healthy weight calculator"],
    io: "form",
    engine: "pure",
    op: "bmi",
    options: [
      {
        kind: "select",
        id: "system",
        label: "Units",
        choices: [
          { value: "metric", label: "Metric — cm and kg" },
          { value: "imperial", label: "Imperial — feet, inches and pounds" },
        ],
        default: "metric",
      },
      /*
        A field per system rather than one pair reused. Sharing them meant the
        units changed but the numbers and the labels did not, so switching to
        imperial silently read 170 cm as 170 inches and returned a BMI of 1.7.
        Each field now carries its own unit in the label and its own sensible
        default, and the pair for the other system is not on screen at all.
      */
      { kind: "number", id: "heightCm", label: "Height (cm)", default: 170, min: 1, step: 0.5, showIf: { id: "system", equals: "metric" } },
      { kind: "number", id: "weightKg", label: "Weight (kg)", default: 70, min: 1, step: 0.1, showIf: { id: "system", equals: "metric" } },
      { kind: "number", id: "heightFt", label: "Height (feet)", default: 5, min: 0, max: 8, step: 1, showIf: { id: "system", equals: "imperial" } },
      { kind: "number", id: "heightIn", label: "and inches", default: 7, min: 0, max: 11, step: 0.5, showIf: { id: "system", equals: "imperial" } },
      { kind: "number", id: "weightLb", label: "Weight (pounds)", default: 154, min: 1, step: 0.5, showIf: { id: "system", equals: "imperial" } },
    ],
    related: ["unit-converter", "age-calculator"],
    icon: "Activity",
  },
  {
    slug: "age-calculator",
    category: "calc",
    title: "Age Calculator",
    short: "Exact age in years, months and days — plus the next birthday",
    keywords: ["age calculator", "how old am i", "date of birth calculator", "age in days"],
    io: "form",
    engine: "pure",
    op: "age",
    options: [
      { kind: "text", id: "birth", label: "Date of birth", default: "", placeholder: "YYYY-MM-DD" },
      { kind: "text", id: "asOf", label: "Age on", default: "", placeholder: "Leave blank for today" },
    ],
    related: ["date-difference-calculator", "unix-timestamp-converter"],
    icon: "Cake",
  },
  {
    slug: "date-difference-calculator",
    category: "calc",
    title: "Date Difference Calculator",
    short: "Days between two dates, with or without weekends",
    keywords: ["date difference calculator", "days between dates", "business days calculator", "date duration"],
    io: "form",
    engine: "pure",
    op: "dateDiff",
    options: [
      { kind: "text", id: "start", label: "From", default: "", placeholder: "YYYY-MM-DD" },
      { kind: "text", id: "end", label: "To", default: "", placeholder: "YYYY-MM-DD" },
      { kind: "toggle", id: "inclusive", label: "Count both end dates", default: false },
      { kind: "toggle", id: "businessOnly", label: "Working days only — skip Saturdays and Sundays", default: false },
    ],
    related: ["age-calculator", "unix-timestamp-converter", "cron-expression-parser"],
    icon: "CalendarDays",
  },
  {
    slug: "aspect-ratio-calculator",
    category: "calc",
    title: "Aspect Ratio Calculator",
    short: "Scale width and height while the ratio holds",
    keywords: ["aspect ratio calculator", "resize ratio calculator", "16:9 calculator", "image ratio tool"],
    io: "form",
    engine: "pure",
    op: "aspectRatio",
    options: [
      { kind: "number", id: "width", label: "Original width", default: 1920, min: 1, step: 1, unit: "px" },
      { kind: "number", id: "height", label: "Original height", default: 1080, min: 1, step: 1, unit: "px" },
      {
        kind: "select",
        id: "lock",
        label: "Solve for",
        choices: [
          { value: "height", label: "Height, from a new width" },
          { value: "width", label: "Width, from a new height" },
        ],
        default: "height",
      },
      { kind: "number", id: "target", label: "New value", default: 1280, min: 1, step: 1, unit: "px" },
    ],
    related: ["unit-converter", "percentage-calculator"],
    icon: "Proportions",
  },
  {
    slug: "base-converter",
    category: "calc",
    title: "Number Base Converter",
    short: "Binary, octal, decimal, hex — and any base from 2 to 36",
    keywords: ["base converter", "binary to decimal", "decimal to hex", "hex to binary converter"],
    io: "text",
    engine: "pure",
    op: "baseConvert",
    options: [
      { kind: "number", id: "from", label: "Input base", default: 10, min: 2, max: 36, step: 1 },
      { kind: "toggle", id: "common", label: "Show binary, octal, decimal and hex", default: true },
      { kind: "number", id: "to", label: "Also convert to base", default: 2, min: 2, max: 36, step: 1 },
      { kind: "toggle", id: "group", label: "Group digits for readability", default: true },
    ],
    related: ["unit-converter", "roman-numeral-converter", "hash-generator"],
    icon: "Binary",
  },
  {
    slug: "roman-numeral-converter",
    category: "calc",
    title: "Roman Numeral Converter",
    short: "Numbers to Roman numerals and back again",
    keywords: ["roman numeral converter", "number to roman numerals", "roman numerals translator"],
    io: "text",
    engine: "pure",
    op: "romanNumeral",
    options: [
      {
        kind: "select",
        id: "direction",
        label: "Convert",
        choices: [
          { value: "auto", label: "Detect automatically" },
          { value: "toRoman", label: "Number → Roman" },
          { value: "toNumber", label: "Roman → number" },
        ],
        default: "auto",
      },
    ],
    related: ["base-converter", "number-to-words"],
    icon: "Scroll",
  },
  {
    slug: "number-to-words",
    category: "calc",
    title: "Number to Words",
    short: "Write an amount out in words, Indian or international",
    keywords: ["number to words", "amount in words", "rupees in words", "spell out numbers"],
    io: "text",
    engine: "pure",
    op: "numberToWords",
    options: [
      {
        kind: "select",
        id: "system",
        label: "Numbering system",
        choices: [
          { value: "indian", label: "Indian — lakh and crore" },
          { value: "international", label: "International — thousand, million, billion" },
        ],
        default: "indian",
      },
      { kind: "toggle", id: "currency", label: "Write as a currency amount", default: false },
      { kind: "text", id: "unit", label: "Currency name", default: "Rupees", showIf: { id: "currency", equals: true } },
      { kind: "text", id: "subunit", label: "Minor unit name", default: "Paise", showIf: { id: "currency", equals: true } },
      { kind: "toggle", id: "capitalise", label: "Capitalise Each Word", default: false },
    ],
    related: ["roman-numeral-converter", "gst-calculator", "base-converter"],
    icon: "SpellCheck",
  },
];
