import { QUANTITIES, unitChoices } from "@/lib/units";

import type { OptionSpec, ToolSpec } from "../types";

/**
 * Calculators & generators. Pure arithmetic — no engine warm-up, no network.
 */
export const CALC_TOOLS: ToolSpec[] = [
  {
    slug: "unit-converter",
    category: "calc",
    title: "Unit Converter",
    short: "Length, mass, area, volume, speed, temperature and data",
    keywords: ["unit converter", "measurement converter", "metric to imperial", "convert units online"],
    io: "form",
    engine: "pure",
    op: "unitConvert",
    options: [
      {
        kind: "select",
        id: "quantity",
        label: "Measuring",
        choices: QUANTITIES.map((q) => ({ value: q.id, label: q.label })),
        default: "length",
      },
      { kind: "number", id: "value", label: "Value", default: 1, step: 0.0001 },
      /*
        One pair of unit pickers per quantity, shown only for the quantity it
        belongs to. These were free text defaulting to "m" and "ft", so picking
        Mass — or anything but Length — produced an error until you also guessed
        a valid unit for it. The choices come from the same table the converter
        uses, so the picker can never offer a unit the converter would reject.
      */
      ...QUANTITIES.flatMap((q): OptionSpec[] => [
        {
          kind: "select",
          id: `from_${q.id}`,
          label: "From",
          choices: unitChoices(q.id),
          default: q.from,
          showIf: { id: "quantity", equals: q.id },
        },
        {
          kind: "select",
          id: `to_${q.id}`,
          label: "To",
          choices: unitChoices(q.id),
          default: q.to,
          showIf: { id: "quantity", equals: q.id },
        },
      ]),
      { kind: "number", id: "precision", label: "Decimal places", default: 6, min: 0, max: 12, step: 1 },
    ],
    related: ["base-converter", "aspect-ratio-calculator", "percentage-calculator"],
    icon: "Ruler",
  },
  {
    slug: "percentage-calculator",
    category: "calc",
    title: "Percentage Calculator",
    short: "Percent of, percent change, and what percent one number is",
    keywords: ["percentage calculator", "percent change calculator", "percent of a number", "increase decrease percent"],
    io: "form",
    engine: "pure",
    op: "percentage",
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Work out",
        choices: [
          { value: "of", label: "X percent of Y" },
          { value: "isWhat", label: "X is what percent of Y" },
          { value: "change", label: "Percent change from X to Y" },
          { value: "addSub", label: "X increased or decreased by Y percent" },
        ],
        default: "of",
      },
      { kind: "number", id: "a", label: "X", default: 15, step: 0.01 },
      { kind: "number", id: "b", label: "Y", default: 200, step: 0.01 },
      { kind: "number", id: "precision", label: "Decimal places", default: 2, min: 0, max: 10, step: 1 },
    ],
    related: ["discount-calculator", "gst-calculator", "tip-calculator"],
    icon: "Percent",
  },
  {
    slug: "discount-calculator",
    category: "calc",
    title: "Discount Calculator",
    short: "Final price, money saved, and stacked discounts done right",
    keywords: ["discount calculator", "percent off calculator", "sale price calculator", "how much do i save"],
    io: "form",
    engine: "pure",
    op: "discount",
    options: [
      { kind: "number", id: "price", label: "Original price", default: 2499, min: 0, step: 1 },
      { kind: "number", id: "discount", label: "Discount", default: 30, min: 0, max: 100, step: 0.5, unit: "%" },
      { kind: "number", id: "second", label: "Extra discount on the reduced price", default: 0, min: 0, max: 100, step: 0.5, unit: "%" },
      { kind: "number", id: "tax", label: "Tax added afterwards", default: 0, min: 0, max: 100, step: 0.5, unit: "%" },
    ],
    related: ["percentage-calculator", "gst-calculator", "tip-calculator"],
    icon: "Tag",
  },
  {
    slug: "tip-calculator",
    category: "calc",
    title: "Tip Calculator",
    short: "Tip, total and the per-person split",
    keywords: ["tip calculator", "bill split calculator", "gratuity calculator", "split the bill"],
    io: "form",
    engine: "pure",
    op: "tip",
    options: [
      { kind: "number", id: "bill", label: "Bill amount", default: 1200, min: 0, step: 1 },
      { kind: "slider", id: "percent", label: "Tip", min: 0, max: 40, step: 1, default: 10, unit: "%" },
      { kind: "number", id: "people", label: "Split between", default: 2, min: 1, max: 100, step: 1, unit: " people" },
      { kind: "toggle", id: "roundUp", label: "Round each share up to a whole unit", default: false },
    ],
    related: ["percentage-calculator", "discount-calculator"],
    icon: "HandCoins",
  },
  {
    slug: "bmi-calculator",
    category: "calc",
    title: "BMI Calculator",
    short: "Body mass index in whatever units you think in, with the healthy range",
    keywords: ["bmi calculator", "body mass index", "bmi chart", "healthy weight calculator"],
    io: "form",
    engine: "pure",
    op: "bmi",
    options: [
      /*
        No system switch. Height and weight each carry their own unit, so
        feet-and-inches with kilograms — the usual combination in India — is
        two ordinary answers rather than a contradiction to resolve first.
      */
      {
        kind: "measure",
        id: "height",
        label: "Height",
        quantity: "length",
        units: ["cm", "ft", "m", "in"],
        default: 170,
        min: 0,
        step: 0.5,
        compound: { whenUnit: "ft", unit: "in", label: "Inches", default: 0 },
      },
      {
        kind: "measure",
        id: "weight",
        label: "Weight",
        quantity: "mass",
        units: ["kg", "lb", "st"],
        default: 70,
        min: 0,
        step: 0.1,
      },
    ],
    related: ["unit-converter", "age-calculator"],
    icon: "Activity",
  },
  {
    slug: "age-calculator",
    category: "calc",
    title: "Age Calculator",
    short: "Exact age in years, months and days — plus the next birthday",
    keywords: ["age calculator", "how old am i", "date of birth calculator", "age in days"],
    io: "form",
    engine: "pure",
    op: "age",
    options: [
      { kind: "text", id: "birth", label: "Date of birth", default: "", placeholder: "YYYY-MM-DD" },
      { kind: "text", id: "asOf", label: "Age on", default: "", placeholder: "Leave blank for today" },
    ],
    related: ["date-difference-calculator", "unix-timestamp-converter"],
    icon: "Cake",
  },
  {
    slug: "date-difference-calculator",
    category: "calc",
    title: "Date Difference Calculator",
    short: "Days between two dates, with or without weekends",
    keywords: ["date difference calculator", "days between dates", "business days calculator", "date duration"],
    io: "form",
    engine: "pure",
    op: "dateDiff",
    options: [
      { kind: "text", id: "start", label: "From", default: "", placeholder: "YYYY-MM-DD" },
      { kind: "text", id: "end", label: "To", default: "", placeholder: "YYYY-MM-DD" },
      { kind: "toggle", id: "inclusive", label: "Count both end dates", default: false },
      { kind: "toggle", id: "businessOnly", label: "Working days only — skip Saturdays and Sundays", default: false },
    ],
    related: ["age-calculator", "unix-timestamp-converter", "cron-expression-parser"],
    icon: "CalendarDays",
  },
  {
    slug: "aspect-ratio-calculator",
    category: "calc",
    title: "Aspect Ratio Calculator",
    short: "Scale width and height while the ratio holds",
    keywords: ["aspect ratio calculator", "resize ratio calculator", "16:9 calculator", "image ratio tool"],
    io: "form",
    engine: "pure",
    op: "aspectRatio",
    options: [
      { kind: "number", id: "width", label: "Original width", default: 1920, min: 1, step: 1, unit: "px" },
      { kind: "number", id: "height", label: "Original height", default: 1080, min: 1, step: 1, unit: "px" },
      {
        kind: "select",
        id: "lock",
        label: "Solve for",
        choices: [
          { value: "height", label: "Height, from a new width" },
          { value: "width", label: "Width, from a new height" },
        ],
        default: "height",
      },
      { kind: "number", id: "target", label: "New value", default: 1280, min: 1, step: 1, unit: "px" },
    ],
    related: ["unit-converter", "percentage-calculator"],
    icon: "Proportions",
  },
  {
    slug: "base-converter",
    category: "calc",
    title: "Number Base Converter",
    short: "Binary, octal, decimal, hex — and any base from 2 to 36",
    keywords: ["base converter", "binary to decimal", "decimal to hex", "hex to binary converter"],
    io: "text",
    engine: "pure",
    op: "baseConvert",
    options: [
      { kind: "number", id: "from", label: "Input base", default: 10, min: 2, max: 36, step: 1 },
      { kind: "toggle", id: "common", label: "Show binary, octal, decimal and hex", default: true },
      { kind: "number", id: "to", label: "Also convert to base", default: 2, min: 2, max: 36, step: 1 },
      { kind: "toggle", id: "group", label: "Group digits for readability", default: true },
    ],
    related: ["unit-converter", "roman-numeral-converter", "hash-generator"],
    icon: "Binary",
  },
  {
    slug: "roman-numeral-converter",
    category: "calc",
    title: "Roman Numeral Converter",
    short: "Numbers to Roman numerals and back again",
    keywords: ["roman numeral converter", "number to roman numerals", "roman numerals translator"],
    io: "text",
    engine: "pure",
    op: "romanNumeral",
    options: [
      {
        kind: "select",
        id: "direction",
        label: "Convert",
        choices: [
          { value: "auto", label: "Detect automatically" },
          { value: "toRoman", label: "Number → Roman" },
          { value: "toNumber", label: "Roman → number" },
        ],
        default: "auto",
      },
    ],
    related: ["base-converter", "number-to-words"],
    icon: "Scroll",
  },
  {
    slug: "number-to-words",
    category: "calc",
    title: "Number to Words",
    short: "Write an amount out in words, Indian or international",
    keywords: ["number to words", "amount in words", "rupees in words", "spell out numbers"],
    io: "text",
    engine: "pure",
    op: "numberToWords",
    options: [
      {
        kind: "select",
        id: "system",
        label: "Numbering system",
        choices: [
          { value: "indian", label: "Indian — lakh and crore" },
          { value: "international", label: "International — thousand, million, billion" },
        ],
        default: "indian",
      },
      { kind: "toggle", id: "currency", label: "Write as a currency amount", default: false },
      { kind: "text", id: "unit", label: "Currency name", default: "Rupees", showIf: { id: "currency", equals: true } },
      { kind: "text", id: "subunit", label: "Minor unit name", default: "Paise", showIf: { id: "currency", equals: true } },
      { kind: "toggle", id: "capitalise", label: "Capitalise Each Word", default: false },
    ],
    related: ["roman-numeral-converter", "gst-calculator", "base-converter"],
    icon: "SpellCheck",
  },
];
