import type { ToolSpec } from "../types";

/**
 * Developer tools. All `pure` engine — no WASM, no worker warm-up, instant results.
 */
export const DEV_TOOLS: ToolSpec[] = [
  {
    slug: "base64-encode",
    category: "dev",
    title: "Base64 Encode",
    short: "Turn text into Base64, with optional URL-safe output",
    keywords: ["base64 encode", "text to base64", "base64 converter", "encode base64 online"],
    io: "text",
    engine: "pure",
    op: "base64Encode",
    options: [
      {
        kind: "toggle",
        id: "urlSafe",
        label: "URL-safe alphabet",
        default: false,
        help: "Uses - and _ instead of + and / so the result is safe in a URL or filename.",
      },
      {
        kind: "toggle",
        id: "padding",
        label: "Keep = padding",
        default: true,
      },
      {
        kind: "toggle",
        id: "wrap",
        label: "Wrap at 76 characters",
        default: false,
        help: "MIME-style line wrapping, for email headers and PEM-like output.",
      },
    ],
    related: ["base64-decode", "url-encode", "jwt-decoder", "hash-generator"],
    icon: "Binary",
  },
  {
    slug: "base64-decode",
    category: "dev",
    title: "Base64 Decode",
    short: "Decode Base64 back to readable text",
    keywords: ["base64 decode", "base64 to text", "decode base64 online", "base64 decoder"],
    io: "text",
    engine: "pure",
    op: "base64Decode",
    options: [
      {
        kind: "toggle",
        id: "urlSafe",
        label: "Accept URL-safe input",
        default: true,
        help: "Treats - and _ as + and /. Harmless to leave on for standard Base64.",
      },
    ],
    related: ["base64-encode", "url-decode", "jwt-decoder"],
    icon: "Binary",
  },
  {
    slug: "url-encode",
    category: "dev",
    title: "URL Encode",
    short: "Percent-encode text for safe use in a URL",
    keywords: ["url encode", "percent encoding", "encodeuricomponent", "url encoder online"],
    io: "text",
    engine: "pure",
    op: "urlEncode",
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Encoding strength",
        choices: [
          { value: "component", label: "Component — encode everything (encodeURIComponent)" },
          { value: "uri", label: "Full URI — keep :/?#[]@ intact (encodeURI)" },
          { value: "form", label: "Form data — spaces become +" },
        ],
        default: "component",
      },
    ],
    related: ["url-decode", "base64-encode", "query-string-parser"],
    icon: "Link",
  },
  {
    slug: "url-decode",
    category: "dev",
    title: "URL Decode",
    short: "Turn percent-encoded text back into plain characters",
    keywords: ["url decode", "percent decode", "decodeuricomponent", "url decoder online"],
    io: "text",
    engine: "pure",
    op: "urlDecode",
    options: [
      {
        kind: "toggle",
        id: "plusAsSpace",
        label: "Treat + as a space",
        default: true,
        help: "Correct for form-encoded data. Turn off if a literal + matters.",
      },
    ],
    related: ["url-encode", "query-string-parser", "base64-decode"],
    icon: "Link",
  },
  {
    slug: "html-entity-encode",
    category: "dev",
    title: "HTML Entity Encode",
    short: "Escape &, <, > and quotes so markup renders as text",
    keywords: ["html encode", "html entities", "escape html", "html entity encoder"],
    io: "text",
    engine: "pure",
    op: "htmlEncode",
    options: [
      {
        kind: "toggle",
        id: "nonAscii",
        label: "Also encode non-ASCII characters",
        default: false,
        help: "Turns accents and emoji into numeric entities. Rarely needed with UTF-8.",
      },
    ],
    related: ["html-entity-decode", "url-encode", "markdown-to-html"],
    icon: "Code",
  },
  {
    slug: "html-entity-decode",
    category: "dev",
    title: "HTML Entity Decode",
    short: "Convert &amp; and &#233; back to real characters",
    keywords: ["html decode", "decode html entities", "unescape html", "html entity decoder"],
    io: "text",
    engine: "pure",
    op: "htmlDecode",
    options: [],
    related: ["html-entity-encode", "html-to-markdown", "url-decode"],
    icon: "Code",
  },
  {
    slug: "jwt-decoder",
    category: "dev",
    title: "JWT Decoder",
    short: "Read the header and claims inside a JSON Web Token",
    keywords: ["jwt decoder", "decode jwt", "json web token", "jwt viewer online"],
    io: "text",
    engine: "pure",
    op: "jwtDecode",
    options: [
      {
        kind: "toggle",
        id: "humanDates",
        label: "Show exp and iat as readable dates",
        default: true,
      },
    ],
    related: ["base64-decode", "json-formatter", "unix-timestamp-converter"],
    icon: "KeyRound",
  },
  {
    slug: "regex-tester",
    category: "dev",
    title: "Regex Tester",
    short: "Test a pattern against sample text and see every match",
    keywords: ["regex tester", "regular expression tester", "regex online", "test regex"],
    io: "text",
    engine: "pure",
    op: "regexTest",
    options: [
      {
        kind: "text",
        id: "pattern",
        label: "Pattern",
        default: "\\b\\w+@\\w+\\.\\w+\\b",
        placeholder: "\\d{4}-\\d{2}-\\d{2}",
      },
      {
        kind: "text",
        id: "flags",
        label: "Flags",
        default: "gi",
        placeholder: "gimsuy",
        maxLength: 8,
      },
      {
        kind: "select",
        id: "output",
        label: "Show",
        choices: [
          { value: "matches", label: "Every match, one per line" },
          { value: "groups", label: "Matches with capture groups" },
          { value: "replace", label: "Result after replacement" },
        ],
        default: "matches",
      },
      {
        kind: "text",
        id: "replacement",
        label: "Replace with",
        default: "",
        placeholder: "$1",
        showIf: { id: "output", equals: "replace" },
      },
    ],
    related: ["find-and-replace", "text-diff", "json-formatter"],
    icon: "Regex",
  },
  {
    slug: "uuid-generator",
    category: "dev",
    title: "UUID Generator",
    short: "Generate v4 or v7 UUIDs from your browser's crypto source",
    keywords: ["uuid generator", "guid generator", "random uuid", "uuid v4 online"],
    io: "form",
    engine: "pure",
    op: "uuidGenerate",
    options: [
      {
        kind: "select",
        id: "version",
        label: "Version",
        choices: [
          { value: "v4", label: "v4 — random" },
          { value: "v7", label: "v7 — time-ordered, sorts by creation" },
          { value: "nil", label: "Nil — all zeroes" },
        ],
        default: "v4",
      },
      { kind: "number", id: "count", label: "How many", default: 10, min: 1, max: 1000, step: 1 },
      { kind: "toggle", id: "uppercase", label: "Uppercase", default: false },
      { kind: "toggle", id: "braces", label: "Wrap in braces", default: false },
      { kind: "toggle", id: "hyphens", label: "Keep hyphens", default: true },
    ],
    related: ["password-generator", "hash-generator", "unix-timestamp-converter"],
    icon: "Fingerprint",
  },
  {
    slug: "cron-expression-parser",
    category: "dev",
    title: "Cron Expression Parser",
    short: "Read a cron line in plain English and see the next runs",
    keywords: ["cron parser", "crontab explained", "cron expression", "cron next run"],
    io: "text",
    engine: "pure",
    op: "cronExplain",
    options: [
      { kind: "number", id: "count", label: "Next runs to show", default: 5, min: 1, max: 25, step: 1 },
      {
        kind: "toggle",
        id: "utc",
        label: "Show times in UTC",
        default: false,
        help: "Off uses your device's time zone.",
      },
    ],
    related: ["unix-timestamp-converter", "date-difference-calculator"],
    icon: "Clock",
  },
  {
    slug: "unix-timestamp-converter",
    category: "dev",
    title: "Unix Timestamp Converter",
    short: "Move between epoch seconds, milliseconds and readable dates",
    keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "date to epoch"],
    io: "text",
    engine: "pure",
    op: "timestampConvert",
    options: [
      {
        kind: "select",
        id: "direction",
        label: "Convert",
        choices: [
          { value: "toDate", label: "Timestamp → date" },
          { value: "toStamp", label: "Date → timestamp" },
        ],
        default: "toDate",
      },
      {
        kind: "select",
        id: "unit",
        label: "Timestamp unit",
        choices: [
          { value: "auto", label: "Detect automatically" },
          { value: "s", label: "Seconds" },
          { value: "ms", label: "Milliseconds" },
        ],
        default: "auto",
      },
      { kind: "toggle", id: "utc", label: "Use UTC", default: true },
    ],
    related: ["cron-expression-parser", "date-difference-calculator", "jwt-decoder"],
    icon: "Clock",
  },
  {
    slug: "color-converter",
    category: "dev",
    title: "Color Converter",
    short: "One colour, every notation — HEX, RGB, HSL, OKLCH, CMYK",
    keywords: ["color converter", "hex to rgb", "rgb to hsl", "hex to hsl", "oklch converter"],
    io: "text",
    engine: "pure",
    op: "colorConvert",
    options: [
      {
        kind: "toggle",
        id: "contrast",
        label: "Include contrast against black and white",
        default: true,
        help: "WCAG ratios, so you can see at a glance whether text will pass.",
      },
    ],
    related: ["css-gradient-generator", "box-shadow-generator"],
    icon: "Palette",
  },
  {
    slug: "css-gradient-generator",
    category: "dev",
    title: "CSS Gradient Generator",
    short: "Build a linear or radial gradient and copy the CSS",
    keywords: ["css gradient generator", "linear gradient css", "radial gradient", "gradient maker"],
    io: "form",
    engine: "pure",
    op: "cssGradient",
    options: [
      {
        kind: "select",
        id: "type",
        label: "Type",
        choices: [
          { value: "linear", label: "Linear" },
          { value: "radial", label: "Radial" },
          { value: "conic", label: "Conic" },
        ],
        default: "linear",
      },
      {
        kind: "slider",
        id: "angle",
        label: "Angle",
        min: 0,
        max: 360,
        step: 1,
        default: 135,
        unit: "°",
        showIf: { id: "type", equals: "linear" },
      },
      { kind: "color", id: "from", label: "From", default: "#0ea5e9" },
      { kind: "color", id: "to", label: "To", default: "#7c3aed" },
      { kind: "toggle", id: "midpoint", label: "Add a middle stop", default: false },
      { kind: "color", id: "via", label: "Middle", default: "#22d3ee", showIf: { id: "midpoint", equals: true } },
    ],
    related: ["color-converter", "box-shadow-generator"],
    icon: "Blend",
  },
  {
    slug: "box-shadow-generator",
    category: "dev",
    title: "Box Shadow Generator",
    short: "Dial in a CSS shadow and copy the rule",
    keywords: ["box shadow generator", "css box shadow", "shadow maker css"],
    io: "form",
    engine: "pure",
    op: "boxShadow",
    options: [
      { kind: "slider", id: "x", label: "Horizontal offset", min: -64, max: 64, step: 1, default: 0, unit: "px" },
      { kind: "slider", id: "y", label: "Vertical offset", min: -64, max: 64, step: 1, default: 8, unit: "px" },
      { kind: "slider", id: "blur", label: "Blur", min: 0, max: 128, step: 1, default: 24, unit: "px" },
      { kind: "slider", id: "spread", label: "Spread", min: -64, max: 64, step: 1, default: -4, unit: "px" },
      { kind: "color", id: "color", label: "Colour", default: "#0f172a" },
      { kind: "slider", id: "opacity", label: "Opacity", min: 0, max: 100, step: 1, default: 18, unit: "%" },
      { kind: "toggle", id: "inset", label: "Inset", default: false },
    ],
    related: ["css-gradient-generator", "color-converter"],
    icon: "Square",
  },
  {
    slug: "query-string-parser",
    category: "dev",
    title: "Query String Parser",
    short: "Break a URL's query into readable key–value pairs",
    keywords: ["query string parser", "url parameters", "parse query string", "url query viewer"],
    io: "text",
    engine: "pure",
    op: "queryParse",
    options: [
      {
        kind: "select",
        id: "output",
        label: "Output as",
        choices: [
          { value: "table", label: "Plain list" },
          { value: "json", label: "JSON object" },
        ],
        default: "table",
      },
      { kind: "toggle", id: "decode", label: "Decode percent-escapes", default: true },
    ],
    related: ["url-decode", "json-formatter", "url-encode"],
    icon: "ListTree",
  },
  {
    slug: "slug-generator",
    category: "dev",
    title: "Slug Generator",
    short: "Turn a title into a clean, URL-safe slug",
    keywords: ["slug generator", "url slug", "slugify online", "seo slug maker"],
    io: "text",
    engine: "pure",
    op: "slugify",
    options: [
      { kind: "text", id: "separator", label: "Separator", default: "-", maxLength: 1 },
      { kind: "toggle", id: "lowercase", label: "Lowercase", default: true },
      {
        kind: "toggle",
        id: "stripStopWords",
        label: "Drop common stop words",
        default: false,
        help: "Removes a, the, of, and similar. Shorter slugs, slightly less readable.",
      },
      { kind: "number", id: "maxLength", label: "Maximum length", default: 0, min: 0, max: 200, step: 1, help: "0 means no limit." },
    ],
    related: ["case-converter", "url-encode", "word-counter"],
    icon: "Link2",
  },
  {
    slug: "lorem-ipsum-generator",
    category: "dev",
    title: "Lorem Ipsum Generator",
    short: "Placeholder copy in paragraphs, sentences or words",
    keywords: ["lorem ipsum generator", "placeholder text", "dummy text generator", "filler text"],
    io: "form",
    engine: "pure",
    op: "loremIpsum",
    options: [
      {
        kind: "select",
        id: "unit",
        label: "Generate",
        choices: [
          { value: "paragraphs", label: "Paragraphs" },
          { value: "sentences", label: "Sentences" },
          { value: "words", label: "Words" },
        ],
        default: "paragraphs",
      },
      { kind: "number", id: "count", label: "How many", default: 3, min: 1, max: 100, step: 1 },
      { kind: "toggle", id: "classic", label: "Start with “Lorem ipsum dolor sit amet”", default: true },
      { kind: "toggle", id: "html", label: "Wrap in <p> tags", default: false },
    ],
    related: ["word-counter", "case-converter"],
    icon: "AlignLeft",
  },
  {
    slug: "json-to-typescript",
    category: "dev",
    title: "JSON to TypeScript",
    short: "Generate interfaces from a sample JSON payload",
    keywords: ["json to typescript", "json to interface", "generate typescript types", "json type generator"],
    io: "text",
    engine: "pure",
    op: "jsonToTypeScript",
    options: [
      { kind: "text", id: "rootName", label: "Root type name", default: "Root" },
      {
        kind: "select",
        id: "style",
        label: "Declare as",
        choices: [
          { value: "interface", label: "interface" },
          { value: "type", label: "type alias" },
        ],
        default: "interface",
      },
      {
        kind: "toggle",
        id: "optional",
        label: "Mark null values optional",
        default: true,
        help: "A null in the sample becomes `field?: string | null` rather than `null`.",
      },
      { kind: "toggle", id: "readonly", label: "Readonly properties", default: false },
    ],
    related: ["json-formatter", "json-validator", "json-to-yaml"],
    icon: "Braces",
  },
];
