import type { ToolSpec } from "../types";

/**
 * Financial calculators. Pure arithmetic — no engine warm-up and no network.
 *
 * Four of these (SIP, EMI, compound interest and GST) started life in the
 * Calculators & Generators category and moved here when this one was created.
 * Their slugs are unchanged and the old paths redirect, because a working URL
 * that someone bookmarked is not ours to break.
 *
 * A rule that runs through the whole file: where a scheme has a notified rate,
 * the rate is an input with a plausible default, never a table pretending to be
 * current. Small-savings rates are re-notified quarterly and a hardcoded one
 * would be silently wrong within months on a page that looks authoritative.
 */
export const FINANCE_TOOLS: ToolSpec[] = [
  /* ---------------- Growing money ---------------- */
  {
    slug: "sip-calculator",
    category: "finance",
    title: "SIP Calculator",
    short: "What a monthly investment grows to at a given return",
    keywords: ["sip calculator", "mutual fund sip calculator", "monthly investment calculator", "sip returns"],
    io: "form",
    engine: "pure",
    op: "sip",
    options: [
      { kind: "number", id: "monthly", label: "Monthly investment", default: 10000, min: 1, step: 500 },
      { kind: "number", id: "rate", label: "Expected return", default: 12, min: 0, max: 40, step: 0.5, unit: "% a year" },
      { kind: "number", id: "years", label: "Duration", default: 10, min: 1, max: 50, step: 1, unit: " years" },
      { kind: "number", id: "stepUp", label: "Yearly step-up", default: 0, min: 0, max: 50, step: 1, unit: "%" },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year table", default: true },
    ],
    related: ["step-up-sip-calculator", "goal-sip-calculator", "lumpsum-calculator", "xirr-calculator"],
    icon: "TrendingUp",
  },
  {
    slug: "step-up-sip-calculator",
    category: "finance",
    title: "Step-Up SIP Calculator",
    short: "Raise the instalment every year and see what the increases are worth",
    keywords: ["step up sip calculator", "top up sip calculator", "increasing sip", "sip with annual increase"],
    io: "form",
    engine: "pure",
    op: "stepUpSip",
    options: [
      { kind: "number", id: "monthly", label: "Starting monthly amount", default: 10000, min: 1, step: 500 },
      { kind: "number", id: "stepUp", label: "Raise it each year by", default: 10, min: 0, max: 50, step: 1, unit: "%" },
      { kind: "number", id: "rate", label: "Expected return", default: 12, min: 0, max: 40, step: 0.5, unit: "% a year" },
      { kind: "number", id: "years", label: "Duration", default: 15, min: 1, max: 50, step: 1, unit: " years" },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year table", default: true },
    ],
    related: ["sip-calculator", "goal-sip-calculator", "retirement-calculator"],
    icon: "ChartNoAxesCombined",
  },
  {
    slug: "lumpsum-calculator",
    category: "finance",
    title: "Lumpsum Calculator",
    short: "What one investment becomes after a run of years",
    keywords: ["lumpsum calculator", "mutual fund calculator", "one time investment calculator", "future value calculator"],
    io: "form",
    engine: "pure",
    op: "lumpsum",
    options: [
      { kind: "number", id: "amount", label: "Amount invested", default: 500000, min: 1, step: 10000 },
      { kind: "number", id: "rate", label: "Expected return", default: 12, min: 0, max: 40, step: 0.5, unit: "% a year" },
      { kind: "number", id: "years", label: "Duration", default: 10, min: 0.25, max: 60, step: 0.25, unit: " years" },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year table", default: true },
    ],
    related: ["sip-calculator", "cagr-calculator", "compound-interest-calculator"],
    icon: "Coins",
  },
  {
    slug: "swp-calculator",
    category: "finance",
    title: "SWP Calculator",
    short: "How long a corpus lasts when you draw from it every month",
    keywords: ["swp calculator", "systematic withdrawal plan", "withdrawal calculator", "how long will my money last"],
    io: "form",
    engine: "pure",
    op: "swp",
    options: [
      { kind: "number", id: "corpus", label: "Starting corpus", default: 5000000, min: 1, step: 100000 },
      { kind: "number", id: "withdrawal", label: "Withdraw each month", default: 30000, min: 1, step: 1000 },
      { kind: "number", id: "rate", label: "Return on what is left", default: 8, min: 0, max: 30, step: 0.5, unit: "% a year" },
      { kind: "number", id: "years", label: "Plan for", default: 25, min: 1, max: 60, step: 1, unit: " years" },
      { kind: "number", id: "escalate", label: "Raise the withdrawal yearly by", default: 0, min: 0, max: 20, step: 1, unit: "%" },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year table", default: true },
    ],
    related: ["retirement-calculator", "post-office-mis-calculator", "senior-citizens-savings-calculator"],
    icon: "ArrowDownUp",
  },
  {
    slug: "goal-sip-calculator",
    category: "finance",
    title: "Goal SIP Calculator",
    short: "Work backwards from a target to the monthly amount that reaches it",
    keywords: ["goal sip calculator", "how much to invest monthly", "target amount calculator", "reverse sip calculator"],
    io: "form",
    engine: "pure",
    op: "goalSip",
    options: [
      { kind: "number", id: "target", label: "Target amount", default: 5000000, min: 1, step: 100000 },
      { kind: "number", id: "years", label: "Reach it in", default: 10, min: 0.5, max: 50, step: 0.5, unit: " years" },
      { kind: "number", id: "rate", label: "Expected return", default: 12, min: 0, max: 40, step: 0.5, unit: "% a year" },
      { kind: "number", id: "existing", label: "Already invested", default: 0, min: 0, step: 10000 },
    ],
    related: ["sip-calculator", "step-up-sip-calculator", "retirement-calculator"],
    icon: "Target",
  },
  {
    slug: "compound-interest-calculator",
    category: "finance",
    title: "Compound Interest Calculator",
    short: "Growth on a lump sum, compounded as often as you like",
    keywords: ["compound interest calculator", "interest calculator", "future value calculator"],
    io: "form",
    engine: "pure",
    op: "compoundInterest",
    options: [
      { kind: "number", id: "principal", label: "Starting amount", default: 100000, min: 0, step: 1000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 8, min: 0, max: 60, step: 0.1, unit: "% a year" },
      { kind: "number", id: "years", label: "Duration", default: 10, min: 0.25, max: 60, step: 0.25, unit: " years" },
      {
        kind: "select",
        id: "frequency",
        label: "Compounded",
        choices: [
          { value: "1", label: "Yearly" },
          { value: "2", label: "Half-yearly" },
          { value: "4", label: "Quarterly" },
          { value: "12", label: "Monthly" },
          { value: "365", label: "Daily" },
        ],
        default: "4",
      },
      { kind: "number", id: "contribution", label: "Added each month", default: 0, min: 0, step: 500 },
    ],
    related: ["simple-interest-calculator", "lumpsum-calculator", "fd-calculator"],
    icon: "ChartLine",
  },
  {
    slug: "simple-interest-calculator",
    category: "finance",
    title: "Simple Interest Calculator",
    short: "Interest on the original amount only, with the compound figure beside it",
    keywords: ["simple interest calculator", "si calculator", "interest on principal", "simple vs compound interest"],
    io: "form",
    engine: "pure",
    op: "simpleInterest",
    options: [
      { kind: "number", id: "principal", label: "Principal", default: 100000, min: 1, step: 1000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 8, min: 0, max: 60, step: 0.1, unit: "% a year" },
      { kind: "number", id: "years", label: "Duration", default: 5, min: 0.25, max: 60, step: 0.25, unit: " years" },
    ],
    related: ["compound-interest-calculator", "flat-vs-reducing-rate-calculator", "loan-emi-calculator"],
    icon: "Percent",
  },
  {
    slug: "cagr-calculator",
    category: "finance",
    title: "CAGR Calculator",
    short: "The smooth yearly rate that joins a starting value to an ending one",
    keywords: ["cagr calculator", "compound annual growth rate", "annualised return calculator", "cagr formula"],
    io: "form",
    engine: "pure",
    op: "cagr",
    options: [
      { kind: "number", id: "start", label: "Starting value", default: 100000, min: 0.01, step: 1000 },
      { kind: "number", id: "end", label: "Ending value", default: 250000, min: 0.01, step: 1000 },
      { kind: "number", id: "years", label: "Over", default: 5, min: 0.08, max: 60, step: 0.25, unit: " years" },
    ],
    related: ["xirr-calculator", "lumpsum-calculator", "inflation-calculator"],
    icon: "ChartSpline",
  },
  {
    slug: "xirr-calculator",
    category: "finance",
    title: "XIRR Calculator",
    short: "The real return on money that went in and out on irregular dates",
    keywords: ["xirr calculator", "irr calculator", "mutual fund xirr", "annualised return on irregular investments"],
    io: "text",
    engine: "pure",
    op: "xirr",
    options: [],
    related: ["cagr-calculator", "sip-calculator", "stock-average-calculator"],
    icon: "CalendarClock",
  },
  {
    slug: "stock-average-calculator",
    category: "finance",
    title: "Stock Average Calculator",
    short: "Average buy price across several purchases, with the position value",
    keywords: ["stock average calculator", "average price calculator", "share averaging", "cost basis calculator"],
    io: "text",
    engine: "pure",
    op: "stockAverage",
    options: [
      { kind: "number", id: "current", label: "Current price (optional)", default: 0, min: 0, step: 0.05 },
    ],
    related: ["brokerage-calculator", "xirr-calculator", "cagr-calculator"],
    icon: "Layers",
  },

  /* ---------------- Deposits and schemes ---------------- */
  {
    slug: "fd-calculator",
    category: "finance",
    title: "FD Calculator",
    short: "Fixed deposit maturity, cumulative or paid out, before and after tax",
    keywords: ["fd calculator", "fixed deposit calculator", "fd maturity calculator", "fd interest calculator"],
    io: "form",
    engine: "pure",
    op: "fixedDeposit",
    options: [
      { kind: "number", id: "principal", label: "Deposit", default: 500000, min: 1, step: 10000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 7, min: 0, max: 20, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Tenure", default: 5, min: 0.08, max: 20, step: 0.25, unit: " years" },
      {
        kind: "select",
        id: "payout",
        label: "Interest",
        choices: [
          { value: "cumulative", label: "Reinvested until maturity" },
          { value: "payout", label: "Paid out as it accrues" },
        ],
        default: "cumulative",
      },
      {
        kind: "select",
        id: "frequency",
        label: "Compounded or paid",
        choices: [
          { value: "1", label: "Yearly" },
          { value: "2", label: "Half-yearly" },
          { value: "4", label: "Quarterly" },
          { value: "12", label: "Monthly" },
        ],
        default: "4",
      },
      { kind: "number", id: "tax", label: "Your tax slab", default: 0, min: 0, max: 42.744, step: 0.1, unit: "%" },
    ],
    related: ["rd-calculator", "compound-interest-calculator", "senior-citizens-savings-calculator"],
    icon: "Landmark",
  },
  {
    slug: "rd-calculator",
    category: "finance",
    title: "RD Calculator",
    short: "Recurring deposit maturity, compounded quarterly the way banks do it",
    keywords: ["rd calculator", "recurring deposit calculator", "rd maturity calculator", "post office rd calculator"],
    io: "form",
    engine: "pure",
    op: "recurringDeposit",
    options: [
      { kind: "number", id: "monthly", label: "Monthly instalment", default: 5000, min: 1, step: 500 },
      { kind: "number", id: "rate", label: "Interest rate", default: 6.75, min: 0, max: 20, step: 0.05, unit: "% a year" },
      { kind: "number", id: "months", label: "Tenure", default: 60, min: 3, max: 240, step: 1, unit: " months" },
    ],
    related: ["fd-calculator", "sip-calculator", "ppf-calculator"],
    icon: "Repeat",
  },
  {
    slug: "ppf-calculator",
    category: "finance",
    title: "PPF Calculator",
    short: "Fifteen years of deposits, compounded yearly and tax free throughout",
    keywords: ["ppf calculator", "public provident fund calculator", "ppf maturity calculator", "ppf interest calculator"],
    io: "form",
    engine: "pure",
    op: "ppf",
    options: [
      { kind: "number", id: "yearly", label: "Deposit each year", default: 150000, min: 500, max: 150000, step: 500 },
      { kind: "number", id: "rate", label: "Interest rate", default: 7.1, min: 0, max: 15, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Term", default: 15, min: 5, max: 50, step: 5, unit: " years" },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year table", default: true },
    ],
    related: ["epf-calculator", "sukanya-samriddhi-calculator", "nsc-calculator"],
    icon: "PiggyBank",
  },
  {
    slug: "epf-calculator",
    category: "finance",
    title: "EPF Calculator",
    short: "Provident fund at retirement, with the pension share taken out properly",
    keywords: ["epf calculator", "pf calculator", "provident fund calculator", "epf maturity calculator"],
    io: "form",
    engine: "pure",
    op: "employeeProvidentFund",
    options: [
      { kind: "number", id: "wage", label: "Monthly basic plus DA", default: 40000, min: 1, step: 1000 },
      { kind: "number", id: "age", label: "Your age", default: 30, min: 15, max: 60, step: 1 },
      { kind: "number", id: "retireAt", label: "Retiring at", default: 58, min: 40, max: 70, step: 1 },
      { kind: "number", id: "rate", label: "Interest rate", default: 8.25, min: 0, max: 15, step: 0.05, unit: "% a year" },
      { kind: "number", id: "growth", label: "Yearly salary growth", default: 5, min: 0, max: 30, step: 0.5, unit: "%" },
      { kind: "number", id: "balance", label: "Balance already in it", default: 0, min: 0, step: 10000 },
      { kind: "number", id: "employeeShare", label: "Your contribution", default: 12, min: 12, max: 100, step: 1, unit: "% of wage" },
      { kind: "number", id: "ceiling", label: "Pension wage ceiling", default: 15000, min: 0, step: 500 },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year table", default: true },
    ],
    related: ["ppf-calculator", "nps-calculator", "gratuity-calculator"],
    icon: "Building2",
  },
  {
    slug: "nps-calculator",
    category: "finance",
    title: "NPS Calculator",
    short: "Corpus at sixty, the tax-free lump sum and the pension it buys",
    keywords: ["nps calculator", "national pension scheme calculator", "nps pension calculator", "nps maturity"],
    io: "form",
    engine: "pure",
    op: "nps",
    options: [
      { kind: "number", id: "monthly", label: "Monthly contribution", default: 5000, min: 1, step: 500 },
      { kind: "number", id: "age", label: "Your age", default: 30, min: 18, max: 65, step: 1 },
      { kind: "number", id: "retireAt", label: "Retiring at", default: 60, min: 40, max: 75, step: 1 },
      { kind: "number", id: "rate", label: "Expected return", default: 10, min: 0, max: 25, step: 0.5, unit: "% a year" },
      { kind: "number", id: "annuityShare", label: "Share buying an annuity", default: 40, min: 40, max: 100, step: 5, unit: "%" },
      { kind: "number", id: "annuityRate", label: "Annuity rate", default: 6, min: 1, max: 15, step: 0.25, unit: "% a year" },
    ],
    related: ["epf-calculator", "retirement-calculator", "ppf-calculator"],
    icon: "Umbrella",
  },
  {
    slug: "sukanya-samriddhi-calculator",
    category: "finance",
    title: "Sukanya Samriddhi Calculator",
    short: "Fifteen years of deposits that keep earning until the account turns twenty-one",
    keywords: ["sukanya samriddhi calculator", "ssy calculator", "sukanya samriddhi yojana", "girl child savings scheme"],
    io: "form",
    engine: "pure",
    op: "sukanyaSamriddhi",
    options: [
      { kind: "number", id: "yearly", label: "Deposit each year", default: 150000, min: 250, max: 150000, step: 500 },
      { kind: "number", id: "rate", label: "Interest rate", default: 8.2, min: 0, max: 15, step: 0.05, unit: "% a year" },
      { kind: "number", id: "age", label: "Her age when you open it", default: 5, min: 0, max: 10, step: 1 },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year table", default: true },
    ],
    related: ["ppf-calculator", "nsc-calculator", "rd-calculator"],
    icon: "Baby",
  },
  {
    slug: "nsc-calculator",
    category: "finance",
    title: "NSC Calculator",
    short: "National Savings Certificate maturity, with the reinvested interest shown",
    keywords: ["nsc calculator", "national savings certificate calculator", "nsc interest calculator", "nsc maturity value"],
    io: "form",
    engine: "pure",
    op: "nsc",
    options: [
      { kind: "number", id: "amount", label: "Amount invested", default: 100000, min: 1000, step: 1000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 7.7, min: 0, max: 15, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Term", default: 5, min: 1, max: 10, step: 1, unit: " years" },
    ],
    related: ["ppf-calculator", "fd-calculator", "post-office-mis-calculator"],
    icon: "ScrollText",
  },
  {
    slug: "senior-citizens-savings-calculator",
    category: "finance",
    title: "SCSS Calculator",
    short: "Quarterly income from the Senior Citizens Savings Scheme",
    keywords: ["scss calculator", "senior citizens savings scheme calculator", "scss interest calculator", "senior citizen deposit"],
    io: "form",
    engine: "pure",
    op: "seniorCitizensSavings",
    options: [
      { kind: "number", id: "deposit", label: "Deposit", default: 1500000, min: 1000, max: 3000000, step: 10000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 8.2, min: 0, max: 15, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Term", default: 5, min: 1, max: 10, step: 1, unit: " years" },
    ],
    related: ["post-office-mis-calculator", "fd-calculator", "swp-calculator"],
    icon: "HandCoins",
  },
  {
    slug: "post-office-mis-calculator",
    category: "finance",
    title: "Post Office MIS Calculator",
    short: "Monthly income from a post office deposit, with the account caps applied",
    keywords: ["post office mis calculator", "monthly income scheme calculator", "pomis calculator", "post office monthly income"],
    io: "form",
    engine: "pure",
    op: "postOfficeMis",
    options: [
      { kind: "number", id: "deposit", label: "Deposit", default: 900000, min: 1000, max: 1500000, step: 10000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 7.4, min: 0, max: 15, step: 0.05, unit: "% a year" },
      {
        kind: "select",
        id: "holding",
        label: "Account",
        choices: [
          { value: "single", label: "Single — capped at 9,00,000" },
          { value: "joint", label: "Joint — capped at 15,00,000" },
        ],
        default: "single",
      },
      { kind: "number", id: "years", label: "Term", default: 5, min: 1, max: 10, step: 1, unit: " years" },
    ],
    related: ["senior-citizens-savings-calculator", "swp-calculator", "fd-calculator"],
    icon: "Mailbox",
  },

  /* ---------------- Borrowing ---------------- */
  {
    slug: "loan-emi-calculator",
    category: "finance",
    title: "Loan EMI Calculator",
    short: "Monthly instalment, total interest and a full amortisation table",
    keywords: ["emi calculator", "loan calculator", "personal loan emi", "emi calculation formula"],
    io: "form",
    engine: "pure",
    op: "loanEmi",
    options: [
      { kind: "number", id: "principal", label: "Loan amount", default: 2500000, min: 1, step: 1000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 8.5, min: 0, max: 60, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Tenure", default: 20, min: 0.25, max: 40, step: 0.25, unit: " years" },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year schedule", default: true },
    ],
    related: ["home-loan-emi-calculator", "car-loan-emi-calculator", "loan-prepayment-calculator", "flat-vs-reducing-rate-calculator"],
    icon: "Banknote",
  },
  {
    slug: "home-loan-emi-calculator",
    category: "finance",
    title: "Home Loan EMI Calculator",
    short: "Instalment from the property price, with the first year's interest split out",
    keywords: ["home loan emi calculator", "housing loan calculator", "home loan interest calculator", "home loan amortisation"],
    io: "form",
    engine: "pure",
    op: "homeLoanEmi",
    options: [
      { kind: "number", id: "price", label: "Property price", default: 8000000, min: 1, step: 100000 },
      { kind: "number", id: "down", label: "Down payment", default: 20, min: 0, max: 100, step: 1, unit: "% of price" },
      { kind: "number", id: "rate", label: "Interest rate", default: 8.5, min: 0, max: 30, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Tenure", default: 20, min: 1, max: 35, step: 1, unit: " years" },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year schedule", default: true },
    ],
    related: ["home-loan-eligibility-calculator", "loan-prepayment-calculator", "loan-emi-calculator"],
    icon: "House",
  },
  {
    slug: "car-loan-emi-calculator",
    category: "finance",
    title: "Car Loan EMI Calculator",
    short: "Instalment on the on-road price, against what the car is worth at the end",
    keywords: ["car loan emi calculator", "auto loan calculator", "vehicle loan emi", "on road price emi calculator"],
    io: "form",
    engine: "pure",
    op: "carLoanEmi",
    options: [
      { kind: "number", id: "price", label: "Ex-showroom price", default: 1200000, min: 1, step: 25000 },
      { kind: "number", id: "onRoad", label: "Taxes, insurance and extras", default: 10, min: 0, max: 40, step: 0.5, unit: "% on top" },
      { kind: "number", id: "down", label: "Down payment", default: 200000, min: 0, step: 10000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 9.5, min: 0, max: 30, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Tenure", default: 5, min: 1, max: 8, step: 1, unit: " years" },
      { kind: "number", id: "depreciation", label: "Yearly depreciation", default: 15, min: 0, max: 40, step: 1, unit: "%" },
      { kind: "toggle", id: "schedule", label: "Show the year-by-year schedule", default: true },
    ],
    related: ["loan-emi-calculator", "flat-vs-reducing-rate-calculator", "loan-prepayment-calculator"],
    icon: "Car",
  },
  {
    slug: "loan-prepayment-calculator",
    category: "finance",
    title: "Loan Prepayment Calculator",
    short: "What a part payment saves, and whether to cut the tenure or the instalment",
    keywords: ["loan prepayment calculator", "part payment calculator", "home loan prepayment", "prepayment interest saved"],
    io: "form",
    engine: "pure",
    op: "loanPrepayment",
    options: [
      { kind: "number", id: "principal", label: "Loan amount", default: 5000000, min: 1, step: 100000 },
      { kind: "number", id: "rate", label: "Interest rate", default: 8.5, min: 0, max: 30, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Original tenure", default: 20, min: 1, max: 35, step: 1, unit: " years" },
      { kind: "number", id: "lump", label: "Part payment", default: 500000, min: 0, step: 50000 },
      { kind: "number", id: "after", label: "Paid in month", default: 24, min: 1, max: 420, step: 1 },
      { kind: "number", id: "extra", label: "Extra every month", default: 0, min: 0, step: 1000 },
      {
        kind: "select",
        id: "keep",
        label: "Use the saving to",
        choices: [
          { value: "tenure", label: "End the loan sooner, instalment unchanged" },
          { value: "emi", label: "Cut the instalment, end date unchanged" },
        ],
        default: "tenure",
      },
    ],
    related: ["home-loan-emi-calculator", "loan-emi-calculator", "home-loan-eligibility-calculator"],
    icon: "Scissors",
  },
  {
    slug: "flat-vs-reducing-rate-calculator",
    category: "finance",
    title: "Flat vs Reducing Rate Calculator",
    short: "What a flat rate really costs once it is stated as a reducing one",
    keywords: ["flat vs reducing rate calculator", "flat interest rate calculator", "reducing balance rate", "effective interest rate"],
    io: "form",
    engine: "pure",
    op: "flatVsReducing",
    options: [
      { kind: "number", id: "principal", label: "Loan amount", default: 500000, min: 1, step: 10000 },
      { kind: "number", id: "flatRate", label: "Flat rate quoted", default: 7, min: 0, max: 40, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Tenure", default: 5, min: 0.25, max: 30, step: 0.25, unit: " years" },
      { kind: "number", id: "reducingRate", label: "Compare with a reducing rate of", default: 0, min: 0, max: 40, step: 0.05, unit: "% a year" },
    ],
    related: ["car-loan-emi-calculator", "loan-emi-calculator", "simple-interest-calculator"],
    icon: "Scale",
  },
  {
    slug: "home-loan-eligibility-calculator",
    category: "finance",
    title: "Home Loan Eligibility Calculator",
    short: "The loan your income can carry, and the property it reaches",
    keywords: ["home loan eligibility calculator", "loan eligibility calculator", "how much home loan can i get", "foir calculator"],
    io: "form",
    engine: "pure",
    op: "homeLoanEligibility",
    options: [
      { kind: "number", id: "income", label: "Monthly income", default: 150000, min: 1, step: 5000 },
      { kind: "number", id: "obligations", label: "Instalments you already pay", default: 0, min: 0, step: 1000 },
      { kind: "number", id: "foir", label: "Share of income a lender allows", default: 50, min: 10, max: 80, step: 5, unit: "%" },
      { kind: "number", id: "rate", label: "Interest rate", default: 8.5, min: 0, max: 30, step: 0.05, unit: "% a year" },
      { kind: "number", id: "years", label: "Tenure", default: 20, min: 1, max: 35, step: 1, unit: " years" },
      { kind: "number", id: "ltv", label: "Share of price a lender funds", default: 80, min: 30, max: 90, step: 5, unit: "%" },
    ],
    related: ["home-loan-emi-calculator", "loan-prepayment-calculator", "salary-calculator"],
    icon: "KeyRound",
  },

  /* ---------------- Earning and paying ---------------- */
  {
    slug: "income-tax-calculator",
    category: "finance",
    title: "Income Tax Calculator",
    short: "Tax under both regimes side by side, slab by slab",
    keywords: ["income tax calculator", "new tax regime calculator", "old vs new regime", "tax slab calculator india"],
    io: "form",
    engine: "pure",
    op: "incomeTax",
    options: [
      { kind: "number", id: "income", label: "Gross salary for the year", default: 1500000, min: 1, step: 50000 },
      {
        kind: "select",
        id: "regime",
        label: "Regime",
        choices: [
          { value: "new", label: "New regime" },
          { value: "old", label: "Old regime" },
        ],
        default: "new",
      },
      { kind: "toggle", id: "salaried", label: "Salaried, so the standard deduction applies", default: true },
      { kind: "number", id: "deductions", label: "Deductions claimed (old regime only)", default: 0, min: 0, step: 10000 },
      { kind: "number", id: "other", label: "Other income", default: 0, min: 0, step: 10000 },
    ],
    related: ["salary-calculator", "hra-calculator", "tds-calculator", "gratuity-calculator"],
    icon: "Receipt",
  },
  {
    slug: "salary-calculator",
    category: "finance",
    title: "Salary Calculator",
    short: "What lands in the bank each month, starting from the CTC on the offer",
    keywords: ["salary calculator", "in hand salary calculator", "ctc to take home", "take home salary india"],
    io: "form",
    engine: "pure",
    op: "salaryBreakup",
    options: [
      { kind: "number", id: "ctc", label: "Cost to company", default: 1800000, min: 1, step: 50000 },
      { kind: "number", id: "basic", label: "Basic pay", default: 40, min: 20, max: 100, step: 1, unit: "% of fixed pay" },
      { kind: "number", id: "bonus", label: "Variable or bonus", default: 0, min: 0, max: 60, step: 1, unit: "% of CTC" },
      { kind: "number", id: "professionalTax", label: "Professional tax for the year", default: 2400, min: 0, max: 5000, step: 100 },
      {
        kind: "select",
        id: "pfBasis",
        label: "Provident fund calculated on",
        help: "Employers may contribute on your actual basic pay or restrict it to the statutory wage ceiling. Both are common, and the difference is large at a senior salary.",
        choices: [
          { value: "actual", label: "Actual basic pay" },
          { value: "ceiling", label: "The statutory wage ceiling" },
        ],
        default: "actual",
      },
      {
        kind: "select",
        id: "regime",
        label: "Tax regime",
        choices: [
          { value: "new", label: "New regime" },
          { value: "old", label: "Old regime" },
        ],
        default: "new",
      },
      { kind: "number", id: "deductions", label: "Deductions claimed (old regime only)", default: 0, min: 0, step: 10000 },
    ],
    related: ["income-tax-calculator", "hra-calculator", "epf-calculator", "gratuity-calculator"],
    icon: "Wallet",
  },
  {
    slug: "hra-calculator",
    category: "finance",
    title: "HRA Calculator",
    short: "The exemption, as the least of three figures, with the binding one named",
    keywords: ["hra calculator", "hra exemption calculator", "house rent allowance", "hra exemption rules"],
    io: "form",
    engine: "pure",
    op: "hra",
    options: [
      { kind: "number", id: "basic", label: "Monthly basic pay", default: 50000, min: 1, step: 1000 },
      { kind: "number", id: "da", label: "Dearness allowance", default: 0, min: 0, step: 1000 },
      { kind: "number", id: "hra", label: "HRA received each month", default: 25000, min: 1, step: 1000 },
      { kind: "number", id: "rent", label: "Rent paid each month", default: 25000, min: 0, step: 1000 },
      { kind: "toggle", id: "metro", label: "Living in Delhi, Mumbai, Kolkata or Chennai", default: true },
    ],
    related: ["income-tax-calculator", "salary-calculator", "tds-calculator"],
    icon: "DoorOpen",
  },
  {
    slug: "gratuity-calculator",
    category: "finance",
    title: "Gratuity Calculator",
    short: "What is due after five years, and how the statutory cap bites",
    keywords: ["gratuity calculator", "gratuity formula", "gratuity eligibility", "gratuity calculation india"],
    io: "form",
    engine: "pure",
    op: "gratuity",
    options: [
      { kind: "number", id: "salary", label: "Last drawn basic plus DA", default: 60000, min: 1, step: 1000 },
      { kind: "number", id: "years", label: "Years of service", default: 10, min: 0, max: 50, step: 0.25 },
      { kind: "toggle", id: "covered", label: "Employer is covered by the Payment of Gratuity Act", default: true },
    ],
    related: ["epf-calculator", "salary-calculator", "income-tax-calculator"],
    icon: "Award",
  },
  {
    slug: "tds-calculator",
    category: "finance",
    title: "TDS Calculator",
    short: "Deduction by section, with the threshold and the no-PAN rate",
    keywords: ["tds calculator", "tds rate chart", "tds on professional fees", "tds deduction calculator"],
    io: "form",
    engine: "pure",
    op: "tds",
    options: [
      { kind: "number", id: "amount", label: "Payment", default: 100000, min: 1, step: 1000 },
      {
        kind: "select",
        id: "section",
        label: "Section",
        choices: [
          { value: "194J", label: "194J — professional or technical fees" },
          { value: "194C", label: "194C — payment to a contractor" },
          { value: "194H", label: "194H — commission or brokerage" },
          { value: "194I", label: "194I — rent of land or building" },
          { value: "194A", label: "194A — interest other than on securities" },
          { value: "192A", label: "192A — early provident fund withdrawal" },
          { value: "194", label: "194 — dividend" },
          { value: "194Q", label: "194Q — purchase of goods" },
          { value: "194O", label: "194O — e-commerce sale" },
        ],
        default: "194J",
      },
      { kind: "number", id: "rate", label: "Override the rate", default: 0, min: 0, max: 40, step: 0.1, unit: "%" },
      { kind: "toggle", id: "pan", label: "PAN is on file", default: true },
    ],
    related: ["income-tax-calculator", "gst-calculator", "salary-calculator"],
    icon: "FileMinus",
  },
  {
    slug: "gst-calculator",
    category: "finance",
    title: "GST Calculator",
    short: "Add or strip GST and split it into CGST and SGST",
    keywords: ["gst calculator", "gst inclusive calculator", "reverse gst", "cgst sgst calculator"],
    io: "form",
    engine: "pure",
    op: "gst",
    options: [
      { kind: "number", id: "amount", label: "Amount", default: 1000, min: 0, step: 1 },
      {
        kind: "select",
        id: "rate",
        label: "GST rate",
        choices: [
          { value: "0", label: "0%" },
          { value: "0.25", label: "0.25%" },
          { value: "3", label: "3%" },
          { value: "5", label: "5%" },
          { value: "12", label: "12%" },
          { value: "18", label: "18%" },
          { value: "28", label: "28%" },
        ],
        default: "18",
      },
      {
        kind: "select",
        id: "mode",
        label: "The amount above is",
        choices: [
          { value: "exclusive", label: "Before GST — add it on" },
          { value: "inclusive", label: "After GST — work backwards" },
        ],
        default: "exclusive",
      },
      { kind: "toggle", id: "interstate", label: "Inter-state supply — IGST instead of CGST + SGST", default: false },
    ],
    related: ["tds-calculator", "income-tax-calculator", "discount-calculator"],
    icon: "ReceiptIndianRupee",
  },
  {
    slug: "inflation-calculator",
    category: "finance",
    title: "Inflation Calculator",
    short: "What today's cost becomes, and what today's money will still buy",
    keywords: ["inflation calculator", "purchasing power calculator", "real return calculator", "future cost calculator"],
    io: "form",
    engine: "pure",
    op: "inflation",
    options: [
      { kind: "number", id: "amount", label: "Amount today", default: 100000, min: 1, step: 5000 },
      { kind: "number", id: "rate", label: "Inflation", default: 6, min: 0, max: 30, step: 0.25, unit: "% a year" },
      { kind: "number", id: "years", label: "Over", default: 10, min: 0.25, max: 60, step: 0.25, unit: " years" },
      { kind: "number", id: "nominal", label: "Your return, to get the real one", default: 0, min: 0, max: 40, step: 0.25, unit: "% a year" },
    ],
    related: ["retirement-calculator", "cagr-calculator", "goal-sip-calculator"],
    icon: "Flame",
  },

  /* ---------------- Retiring and trading ---------------- */
  {
    slug: "retirement-calculator",
    category: "finance",
    title: "Retirement Calculator",
    short: "The corpus a retirement needs, and the monthly amount that builds it",
    keywords: ["retirement calculator", "retirement corpus calculator", "how much do i need to retire", "retirement planning india"],
    io: "form",
    engine: "pure",
    op: "retirement",
    options: [
      { kind: "number", id: "age", label: "Your age", default: 30, min: 18, max: 70, step: 1 },
      { kind: "number", id: "retireAt", label: "Retiring at", default: 60, min: 35, max: 75, step: 1 },
      { kind: "number", id: "until", label: "Plan until age", default: 85, min: 60, max: 105, step: 1 },
      { kind: "number", id: "expense", label: "Monthly expense today", default: 60000, min: 1, step: 5000 },
      { kind: "number", id: "inflation", label: "Inflation", default: 6, min: 0, max: 20, step: 0.25, unit: "% a year" },
      { kind: "number", id: "preReturn", label: "Return while building", default: 12, min: 0, max: 30, step: 0.5, unit: "% a year" },
      { kind: "number", id: "postReturn", label: "Return in retirement", default: 7, min: 0, max: 30, step: 0.5, unit: "% a year" },
      { kind: "number", id: "existing", label: "Already saved", default: 0, min: 0, step: 100000 },
    ],
    related: ["nps-calculator", "swp-calculator", "goal-sip-calculator", "inflation-calculator"],
    icon: "Palmtree",
  },
  {
    slug: "brokerage-calculator",
    category: "finance",
    title: "Brokerage Calculator",
    short: "Every charge on an equity trade, line by line, and the break-even move",
    keywords: ["brokerage calculator", "trading charges calculator", "stt calculator", "intraday charges calculator"],
    io: "form",
    engine: "pure",
    op: "brokerage",
    options: [
      { kind: "number", id: "buy", label: "Buy price", default: 100, min: 0.01, step: 0.05 },
      { kind: "number", id: "sell", label: "Sell price", default: 110, min: 0.01, step: 0.05 },
      { kind: "number", id: "quantity", label: "Quantity", default: 100, min: 1, step: 1 },
      {
        kind: "select",
        id: "segment",
        label: "Segment",
        choices: [
          { value: "delivery", label: "Equity delivery" },
          { value: "intraday", label: "Equity intraday" },
        ],
        default: "delivery",
      },
      { kind: "number", id: "brokerage", label: "Your broker's rate", default: 0, min: 0, max: 5, step: 0.01, unit: "% a side" },
      { kind: "number", id: "cap", label: "Capped at", default: 20, min: 0, step: 1, unit: " a side" },
    ],
    related: ["stock-average-calculator", "xirr-calculator", "cagr-calculator"],
    icon: "CandlestickChart",
  },
];
