import type { AcceptSpec, OptionSpec, ToolSpec } from "../types";

/**
 * Image tools. All of them run on the browser's own canvas — no WASM, no model
 * downloads, so they start instantly and work offline.
 */

const IMAGES_IN: AcceptSpec = {
  mime: ["image/jpeg", "image/png", "image/webp", "image/gif", "image/bmp", "image/avif"],
  ext: ["jpg", "jpeg", "png", "webp", "gif", "bmp", "avif"],
  multiple: true,
  maxMB: 60,
};

const ONE_IMAGE_IN: AcceptSpec = { ...IMAGES_IN, multiple: false };

const IMAGE_OUT = { ext: "jpg", mime: "image/jpeg", cardinality: "per-file" as const };

/** Output format, offered wherever keeping the input's own format is sensible. */
const formatOption: OptionSpec = {
  kind: "select",
  id: "format",
  label: "Save as",
  choices: [
    { value: "same", label: "Same as the original" },
    { value: "jpeg", label: "JPEG" },
    { value: "png", label: "PNG" },
    { value: "webp", label: "WebP" },
  ],
  default: "same",
};

const qualityOption = (fallback: number): OptionSpec => ({
  kind: "slider",
  id: "quality",
  label: "Quality",
  min: 40,
  max: 100,
  step: 1,
  default: fallback,
  unit: "%",
  help: "Ignored for PNG, which is always lossless.",
});

export const IMAGE_TOOLS: ToolSpec[] = [
  {
    slug: "compress-image",
    category: "image",
    title: "Compress Image",
    short: "Shrink photos by quality or to a target file size",
    keywords: ["compress image", "reduce image size", "compress jpeg", "image compressor online free"],
    io: "file",
    engine: "image",
    op: "compressImage",
    accepts: IMAGES_IN,
    output: IMAGE_OUT,
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Compress by",
        choices: [
          { value: "quality", label: "Quality — you choose the setting" },
          { value: "size", label: "Target size — find the quality that fits" },
        ],
        default: "quality",
      },
      {
        kind: "slider",
        id: "quality",
        label: "Quality",
        min: 30,
        max: 95,
        step: 1,
        default: 75,
        unit: "%",
        showIf: { id: "mode", equals: "quality" },
      },
      {
        kind: "number",
        id: "targetKb",
        label: "Target size",
        default: 200,
        min: 10,
        max: 20000,
        step: 10,
        unit: " KB",
        showIf: { id: "mode", equals: "size" },
      },
      {
        kind: "number",
        id: "maxWidth",
        label: "Also limit width to",
        default: 0,
        min: 0,
        max: 8000,
        step: 100,
        unit: " px",
        help: "0 keeps the original dimensions. Resizing saves far more than quality alone.",
      },
      {
        kind: "select",
        id: "format",
        label: "Save as",
        choices: [
          { value: "jpeg", label: "JPEG — best for photographs" },
          { value: "webp", label: "WebP — smaller again, well supported" },
          { value: "png", label: "PNG — lossless, best for graphics" },
        ],
        default: "jpeg",
      },
    ],
    related: ["resize-image", "convert-image", "strip-image-metadata"],
    icon: "Minimize2",
  },
  {
    slug: "resize-image",
    category: "image",
    title: "Resize Image",
    short: "Change dimensions by size, percentage or to fit a box",
    keywords: ["resize image", "image resizer", "change image size", "resize photo online"],
    io: "file",
    engine: "image",
    op: "resizeImage",
    accepts: IMAGES_IN,
    output: IMAGE_OUT,
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Resize by",
        choices: [
          { value: "fit", label: "Fit inside a box, keeping the shape" },
          { value: "cover", label: "Fill a box exactly, cropping the overflow" },
          { value: "width", label: "Width — height follows" },
          { value: "height", label: "Height — width follows" },
          { value: "percent", label: "Percentage" },
          { value: "exact", label: "Exact size, ignoring the shape" },
        ],
        default: "fit",
      },
      { kind: "number", id: "width", label: "Width", default: 1920, min: 1, max: 12000, step: 10, unit: " px", showIf: { id: "mode", equals: "fit" } },
      { kind: "number", id: "height", label: "Height", default: 1080, min: 1, max: 12000, step: 10, unit: " px", showIf: { id: "mode", equals: "fit" } },
      { kind: "slider", id: "percent", label: "Scale to", min: 5, max: 400, step: 5, default: 50, unit: "%", showIf: { id: "mode", equals: "percent" } },
      {
        kind: "toggle",
        id: "allowUpscale",
        label: "Allow enlarging",
        default: false,
        help: "Off leaves images already smaller than the target alone. Enlarging invents detail the photo never had.",
      },
      formatOption,
      qualityOption(88),
    ],
    related: ["compress-image", "crop-image", "favicon-generator"],
    icon: "Scaling",
  },
  {
    slug: "crop-image",
    category: "image",
    title: "Crop Image",
    short: "Trim to a region, or to a fixed aspect ratio",
    keywords: ["crop image", "image cropper", "crop photo online", "crop to square"],
    io: "file",
    engine: "image",
    op: "cropImage",
    accepts: IMAGES_IN,
    output: IMAGE_OUT,
    options: [
      {
        kind: "select",
        id: "aspect",
        label: "Aspect ratio",
        choices: [
          { value: "free", label: "Free" },
          { value: "1:1", label: "Square (1:1)" },
          { value: "4:3", label: "4:3" },
          { value: "3:2", label: "3:2" },
          { value: "16:9", label: "16:9" },
          { value: "9:16", label: "9:16 — portrait video" },
        ],
        default: "free",
      },
      {
        kind: "select",
        id: "unit",
        label: "Measure in",
        choices: [
          { value: "percent", label: "Percent of the image" },
          { value: "pixels", label: "Pixels" },
        ],
        default: "percent",
      },
      { kind: "number", id: "x", label: "From the left", default: 10, min: 0, max: 10000, step: 1 },
      { kind: "number", id: "y", label: "From the top", default: 10, min: 0, max: 10000, step: 1 },
      { kind: "number", id: "width", label: "Width", default: 80, min: 1, max: 12000, step: 1 },
      { kind: "number", id: "height", label: "Height", default: 80, min: 1, max: 12000, step: 1 },
      formatOption,
      qualityOption(92),
    ],
    related: ["resize-image", "rotate-image", "blur-image-area"],
    icon: "Crop",
  },
  {
    slug: "rotate-image",
    category: "image",
    title: "Rotate Image",
    short: "Turn by 90°, 180° or 270°, and flip either way",
    keywords: ["rotate image", "flip image", "turn photo", "rotate picture online"],
    io: "file",
    engine: "image",
    op: "rotateImage",
    accepts: IMAGES_IN,
    output: IMAGE_OUT,
    options: [
      {
        kind: "select",
        id: "angle",
        label: "Rotate",
        choices: [
          { value: "0", label: "Don't rotate" },
          { value: "90", label: "90° clockwise" },
          { value: "180", label: "180°" },
          { value: "270", label: "90° anticlockwise" },
        ],
        default: "90",
      },
      { kind: "toggle", id: "flipHorizontal", label: "Flip left to right", default: false },
      { kind: "toggle", id: "flipVertical", label: "Flip top to bottom", default: false },
      formatOption,
      qualityOption(92),
    ],
    related: ["crop-image", "resize-image", "photo-filters"],
    icon: "RotateCw",
  },
  {
    slug: "convert-image",
    category: "image",
    title: "Convert Image",
    short: "Move between JPEG, PNG and WebP",
    keywords: ["convert image", "png to jpg", "jpg to png", "webp converter", "image format converter"],
    io: "file",
    engine: "image",
    op: "convertImage",
    accepts: IMAGES_IN,
    output: IMAGE_OUT,
    options: [
      {
        kind: "select",
        id: "format",
        label: "Convert to",
        choices: [
          { value: "jpeg", label: "JPEG — photographs, no transparency" },
          { value: "png", label: "PNG — lossless, keeps transparency" },
          { value: "webp", label: "WebP — smaller, keeps transparency" },
        ],
        default: "jpeg",
      },
      qualityOption(90),
      {
        kind: "color",
        id: "background",
        label: "Fill transparency with",
        default: "#ffffff",
        help: "JPEG cannot store transparency, so transparent areas need a colour.",
        showIf: { id: "format", equals: "jpeg" },
      },
    ],
    related: ["compress-image", "resize-image", "strip-image-metadata"],
    icon: "Replace",
  },
  {
    slug: "watermark-image",
    category: "image",
    title: "Watermark Image",
    short: "Stamp text across a picture, once or tiled",
    keywords: ["watermark image", "add watermark to photo", "watermark maker", "copyright photo"],
    io: "file",
    engine: "image",
    op: "watermarkImage",
    accepts: IMAGES_IN,
    output: IMAGE_OUT,
    options: [
      { kind: "text", id: "text", label: "Watermark text", default: "© MSRX", placeholder: "© Your name" },
      {
        kind: "select",
        id: "position",
        label: "Position",
        choices: [
          { value: "bottom-right", label: "Bottom right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "bottom-center", label: "Bottom centre" },
          { value: "middle-center", label: "Middle" },
          { value: "top-right", label: "Top right" },
          { value: "top-left", label: "Top left" },
        ],
        default: "bottom-right",
      },
      { kind: "slider", id: "size", label: "Text size", min: 2, max: 20, step: 1, default: 5, unit: "% of the image" },
      { kind: "slider", id: "opacity", label: "Opacity", min: 5, max: 100, step: 1, default: 45, unit: "%" },
      { kind: "slider", id: "angle", label: "Angle", min: -90, max: 90, step: 5, default: 0, unit: "°" },
      { kind: "color", id: "color", label: "Colour", default: "#ffffff" },
      { kind: "toggle", id: "shadow", label: "Add a shadow so it reads on light photos", default: true },
      { kind: "toggle", id: "tile", label: "Repeat across the whole image", default: false },
      formatOption,
      qualityOption(92),
    ],
    related: ["blur-image-area", "photo-filters", "meme-generator"],
    icon: "Stamp",
  },
  {
    slug: "photo-filters",
    category: "image",
    title: "Photo Filters",
    short: "Brightness, contrast, saturation, blur and colour shifts",
    keywords: ["photo editor online", "image filters", "adjust brightness contrast", "black and white photo"],
    io: "file",
    engine: "image",
    op: "filterImage",
    accepts: IMAGES_IN,
    output: IMAGE_OUT,
    options: [
      { kind: "slider", id: "brightness", label: "Brightness", min: 0, max: 200, step: 1, default: 100, unit: "%" },
      { kind: "slider", id: "contrast", label: "Contrast", min: 0, max: 200, step: 1, default: 100, unit: "%" },
      { kind: "slider", id: "saturate", label: "Saturation", min: 0, max: 200, step: 1, default: 100, unit: "%" },
      { kind: "slider", id: "grayscale", label: "Black and white", min: 0, max: 100, step: 1, default: 0, unit: "%" },
      { kind: "slider", id: "sepia", label: "Sepia", min: 0, max: 100, step: 1, default: 0, unit: "%" },
      { kind: "slider", id: "hueRotate", label: "Hue shift", min: 0, max: 360, step: 5, default: 0, unit: "°" },
      { kind: "slider", id: "blur", label: "Blur", min: 0, max: 20, step: 1, default: 0, unit: "px" },
      { kind: "toggle", id: "invert", label: "Invert colours", default: false },
      formatOption,
      qualityOption(92),
    ],
    related: ["watermark-image", "rotate-image", "meme-generator"],
    icon: "SlidersHorizontal",
  },
  {
    slug: "blur-image-area",
    category: "image",
    title: "Blur Image Area",
    short: "Hide a face, a number plate or an address in a picture",
    keywords: ["blur image", "blur face in photo", "pixelate image", "hide information in picture"],
    io: "file",
    engine: "image",
    op: "blurRegion",
    accepts: IMAGES_IN,
    output: IMAGE_OUT,
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Method",
        choices: [
          { value: "pixelate", label: "Pixelate — detail is discarded" },
          { value: "solid", label: "Solid block — detail is discarded" },
          { value: "blur", label: "Blur — softer, and can sometimes be reversed" },
        ],
        default: "pixelate",
      },
      { kind: "slider", id: "strength", label: "Strength", min: 4, max: 60, step: 1, default: 20 },
      { kind: "color", id: "color", label: "Block colour", default: "#000000", showIf: { id: "mode", equals: "solid" } },
      {
        kind: "select",
        id: "unit",
        label: "Measure in",
        choices: [
          { value: "percent", label: "Percent of the image" },
          { value: "pixels", label: "Pixels" },
        ],
        default: "percent",
      },
      { kind: "number", id: "x", label: "From the left", default: 25, min: 0, max: 10000, step: 1 },
      { kind: "number", id: "y", label: "From the top", default: 25, min: 0, max: 10000, step: 1 },
      { kind: "number", id: "width", label: "Width", default: 50, min: 1, max: 12000, step: 1 },
      { kind: "number", id: "height", label: "Height", default: 50, min: 1, max: 12000, step: 1 },
      formatOption,
      qualityOption(92),
    ],
    related: ["strip-image-metadata", "crop-image", "watermark-image"],
    icon: "EyeOff",
  },
  {
    slug: "strip-image-metadata",
    category: "image",
    title: "Remove Image Metadata",
    short: "Strip EXIF, including the GPS location a photo was taken at",
    keywords: ["remove exif", "strip image metadata", "remove gps from photo", "clear photo metadata"],
    io: "file",
    engine: "image",
    op: "stripMetadata",
    accepts: IMAGES_IN,
    output: IMAGE_OUT,
    options: [formatOption, qualityOption(92)],
    related: ["blur-image-area", "compress-image", "convert-image"],
    icon: "ShieldOff",
  },
  {
    slug: "remove-image-background",
    category: "image",
    title: "Remove Background",
    short: "Cut out one flat background colour — logos, product shots, screenshots",
    keywords: ["remove background", "transparent background", "background remover", "make image transparent"],
    io: "file",
    engine: "image",
    op: "removeSolidBackground",
    accepts: IMAGES_IN,
    output: { ext: "png", mime: "image/png", cardinality: "per-file" },
    options: [
      {
        kind: "text",
        id: "color",
        label: "Background colour",
        default: "",
        placeholder: "Leave blank to sample the corners",
        help: "A hex value, or blank to detect it from the four corners.",
      },
      {
        kind: "slider",
        id: "tolerance",
        label: "Tolerance",
        min: 1,
        max: 60,
        step: 1,
        default: 12,
        unit: "%",
        help: "Higher removes more shades of that colour, and starts eating the subject.",
      },
      { kind: "toggle", id: "feather", label: "Soften the edges", default: true },
    ],
    related: ["convert-image", "crop-image", "favicon-generator"],
    icon: "Eraser",
  },
  {
    slug: "meme-generator",
    category: "image",
    title: "Meme Generator",
    short: "Top and bottom text in the classic style, wrapped to fit",
    keywords: ["meme generator", "meme maker", "add text to image", "caption picture"],
    io: "file",
    engine: "image",
    op: "memeGenerator",
    accepts: IMAGES_IN,
    output: { ext: "png", mime: "image/png", cardinality: "per-file" },
    options: [
      { kind: "text", id: "top", label: "Top text", default: "", placeholder: "One does not simply" },
      { kind: "text", id: "bottom", label: "Bottom text", default: "", placeholder: "walk into Mordor" },
      { kind: "slider", id: "size", label: "Text size", min: 4, max: 20, step: 1, default: 10, unit: "% of the height" },
      { kind: "toggle", id: "uppercase", label: "UPPERCASE", default: true },
    ],
    related: ["photo-filters", "watermark-image", "crop-image"],
    icon: "Laugh",
  },
  {
    slug: "favicon-generator",
    category: "image",
    title: "Favicon Generator",
    short: "Every icon size a site needs, plus a starter web manifest",
    keywords: ["favicon generator", "favicon from image", "app icon generator", "site icon maker"],
    io: "file",
    engine: "image",
    op: "faviconSet",
    accepts: { ...IMAGES_IN, multiple: false },
    output: { ext: "png", mime: "image/png", cardinality: "per-file" },
    options: [
      {
        kind: "text",
        id: "background",
        label: "Background colour",
        default: "",
        placeholder: "Leave blank to keep transparency",
        help: "iOS ignores transparency on home-screen icons, so a colour is worth setting.",
      },
    ],
    related: ["resize-image", "remove-image-background", "convert-image"],
    icon: "AppWindow",
  },
  {
    slug: "exif-viewer",
    category: "image",
    title: "EXIF Viewer",
    short: "See the camera, the settings and the location a photo carries",
    keywords: ["exif viewer", "check photo metadata", "see gps location in photo", "read exif data online"],
    io: "file",
    engine: "image",
    op: "exifView",
    accepts: { mime: ["image/jpeg", "image/tiff"], ext: ["jpg", "jpeg", "tif", "tiff"], multiple: true, maxMB: 60 },
    output: { ext: "txt", mime: "text/plain", cardinality: "per-file" },
    options: [
      {
        kind: "select",
        id: "format",
        label: "Report as",
        choices: [
          { value: "report", label: "Readable report" },
          { value: "json", label: "JSON" },
          { value: "csv", label: "CSV" },
        ],
        default: "report",
      },
      {
        kind: "toggle",
        id: "location",
        label: "Show GPS coordinates",
        default: true,
        help: "Switch off to confirm a photo carries a position without putting it on screen.",
      },
      { kind: "toggle", id: "unknown", label: "Count tags this tool doesn't name", default: true },
    ],
    related: ["strip-image-metadata", "reveal-hidden-text", "compress-image"],
    icon: "Info",
  },
  {
    slug: "color-palette-extractor",
    category: "image",
    title: "Color Palette Extractor",
    short: "Pull the dominant colours out of a picture as hex, RGB or CSS",
    keywords: ["color palette from image", "extract colors from photo", "image color picker online", "dominant color extractor"],
    io: "file",
    engine: "image",
    op: "colorPalette",
    accepts: {
      mime: ["image/jpeg", "image/png", "image/webp", "image/avif"],
      ext: ["jpg", "jpeg", "png", "webp", "avif", "gif", "bmp"],
      multiple: true,
      maxMB: 60,
    },
    output: { ext: "txt", mime: "text/plain", cardinality: "per-file" },
    options: [
      { kind: "number", id: "colors", label: "Colours to find", default: 6, min: 2, max: 16, step: 1 },
      {
        kind: "select",
        id: "format",
        label: "Also list as",
        choices: [
          { value: "hex", label: "Hex" },
          { value: "rgb", label: "RGB" },
          { value: "hsl", label: "HSL" },
          { value: "css", label: "CSS custom properties" },
        ],
        default: "hex",
      },
      { kind: "toggle", id: "swatch", label: "Also make a swatch image", default: true },
      {
        kind: "toggle",
        id: "ignoreFlat",
        label: "Ignore near-white and near-black",
        default: true,
        help: "Most photographs and every screenshot are mostly background. This keeps it out of the palette.",
      },
    ],
    related: ["color-converter", "css-gradient-generator", "convert-image"],
    icon: "Palette",
  },
  {
    slug: "image-to-ascii",
    category: "image",
    title: "Image to ASCII Art",
    short: "Redraw a picture in text characters",
    keywords: ["image to ascii", "ascii art generator from image", "photo to text art", "ascii converter online"],
    io: "file",
    engine: "image",
    op: "imageToAscii",
    accepts: {
      mime: ["image/jpeg", "image/png", "image/webp"],
      ext: ["jpg", "jpeg", "png", "webp", "gif", "bmp", "avif"],
      multiple: true,
      maxMB: 40,
    },
    output: { ext: "txt", mime: "text/plain", cardinality: "per-file" },
    options: [
      { kind: "number", id: "columns", label: "Width in characters", default: 100, min: 20, max: 400, step: 10 },
      {
        kind: "select",
        id: "charset",
        label: "Characters",
        choices: [
          { value: "classic", label: "Classic — @%#*+=-:." },
          { value: "detailed", label: "Detailed — 70 shades" },
          { value: "blocks", label: "Blocks — solid shading" },
          { value: "minimal", label: "Minimal — #+-." },
          { value: "binary", label: "Binary — 1 and 0" },
        ],
        default: "classic",
      },
      { kind: "toggle", id: "invert", label: "Invert for a dark background", default: false },
      {
        kind: "slider",
        id: "aspect",
        label: "Character shape",
        min: 0.3,
        max: 1.2,
        step: 0.05,
        default: 0.5,
        help: "Text characters are taller than they are wide. Lower values squash the picture vertically to compensate.",
      },
    ],
    related: ["convert-image", "resize-image", "meme-generator"],
    icon: "Type",
  },
];

/** Kept for the registry test, which checks single-image tools reject batches. */
export const SINGLE_IMAGE_TOOLS = new Set(["favicon-generator"]);
export { ONE_IMAGE_IN };
