import type { AcceptSpec, ToolSpec } from "../types";

/**
 * PDF tools. Everything here runs on pdf-lib (structure) or pdf.js (rendering
 * and text), both compiled to run in the browser — no file is ever uploaded.
 */

const PDF_IN: AcceptSpec = {
  mime: ["application/pdf"],
  ext: ["pdf"],
  multiple: false,
  maxMB: 100,
};

const PDFS_IN: AcceptSpec = { ...PDF_IN, multiple: true };

const PDF_OUT = { ext: "pdf", mime: "application/pdf", cardinality: "single" as const };

/** A page selection field, reused by half the tools here. */
const pageRangeOption = (label = "Pages", fallback = "all") =>
  ({
    kind: "pageRange" as const,
    id: "pages",
    label,
    default: fallback,
    placeholder: "all, or 1-3, 7, 12-",
    help: "Leave as “all”, or list pages and ranges: 1-3, 7, 12-",
  });

export const PDF_TOOLS: ToolSpec[] = [
  {
    slug: "merge-pdf",
    category: "pdf",
    title: "Merge PDF",
    short: "Combine several PDFs into one, in the order you choose",
    keywords: ["merge pdf", "combine pdf", "join pdf files", "pdf merger online free"],
    io: "file",
    engine: "pdf",
    op: "mergePdf",
    accepts: PDFS_IN,
    output: PDF_OUT,
    options: [
      { kind: "text", id: "filename", label: "Output name", default: "merged", placeholder: "merged" },
      {
        kind: "toggle",
        id: "outline",
        label: "Name the result after the first file",
        default: true,
      },
    ],
    related: ["split-pdf", "organize-pdf", "extract-pages", "compress-pdf"],
    icon: "Combine",
  },
  {
    slug: "split-pdf",
    category: "pdf",
    title: "Split PDF",
    short: "Cut one PDF into several — page by page, in blocks, or at set ranges",
    keywords: ["split pdf", "separate pdf pages", "divide pdf", "pdf splitter online"],
    io: "file",
    engine: "pdf",
    op: "splitPdf",
    accepts: PDF_IN,
    output: { ...PDF_OUT, cardinality: "per-file" },
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Split",
        choices: [
          { value: "each", label: "Every page into its own file" },
          { value: "every", label: "Into blocks of a fixed size" },
          { value: "ranges", label: "At ranges I specify" },
        ],
        default: "each",
      },
      {
        kind: "number",
        id: "size",
        label: "Pages per file",
        default: 10,
        min: 1,
        max: 500,
        step: 1,
        showIf: { id: "mode", equals: "every" },
      },
      {
        kind: "text",
        id: "ranges",
        label: "Ranges",
        default: "",
        placeholder: "1-3, 4-8, 9-",
        help: "Each range becomes its own file.",
        showIf: { id: "mode", equals: "ranges" },
      },
    ],
    related: ["merge-pdf", "extract-pages", "remove-pages", "organize-pdf"],
    icon: "Scissors",
  },
  {
    slug: "remove-pages",
    category: "pdf",
    title: "Remove Pages",
    short: "Delete the pages you don't want and keep the rest",
    keywords: ["remove pages from pdf", "delete pdf pages", "pdf page remover"],
    io: "file",
    engine: "pdf",
    op: "removePages",
    accepts: PDF_IN,
    output: PDF_OUT,
    options: [pageRangeOption("Pages to remove", "")],
    related: ["extract-pages", "split-pdf", "organize-pdf"],
    icon: "FileMinus",
  },
  {
    slug: "extract-pages",
    category: "pdf",
    title: "Extract Pages",
    short: "Pull selected pages out into a new PDF",
    keywords: ["extract pages from pdf", "pdf page extractor", "save pdf pages separately"],
    io: "file",
    engine: "pdf",
    op: "extractPages",
    accepts: PDF_IN,
    output: PDF_OUT,
    options: [
      pageRangeOption("Pages to keep", ""),
      {
        kind: "toggle",
        id: "separate",
        label: "One file per page",
        default: false,
        help: "Off puts every selected page into a single document.",
      },
    ],
    related: ["remove-pages", "split-pdf", "merge-pdf"],
    icon: "FilePlus",
  },
  {
    slug: "organize-pdf",
    category: "pdf",
    title: "Organize PDF",
    short: "Reorder, duplicate or reverse a document's pages",
    keywords: ["organize pdf", "reorder pdf pages", "rearrange pdf", "reverse pdf pages"],
    io: "file",
    engine: "pdf",
    op: "organizePdf",
    accepts: PDF_IN,
    output: PDF_OUT,
    options: [
      {
        kind: "text",
        id: "order",
        label: "New page order",
        default: "reverse",
        placeholder: "3, 1, 2, 4-6",
        help: "List the pages in the order you want them. “reverse” flips the whole document.",
      },
    ],
    related: ["merge-pdf", "extract-pages", "rotate-pdf", "remove-pages"],
    icon: "ArrowUpDown",
  },
  {
    slug: "rotate-pdf",
    category: "pdf",
    title: "Rotate PDF",
    short: "Turn pages the right way up, all of them or just some",
    keywords: ["rotate pdf", "turn pdf pages", "fix pdf orientation", "rotate pdf and save"],
    io: "file",
    engine: "pdf",
    op: "rotatePdf",
    accepts: PDF_IN,
    output: PDF_OUT,
    options: [
      {
        kind: "select",
        id: "angle",
        label: "Turn by",
        choices: [
          { value: "90", label: "90° clockwise" },
          { value: "180", label: "180°" },
          { value: "270", label: "90° anticlockwise" },
        ],
        default: "90",
      },
      pageRangeOption(),
    ],
    related: ["crop-pdf", "organize-pdf", "add-page-numbers"],
    icon: "RotateCw",
  },
  {
    slug: "compress-pdf",
    category: "pdf",
    title: "Compress PDF",
    short: "Make a PDF smaller — losslessly, or much smaller by rasterising",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf", "pdf compressor online free"],
    io: "file",
    engine: "pdf",
    op: "compressPdf",
    accepts: PDF_IN,
    output: PDF_OUT,
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Method",
        choices: [
          { value: "structure", label: "Lossless — rebuild the file, keep the text" },
          { value: "raster", label: "Rasterise — much smaller, destroys the text layer" },
        ],
        default: "structure",
        help: "Rasterising turns every page into a picture. It cannot be undone.",
      },
      {
        kind: "toggle",
        id: "stripMetadata",
        label: "Strip title, author and producer",
        default: true,
        showIf: { id: "mode", equals: "structure" },
      },
      {
        kind: "slider",
        id: "dpi",
        label: "Resolution",
        min: 72,
        max: 300,
        step: 6,
        default: 120,
        unit: " dpi",
        showIf: { id: "mode", equals: "raster" },
      },
      {
        kind: "slider",
        id: "quality",
        label: "JPEG quality",
        min: 30,
        max: 95,
        step: 5,
        default: 70,
        unit: "%",
        showIf: { id: "mode", equals: "raster" },
      },
    ],
    related: ["repair-pdf", "pdf-to-jpg", "merge-pdf"],
    icon: "Minimize2",
  },
  {
    slug: "repair-pdf",
    category: "pdf",
    title: "Repair PDF",
    short: "Rebuild a damaged PDF and recover the pages that survived",
    keywords: ["repair pdf", "fix corrupted pdf", "pdf recovery", "damaged pdf file"],
    io: "file",
    engine: "pdf",
    op: "repairPdf",
    accepts: PDF_IN,
    output: PDF_OUT,
    options: [],
    related: ["compress-pdf", "merge-pdf", "split-pdf"],
    icon: "Wrench",
  },
  {
    slug: "unlock-pdf",
    category: "pdf",
    title: "Unlock PDF",
    short: "Remove a PDF's password and encryption, with the password that opens it",
    keywords: [
      "unlock pdf",
      "remove password from pdf",
      "decrypt pdf",
      "remove pdf restrictions",
      "pdf password remover online free",
    ],
    io: "file",
    engine: "pdf",
    op: "unlockPdf",
    accepts: PDFS_IN,
    output: { ...PDF_OUT, cardinality: "per-file" as const },
    options: [
      {
        kind: "text",
        id: "password",
        label: "Password that opens the file",
        default: "",
        secret: true,
        placeholder: "Leave empty if the file opens without one",
        help: "Needed only for files that ask for a password when you open them. A file that opens but refuses to print or copy needs nothing here.",
      },
    ],
    related: ["protect-pdf", "compress-pdf", "merge-pdf", "repair-pdf"],
    icon: "LockOpen",
  },
  {
    slug: "protect-pdf",
    category: "pdf",
    title: "Protect PDF",
    short: "Lock a PDF with a password and AES-256 encryption",
    keywords: [
      "protect pdf",
      "password protect pdf",
      "encrypt pdf",
      "add password to pdf",
      "lock pdf file online free",
    ],
    io: "file",
    engine: "pdf",
    op: "protectPdf",
    accepts: PDFS_IN,
    output: { ...PDF_OUT, cardinality: "per-file" as const },
    options: [
      {
        kind: "text",
        id: "password",
        label: "Password to open the file",
        default: "",
        secret: true,
        placeholder: "Choose something you will not lose",
        help: "This is the one that matters. It cannot be recovered from the file — not by you, not by us.",
      },
      {
        kind: "text",
        id: "ownerPassword",
        label: "Separate permissions password",
        default: "",
        secret: true,
        placeholder: "Optional",
        help: "Set this only if you want the permissions below to be changeable with a different password. Left empty, the opening password does both jobs.",
      },
      { kind: "toggle", id: "allowPrinting", label: "Allow printing", default: true },
      { kind: "toggle", id: "allowCopying", label: "Allow copying text", default: true },
      { kind: "toggle", id: "allowEditing", label: "Allow editing the pages", default: false },
    ],
    related: ["unlock-pdf", "redact-pdf", "sign-pdf", "add-watermark"],
    icon: "Lock",
  },
  {
    slug: "jpg-to-pdf",
    category: "pdf",
    title: "JPG to PDF",
    short: "Turn photos and screenshots into a single PDF",
    keywords: ["jpg to pdf", "image to pdf", "png to pdf", "convert photos to pdf"],
    io: "file",
    engine: "pdf",
    op: "jpgToPdf",
    accepts: {
      mime: ["image/jpeg", "image/png"],
      ext: ["jpg", "jpeg", "png"],
      multiple: true,
      maxMB: 100,
    },
    output: PDF_OUT,
    options: [
      {
        kind: "select",
        id: "pageSize",
        label: "Page size",
        choices: [
          { value: "a4", label: "A4" },
          { value: "letter", label: "US Letter" },
          { value: "legal", label: "US Legal" },
          { value: "a3", label: "A3" },
          { value: "a5", label: "A5" },
          { value: "fit", label: "Fit each page to its image" },
        ],
        default: "a4",
      },
      {
        kind: "select",
        id: "orientation",
        label: "Orientation",
        choices: [
          { value: "auto", label: "Match each image" },
          { value: "portrait", label: "Portrait" },
          { value: "landscape", label: "Landscape" },
        ],
        default: "auto",
        showIf: { id: "pageSize", equals: "a4" },
      },
      {
        kind: "measure",
        id: "margin",
        label: "Margin",
        quantity: "length",
        units: ["mm", "cm", "in"],
        default: 8,
        min: 0,
        max: 100,
        step: 1,
        help: "White space left around each image.",
      },
      { kind: "toggle", id: "titleFromFirst", label: "Name the PDF after the first image", default: true },
    ],
    related: ["pdf-to-jpg", "merge-pdf", "compress-pdf"],
    icon: "Images",
  },
  {
    slug: "pdf-to-jpg",
    category: "pdf",
    title: "PDF to JPG",
    short: "Save every page as an image, at the resolution you pick",
    keywords: ["pdf to jpg", "pdf to image", "pdf to png", "convert pdf pages to pictures"],
    io: "file",
    engine: "pdf",
    op: "pdfToJpg",
    accepts: PDF_IN,
    output: { ext: "jpg", mime: "image/jpeg", cardinality: "per-file" },
    options: [
      {
        kind: "select",
        id: "format",
        label: "Format",
        choices: [
          { value: "jpeg", label: "JPEG — smaller" },
          { value: "png", label: "PNG — lossless, larger" },
        ],
        default: "jpeg",
      },
      {
        kind: "slider",
        id: "dpi",
        label: "Resolution",
        min: 72,
        max: 400,
        step: 12,
        default: 150,
        unit: " dpi",
        help: "150 is fine on screen. 300 is print quality and roughly four times the size.",
      },
      {
        kind: "slider",
        id: "quality",
        label: "JPEG quality",
        min: 40,
        max: 100,
        step: 5,
        default: 85,
        unit: "%",
        showIf: { id: "format", equals: "jpeg" },
      },
      pageRangeOption(),
    ],
    related: ["jpg-to-pdf", "compress-pdf", "pdf-to-markdown"],
    icon: "Image",
  },
  {
    slug: "add-page-numbers",
    category: "pdf",
    title: "Add Page Numbers",
    short: "Stamp numbers onto a PDF, wherever you want them",
    keywords: ["add page numbers to pdf", "number pdf pages", "pdf page numbering"],
    io: "file",
    engine: "pdf",
    op: "addPageNumbers",
    accepts: PDF_IN,
    output: PDF_OUT,
    options: [
      {
        kind: "select",
        id: "position",
        label: "Position",
        choices: [
          { value: "bottom-center", label: "Bottom centre" },
          { value: "bottom-right", label: "Bottom right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "top-center", label: "Top centre" },
          { value: "top-right", label: "Top right" },
          { value: "top-left", label: "Top left" },
        ],
        default: "bottom-center",
      },
      {
        kind: "select",
        id: "format",
        label: "Format",
        choices: [
          { value: "n", label: "1" },
          { value: "page-n", label: "Page 1" },
          { value: "n-of-m", label: "1 of 20" },
          { value: "dashes", label: "— 1 —" },
        ],
        default: "n",
      },
      { kind: "number", id: "startAt", label: "Start numbering at", default: 1, min: 0, max: 9999, step: 1 },
      { kind: "slider", id: "size", label: "Text size", min: 6, max: 24, step: 1, default: 10, unit: "pt" },
      { kind: "slider", id: "margin", label: "Margin", min: 8, max: 96, step: 2, default: 28, unit: "pt" },
      { kind: "color", id: "color", label: "Colour", default: "#333333" },
      pageRangeOption(),
    ],
    related: ["add-watermark", "crop-pdf", "rotate-pdf"],
    icon: "Hash",
  },
  {
    slug: "add-watermark",
    category: "pdf",
    title: "Add Watermark",
    short: "Stamp text across a document — once per page or tiled",
    keywords: ["add watermark to pdf", "pdf watermark", "draft stamp pdf", "confidential watermark"],
    io: "file",
    engine: "pdf",
    op: "addWatermark",
    accepts: PDF_IN,
    output: PDF_OUT,
    options: [
      { kind: "text", id: "text", label: "Watermark text", default: "DRAFT", placeholder: "CONFIDENTIAL" },
      { kind: "slider", id: "size", label: "Text size", min: 8, max: 144, step: 2, default: 48, unit: "pt" },
      { kind: "slider", id: "opacity", label: "Opacity", min: 2, max: 100, step: 1, default: 15, unit: "%" },
      { kind: "slider", id: "angle", label: "Angle", min: -90, max: 90, step: 5, default: 45, unit: "°" },
      { kind: "color", id: "color", label: "Colour", default: "#888888" },
      { kind: "toggle", id: "tile", label: "Repeat across the whole page", default: false },
      pageRangeOption(),
    ],
    related: ["add-page-numbers", "sign-pdf", "redact-pdf"],
    icon: "Stamp",
  },
  {
    slug: "crop-pdf",
    category: "pdf",
    title: "Crop PDF",
    short: "Trim the margins off every page",
    keywords: ["crop pdf", "trim pdf margins", "resize pdf page", "cut pdf edges"],
    io: "file",
    engine: "pdf",
    op: "cropPdf",
    accepts: PDF_IN,
    output: PDF_OUT,
    options: [
      {
        kind: "select",
        id: "unit",
        label: "Measure in",
        /*
          One unit governs all four trims, because nobody crops the top in
          millimetres and the left in percent. Percent has to stay a choice
          rather than a length: it is relative to each page's own size, which is
          the only sane behaviour on a document of mixed page sizes.
        */
        choices: [
          { value: "percent", label: "Percent of each page" },
          { value: "mm", label: "Millimetres" },
          { value: "cm", label: "Centimetres" },
          { value: "in", label: "Inches" },
          { value: "points", label: "Points (72 per inch)" },
        ],
        default: "percent",
      },
      { kind: "number", id: "top", label: "Trim from top", default: 5, min: 0, max: 500, step: 0.5 },
      { kind: "number", id: "bottom", label: "Trim from bottom", default: 5, min: 0, max: 500, step: 0.5 },
      { kind: "number", id: "left", label: "Trim from left", default: 5, min: 0, max: 500, step: 0.5 },
      { kind: "number", id: "right", label: "Trim from right", default: 5, min: 0, max: 500, step: 0.5 },
      pageRangeOption(),
    ],
    related: ["rotate-pdf", "add-page-numbers", "pdf-to-jpg"],
    icon: "Crop",
  },
  {
    slug: "sign-pdf",
    category: "pdf",
    title: "Sign PDF",
    short: "Place an image of your signature on a page",
    keywords: ["sign pdf", "add signature to pdf", "pdf signature online", "esign pdf free"],
    io: "file",
    engine: "pdf",
    op: "signPdf",
    accepts: {
      mime: ["application/pdf", "image/png", "image/jpeg"],
      ext: ["pdf", "png", "jpg", "jpeg"],
      multiple: true,
      maxMB: 100,
    },
    output: PDF_OUT,
    options: [
      {
        kind: "select",
        id: "page",
        label: "Sign the",
        choices: [
          { value: "last", label: "Last page" },
          { value: "first", label: "First page" },
        ],
        default: "last",
      },
      {
        kind: "select",
        id: "position",
        label: "Position",
        choices: [
          { value: "bottom-right", label: "Bottom right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "bottom-center", label: "Bottom centre" },
        ],
        default: "bottom-right",
      },
      { kind: "slider", id: "width", label: "Signature width", min: 5, max: 80, step: 1, default: 25, unit: "% of page" },
      { kind: "slider", id: "margin", label: "Margin", min: 8, max: 120, step: 4, default: 40, unit: "pt" },
      { kind: "toggle", id: "dateStamp", label: "Add today's date underneath", default: false },
    ],
    related: ["add-watermark", "redact-pdf", "compare-pdf"],
    icon: "PenTool",
  },
  {
    slug: "redact-pdf",
    category: "pdf",
    title: "Redact PDF",
    short: "Permanently remove words from a document, not just cover them",
    keywords: ["redact pdf", "black out pdf text", "remove sensitive information pdf", "pdf redaction"],
    io: "file",
    engine: "pdf",
    op: "redactPdf",
    accepts: PDF_IN,
    output: PDF_OUT,
    options: [
      {
        kind: "textarea",
        id: "terms",
        label: "Words to remove",
        default: "",
        rows: 4,
        placeholder: "One word or phrase per line",
        help: "Every occurrence anywhere in the document is found and removed.",
      },
      { kind: "toggle", id: "caseSensitive", label: "Match case", default: false },
      {
        kind: "slider",
        id: "dpi",
        label: "Output resolution",
        min: 100,
        max: 300,
        step: 10,
        default: 150,
        unit: " dpi",
        help: "Pages are rebuilt as images so the text cannot be recovered.",
      },
    ],
    related: ["add-watermark", "compress-pdf", "sign-pdf"],
    icon: "EyeOff",
  },
  {
    slug: "compare-pdf",
    category: "pdf",
    title: "Compare PDF",
    short: "See what changed between two versions of a document",
    keywords: ["compare pdf", "pdf diff", "find differences between pdfs", "pdf comparison tool"],
    io: "file",
    engine: "pdf",
    op: "comparePdf",
    accepts: PDFS_IN,
    output: { ext: "txt", mime: "text/plain", cardinality: "single" },
    options: [
      { kind: "toggle", id: "ignoreWhitespace", label: "Ignore spacing differences", default: true },
      { kind: "toggle", id: "ignoreCase", label: "Ignore case", default: false },
    ],
    related: ["text-diff", "pdf-to-markdown", "merge-pdf"],
    icon: "GitCompare",
  },
  {
    slug: "pdf-to-markdown",
    category: "pdf",
    title: "PDF to Markdown",
    short: "Pull the text out as Markdown, with headings and lists detected",
    keywords: ["pdf to markdown", "pdf to text", "extract text from pdf", "pdf to md converter"],
    io: "file",
    engine: "pdf",
    op: "pdfToMarkdown",
    accepts: PDF_IN,
    output: { ext: "md", mime: "text/markdown", cardinality: "single" },
    options: [
      {
        kind: "toggle",
        id: "headings",
        label: "Detect headings from text size",
        default: true,
        help: "Lines noticeably larger than the body text become Markdown headings.",
      },
      { kind: "toggle", id: "pageBreaks", label: "Mark page breaks with a rule", default: true },
    ],
    related: ["compare-pdf", "markdown-to-html", "pdf-to-jpg"],
    icon: "FileType",
  },
];
