import type { ToolSpec } from "../types";

/**
 * Security & privacy tools that need no WASM. Hashing uses the browser's own
 * WebCrypto where the algorithm is supported; MD5 and CRC32 are implemented
 * locally because WebCrypto deliberately omits them.
 */
export const SECURITY_TOOLS: ToolSpec[] = [
  {
    slug: "hash-generator",
    category: "security",
    title: "Hash Generator",
    short: "SHA-256, SHA-1, SHA-512, MD5 and CRC32 from any text",
    keywords: ["hash generator", "sha256 generator", "md5 generator online", "checksum generator"],
    io: "text",
    engine: "pure",
    op: "hashText",
    options: [
      {
        kind: "select",
        id: "algorithm",
        label: "Algorithm",
        choices: [
          { value: "all", label: "Show them all" },
          { value: "SHA-256", label: "SHA-256" },
          { value: "SHA-384", label: "SHA-384" },
          { value: "SHA-512", label: "SHA-512" },
          { value: "SHA-1", label: "SHA-1 — legacy, do not use for security" },
          { value: "MD5", label: "MD5 — legacy, do not use for security" },
          { value: "CRC32", label: "CRC32 — integrity only" },
        ],
        default: "all",
      },
      {
        kind: "select",
        id: "encoding",
        label: "Output as",
        choices: [
          { value: "hex", label: "Hexadecimal" },
          { value: "base64", label: "Base64" },
        ],
        default: "hex",
      },
      { kind: "toggle", id: "uppercase", label: "Uppercase hex", default: false },
    ],
    related: ["hmac-generator", "password-generator", "base64-encode"],
    icon: "Hash",
  },
  {
    slug: "hmac-generator",
    category: "security",
    title: "HMAC Generator",
    short: "Sign a message with a secret key using HMAC-SHA",
    keywords: ["hmac generator", "hmac sha256", "hmac online", "message authentication code"],
    io: "text",
    engine: "pure",
    op: "hmacText",
    options: [
      { kind: "text", id: "key", label: "Secret key", default: "", placeholder: "your signing key" },
      {
        kind: "select",
        id: "algorithm",
        label: "Algorithm",
        choices: [
          { value: "SHA-256", label: "HMAC-SHA-256" },
          { value: "SHA-384", label: "HMAC-SHA-384" },
          { value: "SHA-512", label: "HMAC-SHA-512" },
          { value: "SHA-1", label: "HMAC-SHA-1 — legacy" },
        ],
        default: "SHA-256",
      },
      {
        kind: "select",
        id: "encoding",
        label: "Output as",
        choices: [
          { value: "hex", label: "Hexadecimal" },
          { value: "base64", label: "Base64" },
        ],
        default: "hex",
      },
    ],
    related: ["hash-generator", "jwt-decoder", "base64-encode"],
    icon: "KeySquare",
  },
  {
    slug: "password-generator",
    category: "security",
    title: "Password Generator",
    short: "Strong random passwords from your browser's crypto source",
    keywords: ["password generator", "strong password generator", "random password", "secure password maker"],
    io: "form",
    engine: "pure",
    op: "passwordGenerate",
    options: [
      { kind: "slider", id: "length", label: "Length", min: 6, max: 128, step: 1, default: 20 },
      { kind: "number", id: "count", label: "How many", default: 5, min: 1, max: 100, step: 1 },
      { kind: "toggle", id: "lower", label: "Lowercase a–z", default: true },
      { kind: "toggle", id: "upper", label: "Uppercase A–Z", default: true },
      { kind: "toggle", id: "digits", label: "Digits 0–9", default: true },
      { kind: "toggle", id: "symbols", label: "Symbols", default: true },
      {
        kind: "toggle",
        id: "excludeAmbiguous",
        label: "Avoid look-alike characters",
        default: false,
        help: "Drops 0, O, 1, l, I and | so the password survives being read aloud or copied by hand.",
      },
    ],
    related: ["password-strength-checker", "random-string-generator", "uuid-generator"],
    icon: "KeyRound",
  },
  {
    slug: "password-strength-checker",
    category: "security",
    title: "Password Strength Checker",
    short: "See how long a password would take to crack — offline",
    keywords: ["password strength checker", "how strong is my password", "password entropy calculator"],
    io: "text",
    engine: "pure",
    op: "passwordStrength",
    options: [
      {
        kind: "select",
        id: "attacker",
        label: "Assume the attacker can try",
        choices: [
          { value: "1e4", label: "10 thousand guesses a second — online, rate limited" },
          { value: "1e10", label: "10 billion a second — offline, fast hash" },
          { value: "1e12", label: "1 trillion a second — offline, GPU cluster" },
        ],
        default: "1e10",
      },
    ],
    related: ["password-generator", "hash-generator"],
    icon: "ShieldAlert",
  },
  {
    slug: "random-string-generator",
    category: "security",
    title: "Random String Generator",
    short: "Random tokens, keys and IDs in the alphabet you choose",
    keywords: ["random string generator", "random token generator", "api key generator", "random characters"],
    io: "form",
    engine: "pure",
    op: "randomString",
    options: [
      { kind: "slider", id: "length", label: "Length", min: 1, max: 256, step: 1, default: 32 },
      { kind: "number", id: "count", label: "How many", default: 5, min: 1, max: 200, step: 1 },
      {
        kind: "select",
        id: "alphabet",
        label: "Alphabet",
        choices: [
          { value: "alnum", label: "Letters and digits" },
          { value: "hex", label: "Hexadecimal" },
          { value: "base58", label: "Base58 — no look-alikes" },
          { value: "lower", label: "Lowercase letters" },
          { value: "digits", label: "Digits only" },
          { value: "custom", label: "Custom set" },
        ],
        default: "alnum",
      },
      { kind: "text", id: "custom", label: "Characters to draw from", default: "ABCDEF0123456789", showIf: { id: "alphabet", equals: "custom" } },
      { kind: "text", id: "prefix", label: "Prefix", default: "", placeholder: "sk_live_" },
    ],
    related: ["password-generator", "uuid-generator", "hash-generator"],
    icon: "Dices",
  },
  {
    slug: "qr-code-generator",
    category: "security",
    title: "QR Code Generator",
    short: "Make a QR code for a link, Wi-Fi network, contact or text",
    keywords: ["qr code generator", "free qr code maker", "wifi qr code", "vcard qr code"],
    io: "form",
    engine: "pure",
    op: "qrGenerate",
    options: [
      {
        kind: "select",
        id: "kind",
        label: "Encode",
        choices: [
          { value: "text", label: "Link or plain text" },
          { value: "wifi", label: "Wi-Fi network" },
          { value: "vcard", label: "Contact card" },
          { value: "sms", label: "SMS" },
          { value: "email", label: "Email" },
        ],
        default: "text",
      },
      { kind: "textarea", id: "content", label: "Content", default: "https://tools.msrx.co.in", rows: 3, showIf: { id: "kind", equals: "text" } },
      { kind: "text", id: "ssid", label: "Network name", default: "", showIf: { id: "kind", equals: "wifi" } },
      { kind: "text", id: "wifiPassword", label: "Network password", default: "", showIf: { id: "kind", equals: "wifi" } },
      {
        kind: "select",
        id: "wifiSecurity",
        label: "Security",
        choices: [
          { value: "WPA", label: "WPA / WPA2 / WPA3" },
          { value: "WEP", label: "WEP" },
          { value: "nopass", label: "Open network" },
        ],
        default: "WPA",
        showIf: { id: "kind", equals: "wifi" },
      },
      { kind: "text", id: "name", label: "Full name", default: "", showIf: { id: "kind", equals: "vcard" } },
      { kind: "text", id: "phone", label: "Phone", default: "", showIf: { id: "kind", equals: "vcard" } },
      { kind: "text", id: "email", label: "Email", default: "", showIf: { id: "kind", equals: "vcard" } },
      { kind: "text", id: "org", label: "Organisation", default: "", showIf: { id: "kind", equals: "vcard" } },
      { kind: "text", id: "smsNumber", label: "Number", default: "", showIf: { id: "kind", equals: "sms" } },
      { kind: "text", id: "smsBody", label: "Message", default: "", showIf: { id: "kind", equals: "sms" } },
      { kind: "text", id: "emailTo", label: "To", default: "", showIf: { id: "kind", equals: "email" } },
      { kind: "text", id: "emailSubject", label: "Subject", default: "", showIf: { id: "kind", equals: "email" } },
      {
        kind: "select",
        id: "ecc",
        label: "Error correction",
        choices: [
          { value: "L", label: "Low — smallest code" },
          { value: "M", label: "Medium" },
          { value: "Q", label: "Quartile" },
          { value: "H", label: "High — survives damage and logos" },
        ],
        default: "M",
      },
      { kind: "slider", id: "size", label: "Size", min: 128, max: 2048, step: 32, default: 512, unit: "px" },
      { kind: "slider", id: "margin", label: "Quiet zone", min: 0, max: 8, step: 1, default: 2, unit: " modules" },
      { kind: "color", id: "dark", label: "Foreground", default: "#0f172a" },
      { kind: "color", id: "light", label: "Background", default: "#ffffff" },
    ],
    customPanel: true,
    related: ["password-generator", "slug-generator", "url-encode"],
    icon: "QrCode",
  },
];
