import type { ToolSpec } from "../types";

/**
 * Security & privacy tools that need no WASM. Hashing uses the browser's own
 * WebCrypto where the algorithm is supported; MD5 and CRC32 are implemented
 * locally because WebCrypto deliberately omits them.
 */
export const SECURITY_TOOLS: ToolSpec[] = [
  {
    slug: "hash-generator",
    category: "security",
    title: "Hash Generator",
    short: "SHA-256, SHA-1, SHA-512, MD5 and CRC32 from any text",
    keywords: ["hash generator", "sha256 generator", "md5 generator online", "checksum generator"],
    io: "text",
    engine: "pure",
    op: "hashText",
    options: [
      {
        kind: "select",
        id: "algorithm",
        label: "Algorithm",
        choices: [
          { value: "all", label: "Show them all" },
          { value: "SHA-256", label: "SHA-256" },
          { value: "SHA-384", label: "SHA-384" },
          { value: "SHA-512", label: "SHA-512" },
          { value: "SHA-1", label: "SHA-1 — legacy, do not use for security" },
          { value: "MD5", label: "MD5 — legacy, do not use for security" },
          { value: "CRC32", label: "CRC32 — integrity only" },
        ],
        default: "all",
      },
      {
        kind: "select",
        id: "encoding",
        label: "Output as",
        choices: [
          { value: "hex", label: "Hexadecimal" },
          { value: "base64", label: "Base64" },
        ],
        default: "hex",
      },
      { kind: "toggle", id: "uppercase", label: "Uppercase hex", default: false },
    ],
    related: ["hmac-generator", "password-generator", "base64-encode"],
    icon: "Hash",
  },
  {
    slug: "hmac-generator",
    category: "security",
    title: "HMAC Generator",
    short: "Sign a message with a secret key using HMAC-SHA",
    keywords: ["hmac generator", "hmac sha256", "hmac online", "message authentication code"],
    io: "text",
    engine: "pure",
    op: "hmacText",
    options: [
      { kind: "text", id: "key", label: "Secret key", default: "", secret: true, placeholder: "your signing key" },
      {
        kind: "select",
        id: "algorithm",
        label: "Algorithm",
        choices: [
          { value: "SHA-256", label: "HMAC-SHA-256" },
          { value: "SHA-384", label: "HMAC-SHA-384" },
          { value: "SHA-512", label: "HMAC-SHA-512" },
          { value: "SHA-1", label: "HMAC-SHA-1 — legacy" },
        ],
        default: "SHA-256",
      },
      {
        kind: "select",
        id: "encoding",
        label: "Output as",
        choices: [
          { value: "hex", label: "Hexadecimal" },
          { value: "base64", label: "Base64" },
        ],
        default: "hex",
      },
    ],
    related: ["hash-generator", "jwt-decoder", "base64-encode"],
    icon: "KeySquare",
  },
  {
    slug: "password-generator",
    category: "security",
    title: "Password Generator",
    short: "Strong random passwords from your browser's crypto source",
    keywords: ["password generator", "strong password generator", "random password", "secure password maker"],
    io: "form",
    engine: "pure",
    op: "passwordGenerate",
    options: [
      { kind: "slider", id: "length", label: "Length", min: 6, max: 128, step: 1, default: 20 },
      { kind: "number", id: "count", label: "How many", default: 5, min: 1, max: 100, step: 1 },
      { kind: "toggle", id: "lower", label: "Lowercase a–z", default: true },
      { kind: "toggle", id: "upper", label: "Uppercase A–Z", default: true },
      { kind: "toggle", id: "digits", label: "Digits 0–9", default: true },
      { kind: "toggle", id: "symbols", label: "Symbols", default: true },
      {
        kind: "toggle",
        id: "excludeAmbiguous",
        label: "Avoid look-alike characters",
        default: false,
        help: "Drops 0, O, 1, l, I and | so the password survives being read aloud or copied by hand.",
      },
    ],
    related: ["password-strength-checker", "random-string-generator", "uuid-generator"],
    icon: "KeyRound",
  },
  {
    slug: "password-strength-checker",
    category: "security",
    title: "Password Strength Checker",
    short: "See how long a password would take to crack — offline",
    keywords: ["password strength checker", "how strong is my password", "password entropy calculator"],
    io: "text",
    engine: "pure",
    op: "passwordStrength",
    options: [
      {
        kind: "select",
        id: "attacker",
        label: "Assume the attacker can try",
        choices: [
          { value: "1e4", label: "10 thousand guesses a second — online, rate limited" },
          { value: "1e10", label: "10 billion a second — offline, fast hash" },
          { value: "1e12", label: "1 trillion a second — offline, GPU cluster" },
        ],
        default: "1e10",
      },
    ],
    related: ["password-generator", "hash-generator"],
    icon: "ShieldAlert",
  },
  {
    slug: "random-string-generator",
    category: "security",
    title: "Random String Generator",
    short: "Random tokens, keys and IDs in the alphabet you choose",
    keywords: ["random string generator", "random token generator", "api key generator", "random characters"],
    io: "form",
    engine: "pure",
    op: "randomString",
    options: [
      { kind: "slider", id: "length", label: "Length", min: 1, max: 256, step: 1, default: 32 },
      { kind: "number", id: "count", label: "How many", default: 5, min: 1, max: 200, step: 1 },
      {
        kind: "select",
        id: "alphabet",
        label: "Alphabet",
        choices: [
          { value: "alnum", label: "Letters and digits" },
          { value: "hex", label: "Hexadecimal" },
          { value: "base58", label: "Base58 — no look-alikes" },
          { value: "lower", label: "Lowercase letters" },
          { value: "digits", label: "Digits only" },
          { value: "custom", label: "Custom set" },
        ],
        default: "alnum",
      },
      { kind: "text", id: "custom", label: "Characters to draw from", default: "ABCDEF0123456789", showIf: { id: "alphabet", equals: "custom" } },
      { kind: "text", id: "prefix", label: "Prefix", default: "", placeholder: "sk_live_" },
    ],
    related: ["password-generator", "uuid-generator", "hash-generator"],
    icon: "Dices",
  },
  {
    slug: "qr-code-generator",
    category: "security",
    title: "QR Code Generator",
    short: "Make a QR code for a link, Wi-Fi network, contact or text",
    keywords: ["qr code generator", "free qr code maker", "wifi qr code", "vcard qr code"],
    io: "form",
    engine: "pure",
    op: "qrGenerate",
    options: [
      {
        kind: "select",
        id: "kind",
        label: "Encode",
        choices: [
          { value: "text", label: "Link or plain text" },
          { value: "wifi", label: "Wi-Fi network" },
          { value: "vcard", label: "Contact card" },
          { value: "sms", label: "SMS" },
          { value: "email", label: "Email" },
        ],
        default: "text",
      },
      { kind: "textarea", id: "content", label: "Content", default: "https://tools.msrx.co.in", rows: 3, showIf: { id: "kind", equals: "text" } },
      { kind: "text", id: "ssid", label: "Network name", default: "", showIf: { id: "kind", equals: "wifi" } },
      { kind: "text", id: "wifiPassword", label: "Network password", default: "", showIf: { id: "kind", equals: "wifi" } },
      {
        kind: "select",
        id: "wifiSecurity",
        label: "Security",
        choices: [
          { value: "WPA", label: "WPA / WPA2 / WPA3" },
          { value: "WEP", label: "WEP" },
          { value: "nopass", label: "Open network" },
        ],
        default: "WPA",
        showIf: { id: "kind", equals: "wifi" },
      },
      { kind: "text", id: "name", label: "Full name", default: "", showIf: { id: "kind", equals: "vcard" } },
      { kind: "text", id: "phone", label: "Phone", default: "", showIf: { id: "kind", equals: "vcard" } },
      { kind: "text", id: "email", label: "Email", default: "", showIf: { id: "kind", equals: "vcard" } },
      { kind: "text", id: "org", label: "Organisation", default: "", showIf: { id: "kind", equals: "vcard" } },
      { kind: "text", id: "smsNumber", label: "Number", default: "", showIf: { id: "kind", equals: "sms" } },
      { kind: "text", id: "smsBody", label: "Message", default: "", showIf: { id: "kind", equals: "sms" } },
      { kind: "text", id: "emailTo", label: "To", default: "", showIf: { id: "kind", equals: "email" } },
      { kind: "text", id: "emailSubject", label: "Subject", default: "", showIf: { id: "kind", equals: "email" } },
      {
        kind: "select",
        id: "ecc",
        label: "Error correction",
        choices: [
          { value: "L", label: "Low — smallest code" },
          { value: "M", label: "Medium" },
          { value: "Q", label: "Quartile" },
          { value: "H", label: "High — survives damage and logos" },
        ],
        default: "M",
      },
      { kind: "slider", id: "size", label: "Size", min: 128, max: 2048, step: 32, default: 512, unit: "px" },
      { kind: "slider", id: "margin", label: "Quiet zone", min: 0, max: 8, step: 1, default: 2, unit: " modules" },
      { kind: "color", id: "dark", label: "Foreground", default: "#0f172a" },
      { kind: "color", id: "light", label: "Background", default: "#ffffff" },
    ],
    customPanel: true,
    related: ["password-generator", "slug-generator", "url-encode"],
    icon: "QrCode",
  },
  {
    slug: "encrypt-text",
    category: "security",
    title: "Encrypt Text",
    short: "AES-256-GCM with a password, entirely in this tab",
    keywords: ["encrypt text online", "aes encryption online", "password encrypt message", "text encryption tool"],
    io: "text",
    engine: "pure",
    op: "encryptText",
    options: [
      { kind: "text", id: "password", label: "Password", default: "", secret: true, placeholder: "The only thing that can open it" },
      {
        kind: "number",
        id: "iterations",
        label: "PBKDF2 rounds",
        default: 600000,
        min: 100000,
        max: 5000000,
        step: 50000,
        help: "More rounds make a guessing attack slower and this page slower by the same amount. 600,000 is the current OWASP floor.",
      },
      {
        kind: "select",
        id: "kdfHash",
        label: "Key derivation hash",
        choices: [
          { value: "SHA-256", label: "SHA-256" },
          { value: "SHA-512", label: "SHA-512" },
        ],
        default: "SHA-256",
      },
      { kind: "toggle", id: "wrap", label: "Wrap at 64 characters", default: true },
    ],
    related: ["decrypt-text", "encrypt-file", "hash-generator", "password-generator"],
    icon: "Lock",
  },
  {
    slug: "decrypt-text",
    category: "security",
    title: "Decrypt Text",
    short: "Open text encrypted here, with the password it was sealed with",
    keywords: ["decrypt text online", "aes decrypt online", "decrypt message with password", "text decryption tool"],
    io: "text",
    engine: "pure",
    op: "decryptText",
    options: [
      { kind: "text", id: "password", label: "Password", default: "", secret: true, placeholder: "The password it was sealed with" },
      {
        kind: "number",
        id: "iterations",
        label: "PBKDF2 rounds",
        default: 600000,
        min: 100000,
        max: 5000000,
        step: 50000,
        help: "Shown for reference only — the real value travels inside the message and is used instead of this one.",
      },
      {
        kind: "select",
        id: "kdfHash",
        label: "Key derivation hash",
        choices: [
          { value: "SHA-256", label: "SHA-256" },
          { value: "SHA-512", label: "SHA-512" },
        ],
        default: "SHA-256",
      },
      { kind: "toggle", id: "trim", label: "Trim surrounding blank lines", default: false },
    ],
    related: ["encrypt-text", "decrypt-file", "hash-generator"],
    icon: "LockOpen",
  },
  {
    slug: "encrypt-file",
    category: "security",
    title: "Encrypt File",
    short: "Password-protect any file with AES-256-GCM before you send it",
    keywords: ["encrypt file online", "password protect file", "aes file encryption", "encrypt pdf zip locally"],
    io: "file",
    engine: "crypto",
    op: "encryptFile",
    accepts: { mime: [], ext: [], multiple: true, maxMB: 512 },
    output: { ext: "enc", mime: "application/octet-stream", cardinality: "per-file" },
    options: [
      { kind: "text", id: "password", label: "Password", default: "", secret: true, placeholder: "Long, and stored in a password manager" },
      { kind: "text", id: "confirm", label: "Password again", default: "", secret: true, placeholder: "Typed twice, since there is no recovery" },
      {
        kind: "number",
        id: "iterations",
        label: "PBKDF2 rounds",
        default: 600000,
        min: 100000,
        max: 5000000,
        step: 50000,
      },
      {
        kind: "select",
        id: "kdfHash",
        label: "Key derivation hash",
        choices: [
          { value: "SHA-256", label: "SHA-256" },
          { value: "SHA-512", label: "SHA-512" },
        ],
        default: "SHA-256",
      },
      {
        kind: "toggle",
        id: "keepName",
        label: "Keep the original extension in the name",
        default: true,
        help: "report.pdf becomes report.pdf.enc. Switch off if the file type itself is sensitive.",
      },
    ],
    related: ["decrypt-file", "encrypt-text", "zip-files", "hash-generator"],
    icon: "FileLock",
  },
  {
    slug: "decrypt-file",
    category: "security",
    title: "Decrypt File",
    short: "Open a .enc file made here and check it hasn't been altered",
    keywords: ["decrypt file online", "open encrypted file", "aes file decryption", "decrypt enc file"],
    io: "file",
    engine: "crypto",
    op: "decryptFile",
    accepts: { mime: [], ext: ["enc"], multiple: true, maxMB: 512 },
    output: { ext: "bin", mime: "application/octet-stream", cardinality: "per-file" },
    options: [
      { kind: "text", id: "password", label: "Password", default: "", secret: true, placeholder: "The password it was encrypted with" },
      { kind: "toggle", id: "restoreName", label: "Restore the original filename", default: true },
    ],
    related: ["encrypt-file", "decrypt-text", "unzip-file"],
    icon: "FileKey",
  },
  {
    slug: "totp-generator",
    category: "security",
    title: "TOTP Code Generator",
    short: "Turn a 2FA seed into the rotating six-digit code, offline",
    keywords: ["totp generator", "2fa code from secret key", "authenticator code online", "hotp generator"],
    io: "text",
    engine: "pure",
    op: "totpGenerate",
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Type",
        choices: [
          { value: "totp", label: "TOTP — time based" },
          { value: "hotp", label: "HOTP — counter based" },
        ],
        default: "totp",
      },
      {
        kind: "select",
        id: "algorithm",
        label: "Algorithm",
        choices: [
          { value: "SHA-1", label: "SHA-1 — what almost everyone uses" },
          { value: "SHA-256", label: "SHA-256" },
          { value: "SHA-512", label: "SHA-512" },
        ],
        default: "SHA-1",
      },
      { kind: "number", id: "digits", label: "Digits", default: 6, min: 6, max: 10, step: 1 },
      { kind: "number", id: "period", label: "Seconds per code", default: 30, min: 10, max: 300, step: 5 },
      { kind: "number", id: "counter", label: "Counter", default: 0, min: 0, max: 1000000, step: 1, showIf: { id: "mode", equals: "hotp" } },
      { kind: "toggle", id: "showNext", label: "Show the next code too", default: true },
    ],
    related: ["qr-code-generator", "hmac-generator", "password-generator"],
    icon: "Timer",
  },
  {
    slug: "split-secret",
    category: "security",
    title: "Split a Secret Into Shares",
    short: "Shamir's scheme — any M of N shares rebuild it, fewer reveal nothing",
    keywords: ["shamir secret sharing", "split password into shares", "secret sharing tool", "seed phrase backup split"],
    io: "text",
    engine: "pure",
    op: "shamirSplit",
    options: [
      { kind: "number", id: "shares", label: "Shares to make", default: 5, min: 2, max: 255, step: 1 },
      {
        kind: "number",
        id: "threshold",
        label: "Shares needed to rebuild",
        default: 3,
        min: 2,
        max: 255,
        step: 1,
        help: "Lower is easier to recover and easier to steal. Three of five is the usual compromise.",
      },
      { kind: "text", id: "label", label: "Label each share", default: "", placeholder: "vault" },
    ],
    related: ["combine-secret-shares", "password-generator", "encrypt-text"],
    icon: "Split",
  },
  {
    slug: "combine-secret-shares",
    category: "security",
    title: "Combine Secret Shares",
    short: "Rebuild a secret from enough of its shares",
    keywords: ["combine shamir shares", "recover secret from shares", "shamir secret recovery", "join secret shares"],
    io: "text",
    engine: "pure",
    op: "shamirCombine",
    options: [
      {
        kind: "toggle",
        id: "asHex",
        label: "Show the result as hex",
        default: false,
        help: "Use this when the secret was binary rather than text.",
      },
    ],
    related: ["split-secret", "decrypt-text", "password-generator"],
    icon: "Merge",
  },
  {
    slug: "rsa-key-generator",
    category: "security",
    title: "RSA Key Pair Generator",
    short: "Generate a PEM key pair in your browser, never on a server",
    keywords: ["rsa key generator", "generate public private key", "pem key pair online", "rsa 2048 key generator"],
    io: "form",
    engine: "pure",
    op: "rsaKeypair",
    options: [
      {
        kind: "select",
        id: "bits",
        label: "Key size",
        choices: [
          { value: "2048", label: "2048 bits — fast, still standard" },
          { value: "3072", label: "3072 bits" },
          { value: "4096", label: "4096 bits — slowest to generate" },
        ],
        default: "2048",
      },
      {
        kind: "select",
        id: "purpose",
        label: "For",
        choices: [
          { value: "sign", label: "Signing — RSASSA-PKCS1-v1_5" },
          { value: "encrypt", label: "Encryption — RSA-OAEP" },
        ],
        default: "sign",
      },
      {
        kind: "select",
        id: "hash",
        label: "Hash",
        choices: [
          { value: "SHA-256", label: "SHA-256" },
          { value: "SHA-384", label: "SHA-384" },
          { value: "SHA-512", label: "SHA-512" },
        ],
        default: "SHA-256",
      },
    ],
    related: ["sign-verify-text", "hash-generator", "encrypt-text"],
    icon: "KeyRound",
  },
  {
    slug: "sign-verify-text",
    category: "security",
    title: "Sign & Verify Text",
    short: "Prove a message came from your key, or check that someone else's did",
    keywords: ["rsa sign online", "verify signature online", "digital signature tool", "sign message with private key"],
    io: "text",
    engine: "pure",
    op: "rsaSign",
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Action",
        choices: [
          { value: "sign", label: "Sign with a private key" },
          { value: "verify", label: "Verify with a public key" },
        ],
        default: "sign",
      },
      {
        kind: "textarea",
        id: "key",
        label: "PEM key",
        default: "",
        rows: 5,
        placeholder: "-----BEGIN PRIVATE KEY-----",
      },
      {
        kind: "textarea",
        id: "signature",
        label: "Signature to check",
        default: "",
        rows: 3,
        showIf: { id: "mode", equals: "verify" },
      },
      {
        kind: "select",
        id: "hash",
        label: "Hash",
        choices: [
          { value: "SHA-256", label: "SHA-256" },
          { value: "SHA-384", label: "SHA-384" },
          { value: "SHA-512", label: "SHA-512" },
        ],
        default: "SHA-256",
      },
    ],
    related: ["rsa-key-generator", "hash-generator", "hmac-generator"],
    icon: "FileSignature",
  },
  {
    slug: "log-anonymizer",
    category: "security",
    title: "Log Anonymizer",
    short: "Strip IPs, emails, cards and tokens out of a log before you share it",
    keywords: ["log anonymizer", "remove pii from logs", "redact log file", "mask ip addresses in text"],
    io: "text",
    engine: "pure",
    op: "logAnonymize",
    options: [
      {
        kind: "select",
        id: "style",
        label: "Replace with",
        choices: [
          { value: "numbered", label: "Numbered tokens — the same value keeps the same tag" },
          { value: "fixed", label: "A fixed tag per type" },
          { value: "redact", label: "[REDACTED]" },
        ],
        default: "numbered",
      },
      { kind: "text", id: "filter", label: "Keep only lines containing", default: "", placeholder: "ERROR" },
      { kind: "toggle", id: "invert", label: "Drop matching lines instead", default: false },
      { kind: "toggle", id: "filterCase", label: "Match case in the filter", default: false },
      { kind: "toggle", id: "email", label: "Mask email addresses", default: true },
      { kind: "toggle", id: "ipv4", label: "Mask IPv4 addresses", default: true },
      { kind: "toggle", id: "ipv6", label: "Mask IPv6 addresses", default: true },
      { kind: "toggle", id: "card", label: "Mask card numbers", default: true, help: "Checked against the Luhn algorithm, so order numbers are left alone." },
      { kind: "toggle", id: "phone", label: "Mask phone numbers", default: true },
      { kind: "toggle", id: "uuid", label: "Mask UUIDs", default: true },
      { kind: "toggle", id: "token", label: "Mask API keys and JWTs", default: true },
      { kind: "toggle", id: "mac", label: "Mask MAC addresses", default: true },
      { kind: "toggle", id: "path", label: "Mask usernames in file paths", default: false },
    ],
    related: ["find-and-replace", "unicode-inspector", "strip-image-metadata"],
    icon: "EyeOff",
  },
  {
    slug: "hide-text-in-image",
    category: "security",
    title: "Hide Text in an Image",
    short: "Write a message into a picture's low bits, optionally encrypted",
    keywords: ["steganography tool", "hide text in image", "lsb steganography online", "hide message in png"],
    io: "file",
    engine: "image",
    op: "stegoHide",
    accepts: {
      mime: ["image/png", "image/jpeg", "image/webp"],
      ext: ["png", "jpg", "jpeg", "webp", "bmp"],
      multiple: true,
      maxMB: 40,
    },
    output: { ext: "png", mime: "image/png", cardinality: "per-file" },
    options: [
      { kind: "textarea", id: "message", label: "Message to hide", default: "", rows: 4 },
      {
        kind: "text",
        id: "password",
        label: "Password (optional)",
        default: "",
        secret: true,
        help: "With one, the message is encrypted before it is hidden, so finding the bits is not the same as reading them.",
      },
      {
        kind: "number",
        id: "bits",
        label: "Bits per colour channel",
        default: 1,
        min: 1,
        max: 2,
        step: 1,
        help: "Two doubles the capacity and is slightly more visible in flat areas.",
      },
    ],
    related: ["reveal-hidden-text", "encrypt-file", "strip-image-metadata"],
    icon: "ImagePlus",
  },
  {
    slug: "reveal-hidden-text",
    category: "security",
    title: "Reveal Hidden Text",
    short: "Read a message hidden in a picture's low bits",
    keywords: ["steganography decoder", "reveal hidden message image", "extract text from png", "lsb decoder online"],
    io: "file",
    engine: "image",
    op: "stegoReveal",
    accepts: {
      mime: ["image/png"],
      ext: ["png", "bmp"],
      multiple: true,
      maxMB: 40,
    },
    output: { ext: "txt", mime: "text/plain", cardinality: "per-file" },
    options: [
      { kind: "text", id: "password", label: "Password", default: "", secret: true, placeholder: "If the message was encrypted" },
      { kind: "number", id: "bits", label: "Bits per colour channel", default: 1, min: 1, max: 2, step: 1 },
      { kind: "toggle", id: "asFile", label: "One text file per image", default: true },
    ],
    related: ["hide-text-in-image", "exif-viewer", "decrypt-file"],
    icon: "ScanEye",
  },
];
