import type { ToolSpec } from "../types";

/**
 * Text & data tools. All `pure` engine — parsing and reshaping, no WASM.
 */
export const TEXT_TOOLS: ToolSpec[] = [
  {
    slug: "json-formatter",
    category: "text",
    title: "JSON Formatter",
    short: "Pretty-print messy JSON and spot the error if it won't parse",
    keywords: ["json formatter", "json beautifier", "format json online", "json pretty print"],
    io: "text",
    engine: "pure",
    op: "jsonFormat",
    options: [
      {
        kind: "select",
        id: "indent",
        label: "Indent with",
        choices: [
          { value: "2", label: "2 spaces" },
          { value: "4", label: "4 spaces" },
          { value: "tab", label: "Tab" },
        ],
        default: "2",
      },
      {
        kind: "toggle",
        id: "sortKeys",
        label: "Sort keys alphabetically",
        default: false,
        help: "Useful when diffing two payloads that list their fields in different orders.",
      },
    ],
    related: ["json-minifier", "json-validator", "json-to-yaml", "json-to-typescript"],
    icon: "Braces",
  },
  {
    slug: "json-minifier",
    category: "text",
    title: "JSON Minifier",
    short: "Strip every space and newline out of a JSON payload",
    keywords: ["json minifier", "minify json", "compress json", "json compact"],
    io: "text",
    engine: "pure",
    op: "jsonMinify",
    options: [],
    related: ["json-formatter", "json-validator"],
    icon: "Minimize2",
  },
  {
    slug: "json-validator",
    category: "text",
    title: "JSON Validator",
    short: "Check JSON is valid and get the line and column of the fault",
    keywords: ["json validator", "validate json", "json syntax checker", "is my json valid"],
    io: "text",
    engine: "pure",
    op: "jsonValidate",
    options: [
      {
        kind: "toggle",
        id: "stats",
        label: "Show a structure summary",
        default: true,
        help: "Counts keys, nesting depth and array lengths once the document parses.",
      },
    ],
    related: ["json-formatter", "json-minifier", "yaml-to-json"],
    icon: "CircleCheck",
  },
  {
    slug: "json-to-yaml",
    category: "text",
    title: "JSON to YAML",
    short: "Convert a JSON document into readable YAML",
    keywords: ["json to yaml", "convert json to yaml", "json yaml converter"],
    io: "text",
    engine: "pure",
    op: "jsonToYaml",
    options: [
      { kind: "select", id: "indent", label: "Indent", choices: [{ value: "2", label: "2 spaces" }, { value: "4", label: "4 spaces" }], default: "2" },
      {
        kind: "toggle",
        id: "quoteStrings",
        label: "Always quote strings",
        default: false,
        help: "Prevents YAML from reading yes, no, on and off as booleans.",
      },
    ],
    related: ["yaml-to-json", "json-formatter", "toml-to-json"],
    icon: "ArrowRightLeft",
  },
  {
    slug: "yaml-to-json",
    category: "text",
    title: "YAML to JSON",
    short: "Turn YAML config into JSON, with clear parse errors",
    keywords: ["yaml to json", "convert yaml to json", "yaml json converter"],
    io: "text",
    engine: "pure",
    op: "yamlToJson",
    options: [
      { kind: "select", id: "indent", label: "Indent", choices: [{ value: "2", label: "2 spaces" }, { value: "4", label: "4 spaces" }, { value: "0", label: "Minified" }], default: "2" },
    ],
    related: ["json-to-yaml", "json-validator", "toml-to-json"],
    icon: "ArrowRightLeft",
  },
  {
    slug: "json-to-csv",
    category: "text",
    title: "JSON to CSV",
    short: "Flatten an array of objects into a spreadsheet-ready CSV",
    keywords: ["json to csv", "convert json to csv", "json csv converter", "json to excel"],
    io: "text",
    engine: "pure",
    op: "jsonToCsv",
    options: [
      {
        kind: "select",
        id: "delimiter",
        label: "Delimiter",
        choices: [
          { value: ",", label: "Comma" },
          { value: ";", label: "Semicolon" },
          { value: "\t", label: "Tab" },
          { value: "|", label: "Pipe" },
        ],
        default: ",",
      },
      {
        kind: "toggle",
        id: "flatten",
        label: "Flatten nested objects",
        default: true,
        help: "A nested { user: { id } } becomes a user.id column instead of raw JSON in a cell.",
      },
      { kind: "toggle", id: "header", label: "Include a header row", default: true },
    ],
    related: ["csv-to-json", "json-formatter", "csv-to-markdown-table"],
    icon: "Table",
  },
  {
    slug: "csv-to-json",
    category: "text",
    title: "CSV to JSON",
    short: "Parse CSV into JSON, quoted fields and all",
    keywords: ["csv to json", "convert csv to json", "csv json converter", "parse csv online"],
    io: "text",
    engine: "pure",
    op: "csvToJson",
    options: [
      {
        kind: "select",
        id: "delimiter",
        label: "Delimiter",
        choices: [
          { value: "auto", label: "Detect automatically" },
          { value: ",", label: "Comma" },
          { value: ";", label: "Semicolon" },
          { value: "\t", label: "Tab" },
          { value: "|", label: "Pipe" },
        ],
        default: "auto",
      },
      { kind: "toggle", id: "header", label: "First row is a header", default: true },
      {
        kind: "toggle",
        id: "typed",
        label: "Convert numbers and booleans",
        default: true,
        help: "Off keeps every value a string, which is safer for IDs with leading zeroes.",
      },
    ],
    related: ["json-to-csv", "json-formatter", "remove-duplicate-lines"],
    icon: "Table",
  },
  {
    slug: "json-to-xml",
    category: "text",
    title: "JSON to XML",
    short: "Convert JSON into an XML document",
    keywords: ["json to xml", "convert json to xml", "json xml converter"],
    io: "text",
    engine: "pure",
    op: "jsonToXml",
    options: [
      { kind: "text", id: "rootName", label: "Root element", default: "root" },
      { kind: "toggle", id: "pretty", label: "Indent the output", default: true },
      { kind: "toggle", id: "declaration", label: "Include the XML declaration", default: true },
    ],
    related: ["xml-to-json", "json-formatter"],
    icon: "FileCode",
  },
  {
    slug: "xml-to-json",
    category: "text",
    title: "XML to JSON",
    short: "Parse XML into JSON, with attributes preserved",
    keywords: ["xml to json", "convert xml to json", "xml json converter", "parse xml online"],
    io: "text",
    engine: "pure",
    op: "xmlToJson",
    options: [
      {
        kind: "toggle",
        id: "attributes",
        label: "Keep attributes",
        default: true,
        help: "Attributes land under an @_ prefix so they never collide with child elements.",
      },
      { kind: "toggle", id: "pretty", label: "Indent the output", default: true },
    ],
    related: ["json-to-xml", "json-formatter", "json-validator"],
    icon: "FileCode",
  },
  {
    slug: "toml-to-json",
    category: "text",
    title: "TOML to JSON",
    short: "Convert a TOML config file into JSON",
    keywords: ["toml to json", "convert toml", "toml parser online", "toml json converter"],
    io: "text",
    engine: "pure",
    op: "tomlToJson",
    options: [
      { kind: "select", id: "indent", label: "Indent", choices: [{ value: "2", label: "2 spaces" }, { value: "4", label: "4 spaces" }], default: "2" },
    ],
    related: ["yaml-to-json", "json-formatter", "json-to-yaml"],
    icon: "Settings2",
  },
  {
    slug: "markdown-to-html",
    category: "text",
    title: "Markdown to HTML",
    short: "Render Markdown into clean HTML you can paste anywhere",
    keywords: ["markdown to html", "md to html", "markdown converter", "markdown renderer"],
    io: "text",
    engine: "pure",
    op: "markdownToHtml",
    options: [
      { kind: "toggle", id: "gfm", label: "GitHub-flavoured Markdown", default: true, help: "Tables, task lists, strikethrough and autolinks." },
      { kind: "toggle", id: "breaks", label: "Treat single newlines as line breaks", default: false },
    ],
    related: ["html-to-markdown", "html-entity-encode", "word-counter"],
    icon: "FileType",
  },
  {
    slug: "html-to-markdown",
    category: "text",
    title: "HTML to Markdown",
    short: "Convert HTML back into tidy Markdown",
    keywords: ["html to markdown", "html to md", "convert html markdown", "markdown from html"],
    io: "text",
    engine: "pure",
    op: "htmlToMarkdown",
    options: [
      {
        kind: "select",
        id: "headingStyle",
        label: "Headings",
        choices: [
          { value: "atx", label: "# Hash style" },
          { value: "setext", label: "Underline style" },
        ],
        default: "atx",
      },
      {
        kind: "select",
        id: "bulletMarker",
        label: "Bullets",
        choices: [
          { value: "-", label: "Hyphen" },
          { value: "*", label: "Asterisk" },
          { value: "+", label: "Plus" },
        ],
        default: "-",
      },
    ],
    related: ["markdown-to-html", "html-entity-decode", "remove-line-breaks"],
    icon: "FileType",
  },
  {
    slug: "text-diff",
    category: "text",
    title: "Text Diff",
    short: "Compare two blocks of text line by line",
    keywords: ["text diff", "compare text online", "diff checker", "text comparison tool"],
    io: "text",
    engine: "pure",
    op: "textDiff",
    options: [
      {
        kind: "select",
        id: "granularity",
        label: "Compare by",
        choices: [
          { value: "line", label: "Line" },
          { value: "word", label: "Word" },
          { value: "char", label: "Character" },
        ],
        default: "line",
      },
      { kind: "toggle", id: "ignoreCase", label: "Ignore case", default: false },
      { kind: "toggle", id: "ignoreWhitespace", label: "Ignore whitespace", default: false },
    ],
    customPanel: true,
    related: ["find-and-replace", "sort-lines", "remove-duplicate-lines"],
    icon: "GitCompare",
  },
  {
    slug: "case-converter",
    category: "text",
    title: "Case Converter",
    short: "Switch text between sentence, title, camel, snake and kebab case",
    keywords: ["case converter", "uppercase lowercase converter", "camel case converter", "title case tool"],
    io: "text",
    engine: "pure",
    op: "caseConvert",
    options: [
      {
        kind: "select",
        id: "target",
        label: "Convert to",
        choices: [
          { value: "lower", label: "lowercase" },
          { value: "upper", label: "UPPERCASE" },
          { value: "sentence", label: "Sentence case" },
          { value: "title", label: "Title Case" },
          { value: "camel", label: "camelCase" },
          { value: "pascal", label: "PascalCase" },
          { value: "snake", label: "snake_case" },
          { value: "constant", label: "CONSTANT_CASE" },
          { value: "kebab", label: "kebab-case" },
          { value: "alternating", label: "aLtErNaTiNg" },
        ],
        default: "title",
      },
    ],
    related: ["slug-generator", "word-counter", "find-and-replace"],
    icon: "CaseSensitive",
  },
  {
    slug: "word-counter",
    category: "text",
    title: "Word Counter",
    short: "Count words, characters, sentences and reading time",
    keywords: ["word counter", "character count", "word count tool", "reading time calculator"],
    io: "text",
    engine: "pure",
    op: "wordCount",
    options: [
      { kind: "number", id: "wpm", label: "Reading speed", default: 225, min: 80, max: 600, step: 5, unit: "wpm" },
      { kind: "toggle", id: "topWords", label: "List the most frequent words", default: true },
    ],
    related: ["case-converter", "remove-duplicate-lines", "lorem-ipsum-generator"],
    icon: "Hash",
  },
  {
    slug: "sort-lines",
    category: "text",
    title: "Sort Lines",
    short: "Alphabetical, numeric or natural sort, forwards or back",
    keywords: ["sort lines", "alphabetize list", "sort text online", "line sorter"],
    io: "text",
    engine: "pure",
    op: "sortLines",
    options: [
      {
        kind: "select",
        id: "order",
        label: "Order",
        choices: [
          { value: "asc", label: "A to Z" },
          { value: "desc", label: "Z to A" },
          { value: "length", label: "Shortest first" },
          { value: "random", label: "Shuffle" },
        ],
        default: "asc",
      },
      {
        kind: "toggle",
        id: "natural",
        label: "Natural number order",
        default: true,
        help: "Puts item2 before item10 instead of after it.",
      },
      { kind: "toggle", id: "ignoreCase", label: "Ignore case", default: true },
      { kind: "toggle", id: "dedupe", label: "Remove duplicates while sorting", default: false },
    ],
    related: ["remove-duplicate-lines", "remove-line-breaks", "text-diff"],
    icon: "ArrowDownAZ",
  },
  {
    slug: "remove-duplicate-lines",
    category: "text",
    title: "Remove Duplicate Lines",
    short: "Keep one of each line and see how many went",
    keywords: ["remove duplicate lines", "deduplicate text", "unique lines", "delete duplicates"],
    io: "text",
    engine: "pure",
    op: "dedupeLines",
    options: [
      { kind: "toggle", id: "ignoreCase", label: "Ignore case", default: false },
      { kind: "toggle", id: "trim", label: "Ignore leading and trailing spaces", default: true },
      { kind: "toggle", id: "keepEmpty", label: "Keep blank lines", default: false },
      {
        kind: "select",
        id: "keep",
        label: "Keep",
        choices: [
          { value: "first", label: "The first occurrence" },
          { value: "last", label: "The last occurrence" },
          { value: "unique", label: "Only lines that appear once" },
        ],
        default: "first",
      },
    ],
    related: ["sort-lines", "find-and-replace", "csv-to-json"],
    icon: "Rows3",
  },
  {
    slug: "find-and-replace",
    category: "text",
    title: "Find and Replace",
    short: "Bulk replace across a whole document, plain or regex",
    keywords: ["find and replace online", "bulk replace text", "replace text tool", "regex replace"],
    io: "text",
    engine: "pure",
    op: "findReplace",
    options: [
      { kind: "text", id: "find", label: "Find", default: "", placeholder: "old text" },
      { kind: "text", id: "replace", label: "Replace with", default: "", placeholder: "new text" },
      { kind: "toggle", id: "regex", label: "Treat as a regular expression", default: false },
      { kind: "toggle", id: "caseSensitive", label: "Match case", default: false },
      { kind: "toggle", id: "wholeWord", label: "Whole words only", default: false, showIf: { id: "regex", equals: false } },
    ],
    related: ["regex-tester", "text-diff", "remove-line-breaks"],
    icon: "Replace",
  },
  {
    slug: "remove-line-breaks",
    category: "text",
    title: "Remove Line Breaks",
    short: "Unwrap hard-wrapped text without losing paragraphs",
    keywords: ["remove line breaks", "remove line breaks from text", "unwrap text", "join lines"],
    io: "text",
    engine: "pure",
    op: "removeLineBreaks",
    options: [
      {
        kind: "select",
        id: "mode",
        label: "Remove",
        choices: [
          { value: "single", label: "Single breaks — keep paragraphs" },
          { value: "all", label: "Every break — one long line" },
          { value: "extra", label: "Only runs of blank lines" },
        ],
        default: "single",
      },
      { kind: "text", id: "joiner", label: "Join with", default: " ", maxLength: 4 },
      { kind: "toggle", id: "trimLines", label: "Trim spaces from each line", default: true },
    ],
    related: ["sort-lines", "find-and-replace", "word-counter"],
    icon: "WrapText",
  },
  {
    slug: "csv-to-markdown-table",
    category: "text",
    title: "CSV to Markdown Table",
    short: "Paste a CSV, get a formatted Markdown table",
    keywords: ["csv to markdown", "markdown table generator", "csv table converter", "make markdown table"],
    io: "text",
    engine: "pure",
    op: "csvToMarkdown",
    options: [
      {
        kind: "select",
        id: "delimiter",
        label: "Delimiter",
        choices: [
          { value: "auto", label: "Detect automatically" },
          { value: ",", label: "Comma" },
          { value: ";", label: "Semicolon" },
          { value: "\t", label: "Tab" },
        ],
        default: "auto",
      },
      {
        kind: "select",
        id: "align",
        label: "Column alignment",
        choices: [
          { value: "none", label: "Default" },
          { value: "left", label: "Left" },
          { value: "center", label: "Centre" },
          { value: "right", label: "Right" },
        ],
        default: "none",
      },
      { kind: "toggle", id: "pad", label: "Pad cells so the source lines up", default: true },
    ],
    related: ["csv-to-json", "json-to-csv", "markdown-to-html"],
    icon: "Table2",
  },
];
