import type { AcceptSpec, OptionSpec, OutputSpec, ToolSpec } from "../types";

/**
 * Video tools.
 *
 * Every one of these runs on WebCodecs — the same decoders and encoders the
 * browser already uses to play video — with container work done in TypeScript
 * by Mediabunny. There is no FFmpeg build behind them, which is the reason a
 * page here is usable the moment it loads rather than after a thirty-megabyte
 * download, and the reason the site needs none of the cross-origin isolation
 * that such a build would impose on every other page.
 *
 * The limit that buys is real and is stated on the pages: what can be read is
 * what this browser can play.
 */

const VIDEO_IN: AcceptSpec = {
  mime: ["video/*"],
  ext: ["mp4", "m4v", "mov", "qt", "webm", "mkv", "ts", "mts", "m2ts"],
  multiple: false,
  maxMB: 500,
};

const VIDEOS_IN: AcceptSpec = { ...VIDEO_IN, multiple: true };

const VIDEO_OUT: OutputSpec = { ext: "mp4", mime: "video/mp4", cardinality: "per-file" };
const ONE_VIDEO_OUT: OutputSpec = { ...VIDEO_OUT, cardinality: "single" };

/**
 * The container, on every tool that writes video.
 *
 * MP4 leads because it is the file that plays everywhere — the television, the
 * ten-year-old phone, the upload form that rejects everything else. WebM is
 * kept beside it because its codecs are royalty-free and because a device that
 * cannot encode H.264 can almost always encode VP9.
 */
const formatOptions: OptionSpec[] = [
  {
    kind: "select",
    id: "format",
    label: "Save as",
    choices: [
      { value: "mp4", label: "MP4 — plays everywhere" },
      { value: "webm", label: "WebM — royalty-free, smaller" },
      { value: "mkv", label: "MKV — holds anything" },
      { value: "mov", label: "MOV — QuickTime" },
    ],
    default: "mp4",
  },
  {
    kind: "select",
    id: "quality",
    label: "Quality",
    choices: [
      { value: "very-high", label: "Very high — largest file" },
      { value: "high", label: "High" },
      { value: "medium", label: "Medium" },
      { value: "low", label: "Low — smallest file" },
    ],
    default: "high",
  },
];

const positionChoices = [
  { value: "top-left", label: "Top left" },
  { value: "top-center", label: "Top centre" },
  { value: "top-right", label: "Top right" },
  { value: "middle-left", label: "Middle left" },
  { value: "middle-center", label: "Centre" },
  { value: "middle-right", label: "Middle right" },
  { value: "bottom-left", label: "Bottom left" },
  { value: "bottom-center", label: "Bottom centre" },
  { value: "bottom-right", label: "Bottom right" },
];

export const VIDEO_TOOLS: ToolSpec[] = [
  {
    slug: "trim-video",
    category: "video",
    title: "Trim Video",
    short: "Cut a clip out of a video, by start and end time",
    keywords: ["trim video online", "cut video", "video trimmer", "crop video length"],
    io: "file",
    engine: "video",
    op: "trimVideo",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    options: [
      {
        kind: "text",
        id: "start",
        label: "Start at",
        default: "",
        placeholder: "0:00",
        help: "Seconds, or minutes:seconds. Leave empty to start at the beginning.",
      },
      {
        kind: "text",
        id: "end",
        label: "End at",
        default: "",
        placeholder: "end of video",
        help: "Leave empty to run to the end.",
      },
      ...formatOptions,
    ],
    related: ["merge-videos", "compress-video", "video-to-gif", "crop-video"],
    icon: "Scissors",
  },
  {
    slug: "compress-video",
    category: "video",
    title: "Compress Video",
    short: "Make a video file smaller, with the size levers that actually work",
    keywords: ["compress video online", "reduce video file size", "make video smaller", "shrink mp4"],
    io: "file",
    engine: "video",
    op: "compressVideo",
    accepts: VIDEOS_IN,
    output: VIDEO_OUT,
    options: [
      {
        kind: "select",
        id: "maxHeight",
        label: "Shrink the picture to",
        choices: [
          { value: "0", label: "Leave the size alone" },
          { value: "1080", label: "1080p — full HD" },
          { value: "720", label: "720p — HD, a good default" },
          { value: "480", label: "480p — small, fine on a phone" },
          { value: "360", label: "360p — email-sized" },
        ],
        default: "720",
        help: "The biggest lever there is. Half the height is a quarter of the pixels, which no quality setting can match.",
      },
      {
        kind: "select",
        id: "frameRate",
        label: "Frames per second",
        choices: [
          { value: "0", label: "Leave it alone" },
          { value: "30", label: "30 — smooth" },
          { value: "24", label: "24 — film" },
          { value: "15", label: "15 — screen recordings and slides" },
        ],
        default: "0",
      },
      ...formatOptions,
    ],
    related: ["resize-video", "convert-video", "trim-video", "video-to-gif"],
    icon: "Minimize2",
  },
  {
    slug: "convert-video",
    category: "video",
    title: "Video Converter",
    short: "Move a video between MP4, WebM, MKV and MOV",
    keywords: ["video converter", "mov to mp4", "webm to mp4", "mkv to mp4 online"],
    io: "file",
    engine: "video",
    op: "convertVideo",
    accepts: VIDEOS_IN,
    output: VIDEO_OUT,
    options: formatOptions,
    related: ["compress-video", "video-to-mp3", "resize-video", "trim-video"],
    icon: "RefreshCw",
  },
  {
    slug: "resize-video",
    category: "video",
    title: "Resize Video",
    short: "Change the resolution, by preset or by exact size",
    keywords: ["resize video online", "change video resolution", "1080p to 720p", "scale video"],
    io: "file",
    engine: "video",
    op: "resizeVideo",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    options: [
      {
        kind: "select",
        id: "mode",
        label: "How",
        choices: [
          { value: "preset", label: "A standard size" },
          { value: "custom", label: "Exact dimensions" },
        ],
        default: "preset",
      },
      {
        kind: "select",
        id: "preset",
        label: "Size",
        choices: [
          { value: "2160", label: "2160p — 4K" },
          { value: "1440", label: "1440p — 2K" },
          { value: "1080", label: "1080p — full HD" },
          { value: "720", label: "720p — HD" },
          { value: "480", label: "480p" },
          { value: "360", label: "360p" },
          { value: "240", label: "240p" },
        ],
        default: "720",
        showIf: { id: "mode", equals: "preset" },
      },
      {
        kind: "toggle",
        id: "upscale",
        label: "Allow enlarging",
        default: false,
        showIf: { id: "mode", equals: "preset" },
        help: "Off by default. Enlarging cannot recover detail that was never recorded — it only makes the file bigger.",
      },
      {
        kind: "number",
        id: "width",
        label: "Width",
        default: 0,
        min: 0,
        max: 7680,
        unit: "px",
        showIf: { id: "mode", equals: "custom" },
        help: "Leave at 0 to work it out from the height.",
      },
      {
        kind: "number",
        id: "height",
        label: "Height",
        default: 0,
        min: 0,
        max: 4320,
        unit: "px",
        showIf: { id: "mode", equals: "custom" },
      },
      {
        kind: "select",
        id: "fit",
        label: "If the shape does not match",
        choices: [
          { value: "contain", label: "Fit inside, with bars" },
          { value: "cover", label: "Fill the frame, cropping the overflow" },
          { value: "fill", label: "Stretch to fit" },
        ],
        default: "contain",
        showIf: { id: "mode", equals: "custom" },
      },
      ...formatOptions,
    ],
    related: ["compress-video", "crop-video", "convert-video", "rotate-video"],
    icon: "Scaling",
  },
  {
    slug: "crop-video",
    category: "video",
    title: "Crop Video",
    short: "Keep a rectangle of the picture and throw the rest away",
    keywords: ["crop video online", "cut video edges", "crop mp4", "change video aspect ratio"],
    io: "file",
    engine: "video",
    op: "cropVideo",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    options: [
      { kind: "slider", id: "x", label: "From the left", min: 0, max: 95, step: 1, default: 0, unit: "%" },
      { kind: "slider", id: "y", label: "From the top", min: 0, max: 95, step: 1, default: 0, unit: "%" },
      { kind: "slider", id: "width", label: "Width", min: 5, max: 100, step: 1, default: 100, unit: "%" },
      { kind: "slider", id: "height", label: "Height", min: 5, max: 100, step: 1, default: 100, unit: "%" },
      ...formatOptions,
    ],
    related: ["resize-video", "rotate-video", "hide-video-region", "trim-video"],
    icon: "Crop",
  },
  {
    slug: "rotate-video",
    category: "video",
    title: "Rotate Video",
    short: "Turn a video the right way up, permanently",
    keywords: ["rotate video online", "fix sideways video", "turn video 90 degrees", "rotate mp4"],
    io: "file",
    engine: "video",
    op: "rotateVideo",
    accepts: VIDEOS_IN,
    output: VIDEO_OUT,
    options: [
      {
        kind: "select",
        id: "angle",
        label: "Turn it",
        choices: [
          { value: "90", label: "90° clockwise" },
          { value: "180", label: "180° — upside down" },
          { value: "270", label: "90° anticlockwise" },
        ],
        default: "90",
      },
      {
        kind: "toggle",
        id: "bake",
        label: "Turn the pixels, not just the label",
        default: true,
        help: "A rotation can be written as a flag in the file header, which is instant and lossless — but plenty of players and upload forms ignore it and show the video sideways anyway.",
      },
      ...formatOptions,
    ],
    related: ["flip-video", "crop-video", "resize-video", "convert-video"],
    icon: "RotateCw",
  },
  {
    slug: "flip-video",
    category: "video",
    title: "Flip Video",
    short: "Mirror a video left-to-right or top-to-bottom",
    keywords: ["flip video online", "mirror video", "reverse video horizontally", "unmirror selfie video"],
    io: "file",
    engine: "video",
    op: "flipVideo",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    options: [
      {
        kind: "select",
        id: "axis",
        label: "Mirror",
        choices: [
          { value: "horizontal", label: "Left to right" },
          { value: "vertical", label: "Top to bottom" },
          { value: "both", label: "Both — same as a 180° turn" },
        ],
        default: "horizontal",
      },
      ...formatOptions,
    ],
    related: ["rotate-video", "crop-video", "add-text-to-video", "resize-video"],
    icon: "FlipHorizontal",
  },
  {
    slug: "change-video-speed",
    category: "video",
    title: "Change Video Speed",
    short: "Play a video faster or slower, sound and all",
    keywords: ["change video speed", "speed up video online", "slow motion video", "timelapse from video"],
    io: "file",
    engine: "video",
    op: "changeVideoSpeed",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    options: [
      {
        kind: "select",
        id: "rate",
        label: "Speed",
        choices: [
          { value: "0.25", label: "Quarter speed — slow motion" },
          { value: "0.5", label: "Half speed" },
          { value: "1.5", label: "One and a half times" },
          { value: "2", label: "Double speed" },
          { value: "4", label: "Four times" },
          { value: "8", label: "Eight times — timelapse" },
        ],
        default: "2",
      },
      {
        kind: "select",
        id: "sound",
        label: "The sound",
        choices: [
          { value: "keep", label: "Speed it up too — pitch rises" },
          { value: "drop", label: "Drop it — silent result" },
        ],
        default: "keep",
      },
      ...formatOptions,
    ],
    related: ["trim-video", "loop-video", "change-audio-speed", "compress-video"],
    icon: "Gauge",
  },
  {
    slug: "merge-videos",
    category: "video",
    title: "Merge Videos",
    short: "Join several clips end to end, in the order you choose",
    keywords: ["merge videos online", "join video clips", "combine mp4 files", "video joiner"],
    io: "file",
    engine: "video",
    op: "mergeVideos",
    accepts: VIDEOS_IN,
    output: ONE_VIDEO_OUT,
    options: formatOptions,
    related: ["trim-video", "loop-video", "add-audio-to-video", "compress-video"],
    icon: "Layers",
  },
  {
    slug: "loop-video",
    category: "video",
    title: "Loop Video",
    short: "Repeat a clip a set number of times in one file",
    keywords: ["loop video online", "repeat video", "make video loop", "boomerang video"],
    io: "file",
    engine: "video",
    op: "loopVideo",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    options: [
      {
        kind: "number",
        id: "times",
        label: "Repeat",
        default: 3,
        min: 2,
        max: 50,
        step: 1,
        unit: "times",
        help: "The copies are laid end to end in one file, so the loop plays anywhere — including the places that ignore a player's repeat setting.",
      },
      ...formatOptions,
    ],
    related: ["merge-videos", "trim-video", "video-to-gif", "change-video-speed"],
    icon: "Repeat",
  },
  {
    slug: "mute-video",
    category: "video",
    title: "Mute Video",
    short: "Remove the sound track and keep the picture untouched",
    keywords: ["mute video online", "remove audio from video", "silent video", "strip sound from mp4"],
    io: "file",
    engine: "video",
    op: "muteVideo",
    accepts: VIDEOS_IN,
    output: VIDEO_OUT,
    options: formatOptions,
    related: ["change-video-volume", "video-to-mp3", "add-audio-to-video", "compress-video"],
    icon: "VolumeX",
  },
  {
    slug: "change-video-volume",
    category: "video",
    title: "Change Video Volume",
    short: "Make a video louder or quieter without touching the picture",
    keywords: ["change video volume", "increase video volume online", "make video louder", "quieten video"],
    io: "file",
    engine: "video",
    op: "changeVideoVolume",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    options: [
      {
        kind: "slider",
        id: "decibels",
        label: "Change by",
        min: -30,
        max: 20,
        step: 1,
        default: 6,
        unit: " dB",
        help: "Six decibels up is roughly twice as loud, six down roughly half.",
      },
      ...formatOptions,
    ],
    related: ["mute-video", "add-audio-to-video", "video-to-mp3", "change-audio-volume"],
    icon: "Volume2",
  },
  {
    slug: "add-audio-to-video",
    category: "video",
    title: "Add Audio to Video",
    short: "Put a soundtrack or voiceover under a video",
    keywords: ["add audio to video", "add music to video online", "replace video audio", "voiceover video"],
    io: "file",
    engine: "video",
    op: "addAudioToVideo",
    accepts: {
      mime: ["video/*", "audio/*"],
      ext: ["mp4", "m4v", "mov", "webm", "mkv", "mp3", "wav", "m4a", "aac", "ogg", "opus", "flac"],
      multiple: true,
      maxMB: 500,
    },
    output: VIDEO_OUT,
    options: [
      {
        kind: "select",
        id: "mode",
        label: "The video's own sound",
        choices: [
          { value: "replace", label: "Replace it" },
          { value: "mix", label: "Keep it and mix the new track over" },
        ],
        default: "replace",
      },
      {
        kind: "slider",
        id: "level",
        label: "New track level",
        min: 10,
        max: 90,
        step: 5,
        default: 50,
        unit: "%",
        showIf: { id: "mode", equals: "mix" },
      },
      {
        kind: "select",
        id: "fit",
        label: "If the sound is shorter than the video",
        choices: [
          { value: "loop", label: "Repeat it to the end" },
          { value: "stop", label: "Let it stop" },
        ],
        default: "loop",
      },
      ...formatOptions,
    ],
    related: ["mute-video", "change-video-volume", "merge-videos", "video-to-mp3"],
    icon: "Music",
  },
  {
    slug: "video-to-mp3",
    category: "video",
    title: "Video to MP3",
    short: "Take the sound out of a video as MP3 or WAV",
    keywords: ["video to mp3", "extract audio from video", "mp4 to mp3 online", "video to wav"],
    io: "file",
    engine: "video",
    op: "videoToAudio",
    accepts: VIDEOS_IN,
    output: { ext: "mp3", mime: "audio/mpeg", cardinality: "per-file" },
    options: [
      {
        kind: "select",
        id: "format",
        label: "Save as",
        choices: [
          { value: "mp3", label: "MP3 — small, plays anywhere" },
          { value: "wav", label: "WAV — uncompressed, about ten times larger" },
        ],
        default: "mp3",
      },
      {
        kind: "select",
        id: "quality",
        label: "MP3 quality",
        choices: [
          { value: "very-high", label: "Very high" },
          { value: "high", label: "High" },
          { value: "medium", label: "Medium" },
          { value: "low", label: "Low — speech only" },
        ],
        default: "high",
        showIf: { id: "format", equals: "mp3" },
      },
    ],
    related: ["mute-video", "trim-audio", "change-audio-volume", "convert-video"],
    icon: "AudioLines",
  },
  {
    slug: "video-to-gif",
    category: "video",
    title: "Video to GIF",
    short: "Turn a few seconds of video into an animated GIF",
    keywords: ["video to gif", "mp4 to gif online", "make a gif from video", "gif maker"],
    io: "file",
    engine: "video",
    op: "videoToGif",
    accepts: VIDEO_IN,
    output: { ext: "gif", mime: "image/gif", cardinality: "single" },
    options: [
      { kind: "text", id: "start", label: "Start at", default: "", placeholder: "0:00" },
      {
        kind: "text",
        id: "end",
        label: "End at",
        default: "",
        placeholder: "ten seconds in",
        help: "GIF has no compression between frames. Keep it short unless you want a file measured in tens of megabytes.",
      },
      { kind: "slider", id: "fps", label: "Frames per second", min: 5, max: 30, step: 1, default: 12 },
      { kind: "slider", id: "width", label: "Width", min: 120, max: 1000, step: 20, default: 480, unit: "px" },
    ],
    related: ["trim-video", "video-thumbnail", "loop-video", "compress-video"],
    icon: "Film",
  },
  {
    slug: "video-thumbnail",
    category: "video",
    title: "Video to Image",
    short: "Grab a single frame as a PNG or JPEG",
    keywords: ["video to image", "grab frame from video", "video thumbnail maker", "screenshot from video"],
    io: "file",
    engine: "video",
    op: "videoThumbnail",
    accepts: VIDEOS_IN,
    output: { ext: "png", mime: "image/png", cardinality: "per-file" },
    options: [
      {
        kind: "text",
        id: "at",
        label: "Take the frame at",
        default: "",
        placeholder: "0:00",
        help: "Seconds, or minutes:seconds.",
      },
      {
        kind: "select",
        id: "format",
        label: "Save as",
        choices: [
          { value: "png", label: "PNG — exactly what the decoder produced" },
          { value: "jpg", label: "JPEG — a fraction of the size" },
        ],
        default: "png",
      },
      {
        kind: "slider",
        id: "quality",
        label: "JPEG quality",
        min: 40,
        max: 100,
        step: 5,
        default: 90,
        unit: "%",
        showIf: { id: "format", equals: "jpg" },
      },
      { kind: "number", id: "width", label: "Width", default: 0, min: 0, max: 4000, unit: "px", help: "Leave at 0 for the video's own size." },
    ],
    related: ["video-to-gif", "trim-video", "compress-image", "resize-image"],
    icon: "Image",
  },
  {
    slug: "add-text-to-video",
    category: "video",
    title: "Add Text to Video",
    short: "Burn a caption, title or credit into every frame",
    keywords: ["add text to video", "video caption maker", "put words on video", "video title overlay"],
    io: "file",
    engine: "video",
    op: "addTextToVideo",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    options: [
      {
        kind: "textarea",
        id: "text",
        label: "The words",
        default: "",
        rows: 2,
        placeholder: "Shot on the roof, March 2026",
      },
      { kind: "select", id: "position", label: "Where", choices: positionChoices, default: "bottom-center" },
      { kind: "slider", id: "size", label: "Size", min: 2, max: 20, step: 1, default: 6, unit: "% of height" },
      { kind: "color", id: "colour", label: "Colour", default: "#ffffff" },
      {
        kind: "toggle",
        id: "shadow",
        label: "Shadow behind the text",
        default: true,
        help: "White text over a bright frame is unreadable, and a video's frames are not one colour. A shadow works over both.",
      },
      { kind: "slider", id: "margin", label: "Margin", min: 0, max: 20, step: 1, default: 4, unit: "%" },
      ...formatOptions,
    ],
    related: ["add-image-to-video", "hide-video-region", "crop-video", "trim-video"],
    icon: "Type",
  },
  {
    slug: "add-image-to-video",
    category: "video",
    title: "Add Image to Video",
    short: "Place a logo or watermark on every frame",
    keywords: ["add logo to video", "watermark video online", "put image on video", "video watermark maker"],
    io: "file",
    engine: "video",
    op: "addImageToVideo",
    accepts: {
      mime: ["video/*", "image/*"],
      ext: ["mp4", "m4v", "mov", "webm", "mkv", "png", "jpg", "jpeg", "webp", "gif", "svg"],
      multiple: true,
      maxMB: 500,
    },
    output: VIDEO_OUT,
    options: [
      { kind: "select", id: "position", label: "Where", choices: positionChoices, default: "bottom-right" },
      { kind: "slider", id: "scale", label: "Width", min: 5, max: 60, step: 1, default: 20, unit: "% of frame" },
      { kind: "slider", id: "opacity", label: "Opacity", min: 10, max: 100, step: 5, default: 85, unit: "%" },
      { kind: "slider", id: "margin", label: "Margin", min: 0, max: 20, step: 1, default: 3, unit: "%" },
      ...formatOptions,
    ],
    related: ["add-text-to-video", "hide-video-region", "crop-video", "compress-video"],
    icon: "Stamp",
  },
  {
    slug: "hide-video-region",
    category: "video",
    title: "Blur Part of a Video",
    short: "Blur, pixelate or black out a rectangle for the whole clip",
    keywords: ["blur video online", "hide face in video", "pixelate video", "remove logo from video"],
    io: "file",
    engine: "video",
    op: "hideVideoRegion",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    options: [
      {
        kind: "select",
        id: "method",
        label: "How",
        choices: [
          { value: "blur", label: "Blur" },
          { value: "pixelate", label: "Pixelate" },
          { value: "black", label: "Solid black" },
        ],
        default: "blur",
      },
      { kind: "slider", id: "strength", label: "Strength", min: 4, max: 60, step: 2, default: 20, showIf: { id: "method", equals: "blur" } },
      { kind: "slider", id: "x", label: "From the left", min: 0, max: 95, step: 1, default: 60, unit: "%" },
      { kind: "slider", id: "y", label: "From the top", min: 0, max: 95, step: 1, default: 5, unit: "%" },
      { kind: "slider", id: "width", label: "Width", min: 5, max: 100, step: 1, default: 30, unit: "%" },
      { kind: "slider", id: "height", label: "Height", min: 5, max: 100, step: 1, default: 15, unit: "%" },
      ...formatOptions,
    ],
    related: ["crop-video", "add-image-to-video", "add-text-to-video", "blur-image-area"],
    icon: "EyeOff",
  },
  {
    slug: "screen-recorder",
    category: "video",
    title: "Screen Recorder",
    short: "Record a window, a tab or the whole screen — nothing is uploaded",
    keywords: ["screen recorder online", "record screen in browser", "free screen recording", "record tab with audio"],
    io: "file",
    engine: "video",
    op: "exportVideoRecording",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    record: "screen",
    options: formatOptions,
    related: ["video-recorder", "trim-video", "compress-video", "video-to-gif"],
    icon: "MonitorPlay",
  },
  {
    slug: "video-recorder",
    category: "video",
    title: "Video Recorder",
    short: "Record from the camera and keep the file on your own machine",
    keywords: ["webcam recorder online", "record video in browser", "camera recorder", "record video no upload"],
    io: "file",
    engine: "video",
    op: "exportVideoRecording",
    accepts: VIDEO_IN,
    output: VIDEO_OUT,
    record: "camera",
    options: formatOptions,
    related: ["screen-recorder", "trim-video", "voice-recorder", "compress-video"],
    icon: "Video",
  },
];
